#!/usr/bin/env bash
# Astucia Wiki — Copyright (C) 2026 Mads Rotwitt
# Free software under the GNU GPL v3 or later. See LICENSE for the full notice,
# or <https://www.gnu.org/licenses/>. Distributed WITHOUT ANY WARRANTY.
#
# What a run says when it produces no answer.
#
# Two of the three wire families reported a token-ceiling truncation clearly; OpenAI
# chat-completions never checked finish_reason === 'length' at all, so a truncated run
# fell through to an empty reply and reported "No response was generated." — which is the
# least useful thing it could say, and points at the wrong cause. A reasoning model at
# high effort is exactly the case that hits it: reasoning tokens come out of the same
# ceiling as the answer, so the model can spend the whole budget thinking and return
# `length` with empty content.

set -uo pipefail
cd "$(dirname "$0")"
. lib/assert.sh
. lib/fixture.sh

fixture_start otp || exit 1
trap fixture_stop EXIT
fixture_space Main
fixture_page 'Main/Notes.md' '# A page'

# A stub whose reply shape is chosen per request, so each failure mode is reproducible.
cat > "$WIKI_APP/__test_llm.php" <<'PHP'
<?php
// GENERATED BY tests/ai_failure_reporting.test.sh — never part of a release.
$dir  = dirname(__DIR__);
$mode = $_GET['mode'] ?? 'length';
$n    = (int)@file_get_contents($dir . '/calls.txt') + 1;
file_put_contents($dir . '/calls.txt', (string)$n);
header('Content-Type: application/json');
$stop  = ['choices' => [['finish_reason' => 'stop', 'message' => ['role' => 'assistant', 'content' => 'Done.']]]];
$empty = ['choices' => [['finish_reason' => 'stop', 'message' => ['role' => 'assistant', 'content' => '']]]];
$len   = ['choices' => [['finish_reason' => 'length', 'message' => ['role' => 'assistant', 'content' => '']]]];
$tool  = ['choices' => [['finish_reason' => 'tool_calls', 'message' => [
             'role' => 'assistant', 'content' => null,
             'tool_calls' => [['id' => 'c1', 'type' => 'function',
                               'function' => ['name' => 'wiki_read_page',
                                              'arguments' => '{"path":"Notes.md"}']]]]]]];
if ($mode === 'length')            { echo json_encode($len);   return; }   // truncated at once
if ($mode === 'empty')             { echo json_encode($empty); return; }   // said nothing, no tools
if ($mode === 'tool_then_length')  { echo json_encode($n === 1 ? $tool : $len);   return; }
if ($mode === 'tool_then_empty')   { echo json_encode($n === 1 ? $tool : $empty); return; }
// finish_reason says tool_calls, but none were sent.
if ($mode === 'phantom_tool') {
    echo json_encode(['choices' => [['finish_reason' => 'tool_calls',
                      'message' => ['role' => 'assistant', 'content' => null, 'tool_calls' => []]]]]);
    return;
}
// A reasoning model that stops after its analysis turn. This is the shape reported from a
// real gpt120b run at effort=high: finish_reason stop, content null, and the text in both
// reasoning fields. Repeated on every call, so the nudge gets a second one just like it.
if ($mode === 'reasoning_only') {
    echo json_encode(['choices' => [['finish_reason' => 'stop', 'message' => [
        'role' => 'assistant', 'content' => null, 'refusal' => null, 'tool_calls' => [],
        'reasoning' => 'I considered the sales figures and concluded...',
        'reasoning_content' => 'I considered the sales figures and concluded...']]]]);
    return;
}
// Analysis first, then a proper answer when asked — what the nudge is for.
if ($mode === 'reasoning_then_answer') {
    if ($n === 1) {
        echo json_encode(['choices' => [['finish_reason' => 'stop', 'message' => [
            'role' => 'assistant', 'content' => null,
            'reasoning_content' => 'Let me think about the figures first.']]]]);
    } else {
        echo json_encode(['choices' => [['finish_reason' => 'stop',
            'message' => ['role' => 'assistant', 'content' => 'Revenue grew 50% in Q1.']]]]);
    }
    return;
}
echo json_encode($stop);
PHP

run_job() {  # run_job <mode> <effort>
    rm -f "$WIKI_ROOT/calls.txt"
    (cd "$WIKI_APP" && STUB="$WIKI_URL/__test_llm.php?mode=$1" EFFORT="$2" php -r '
require "config.php"; require "indexer.php"; require "space_settings.php";
require "ai_core.php"; require "mailer.php"; require "agent_jobs.php";
$space_dir = rtrim(PAGES_DIR, "/") . "/Main";
$cfg = ["provider" => "openai", "model" => "m", "api_key" => "k",
        "api_url" => getenv("STUB"), "max_tokens" => 16000];
if (getenv("EFFORT") !== "") $cfg["reasoning_effort"] = getenv("EFFORT");
$ai  = ["uid" => -9, "name" => "Bot", "role" => "editor", "is_ai" => true, "ai_config" => $cfg];
$res = run_agent_job(["id" => "j1", "prompt" => "go", "space" => "Main",
                      "thinking" => wiki_ai_thinking_config($cfg)],
                     $ai, new PageIndexer($space_dir), $space_dir);
echo "ERROR=", (string)($res["error"] ?? "(none)"), "\n";
echo "REPLY=", (string)($res["reply"] ?? "(none)"), "\n";' 2>&1)
}

section 'a truncated run says so instead of "no response"'
r=$(run_job length high)
assert_contains     "names the cause"          'Response truncated'          "$r"
assert_contains     "quotes the ceiling"       '16,000'                      "$r"
assert_contains     "explains high effort"     'Extended reasoning is charged against that same limit' "$r"
assert_contains     "and says what to change"  'raise Max Tokens'            "$r"
assert_not_contains "not the old message"      'No response was generated'   "$r"

section '  …and mentions reasoning only when the AI reasons'
r=$(run_job length "")
assert_contains     "still names the cause"    'Response truncated'          "$r"
assert_contains     "generic advice"           'Increase Max Tokens'         "$r"
assert_not_contains "no reasoning clause"      'Extended reasoning'          "$r"

section 'truncation after real work is still truncation'
r=$(run_job tool_then_length high)
assert_contains     "reported as truncated"    'Response truncated'          "$r"

section 'work done but no closing sentence names what ran'
# This is what a job that wrote to the wiki and then went quiet used to report as a flat
# failure, sending the reader looking for work that had already happened.
r=$(run_job tool_then_empty high)
assert_contains     "says the run did call tools" 'it did call'              "$r"
assert_contains     "names the tool"              'wiki_read_page'           "$r"
assert_contains     "says the changes are saved"  'already saved'            "$r"
assert_not_contains "not the old message"         'No response was generated' "$r"

section 'a model that genuinely said nothing still reports plainly'
r=$(run_job empty high)
assert_contains     "the plain message survives" 'No response was generated' "$r"
# …but it now carries the evidence, which is what separates the causes below.
assert_contains     "with the finish_reason"     'finish_reason=stop'        "$r"
assert_contains     "and the message shape"      'content=empty'             "$r"

section 'a tool_calls finish with no tool calls says so'
r=$(run_job phantom_tool high)
assert_contains     "names what happened"        'signalled a tool call but sent none' "$r"
assert_contains     "with the evidence"          'finish_reason=tool_calls'  "$r"
assert_not_contains "not the catch-all"          'No response was generated' "$r"

section 'a model that stops after its analysis turn is asked to finish'
# The reported case: gpt120b at effort=high returned 214 characters of reasoning, no
# content, finish_reason=stop. That is one turn short of an answer, not a failed run, so
# the loop asks for the answer instead of reporting "Lower this AI user's Reasoning effort".
r=$(run_job reasoning_then_answer high)
assert_contains     "the answer comes back"      'REPLY=Revenue grew 50% in Q1.' "$r"
assert_contains     "no error"                   'ERROR=(none)'                  "$r"
assert_eq           "it took exactly two calls"  "2" "$(cat "$WIKI_ROOT/calls.txt")"

section '  …and if it still will not answer, its reasoning is handed over'
r=$(run_job reasoning_only high)
assert_contains     "the reasoning is the reply"  'I considered the sales figures' "$r"
assert_contains     "labelled as reasoning only"  'only its reasoning'            "$r"
assert_contains     "and it is not an error"      'ERROR=(none)'                  "$r"
assert_not_contains "not the old failure"         'Lower this AI'                 "$r"
assert_not_contains "not the catch-all"           'No response was generated'     "$r"
# Nudged once, not in a loop: the first call, the nudge, and no more.
assert_eq           "nudged exactly once"        "2" "$(cat "$WIKI_ROOT/calls.txt")"

section 'and a working run is unaffected'
r=$(run_job ok high)
assert_contains     "reply delivered"          'REPLY=Done.'                 "$r"
assert_contains     "no error"                 'ERROR=(none)'                "$r"

printf '\n'
exit $(( ASSERT_FAIL > 0 ))
