#!/usr/bin/env bash
# Astucia Wiki — Copyright (C) 2026 Mads Rotwitt
# Free software under the GNU GPL v3 or later. See LICENSE for the full notice,
# or <https://www.gnu.org/licenses/>. Distributed WITHOUT ANY WARRANTY.
#
# Live progress for a background AI run.
#
# An AI user set to "always run in the background" answers through run_agent_job() and
# shows no modal, so its placeholder in the thread is the only thing the reader can see.
# It used to sit on a static "Queued…" for the whole run; now the runner writes the same
# <chat>.ai-status.<id> file the inline reply path writes.
#
# The steps overwrite one file, so asserting on it at the end would only ever see the
# last one. Instead the LLM stub reports what the status file said at the moment it was
# called — which pins down the ordering: the run must already be past "preparing" and
# recording its tool calls before the second call goes out.

set -uo pipefail
cd "$(dirname "$0")"
. lib/assert.sh
. lib/fixture.sh

fixture_start otp || exit 1
trap fixture_stop EXIT

fixture_space Main
fixture_users '{"users":[
  {"uid":1,"sub":"s1","name":"Admin","role":"admin","auth":"oidc"},
  {"uid":-9,"name":"Bg","role":"editor","is_ai":true,
   "ai_config":{"provider":"openai","model":"stub-1","api_key":"k",
                "always_background":true,"max_tokens":256}}]}'
JAR=$WIKI_ROOT/jar
fixture_login "$JAR" "uid=1&sub=s1&name=Admin&role=admin"

# A thread holding a job-backed placeholder, exactly as queue_agent_job leaves it.
cat > "$WIKI_PAGES/Main/T.chat" <<'EOF'
{"messages":[
 {"id":1,"uid":1,"name":"Admin","text":"#Bg summarise the wiki","timestamp":"2026-01-01T00:00:00+00:00"},
 {"id":2,"uid":-9,"name":"Bg","text":"","timestamp":"2026-01-01T00:00:01+00:00","pending":true,"job_id":"job-1"}
],"nextMessageId":3,"topic":"T"}
EOF

# A stub LLM: one tool call, then a text reply. Each request appends what the status file
# said when it arrived, which is how the ordering gets asserted.
cat > "$WIKI_APP/__test_llm.php" <<'PHP'
<?php
// GENERATED BY tests/ai_job_status.test.sh — never part of a release.
$dir   = dirname(__DIR__);
$nfile = $dir . '/llm-calls.txt';
$n     = (int)@file_get_contents($nfile) + 1;
file_put_contents($nfile, (string)$n);
$status = @file_get_contents($dir . '/pages/Main/T.chat.ai-status.2');
file_put_contents($dir . '/llm-seen.jsonl', 'call' . $n . ' ' . ($status ?: '(no status file)') . "\n", FILE_APPEND);
header('Content-Type: application/json');
if ($n === 1) {
    echo json_encode(['choices' => [['finish_reason' => 'tool_calls', 'message' => [
        'role' => 'assistant', 'content' => null,
        'tool_calls' => [['id' => 'c1', 'type' => 'function',
                          'function' => ['name' => 'wiki_list_pages', 'arguments' => '{}']]],
    ]]]]);
} else {
    echo json_encode(['choices' => [['finish_reason' => 'stop',
                                     'message' => ['role' => 'assistant', 'content' => 'All done.']]]]);
}
PHP

# Drive one job the way the cron runner does, but in-process so the test owns the timing.
run_out=$(cd "$WIKI_APP" && STUB_URL="$WIKI_URL/__test_llm.php" php -r '
require "config.php"; require "indexer.php"; require "space_settings.php";
require "ai_core.php"; require "mailer.php"; require "agent_jobs.php";
$space_dir = rtrim(PAGES_DIR, "/") . "/Main";
$users = json_decode(file_get_contents(WIKI_SYSTEM_DATA . "users.json"), true)["users"];
$ai = null; foreach ($users as $u) if (!empty($u["is_ai"])) $ai = $u;
$ai["ai_config"]["api_url"] = getenv("STUB_URL");
$job = ["id" => "job-1", "prompt" => "summarise the wiki", "space" => "Main",
        "reply_to" => ["chat" => "T.chat", "message_id" => 2],
        "requested_by" => ["uid" => 1, "name" => "Admin"]];
$res = run_agent_job($job, $ai, new PageIndexer($space_dir), $space_dir);
echo "REPLY=", (string)($res["reply"] ?? ""), "\n";
echo "ERROR=", (string)($res["error"] ?? ""), "\n";
' 2>&1)

section 'the run itself'
assert_contains "job completed"              'REPLY=All done.'   "$run_out"
assert_contains "no error"                   'ERROR='            "$run_out"
assert_eq       "the stub was called twice"  "2" "$(cat "$WIKI_ROOT/llm-calls.txt" 2>/dev/null)"

seen=$(cat "$WIKI_ROOT/llm-seen.jsonl" 2>/dev/null)
call1=$(printf '%s' "$seen" | sed -n 's/^call1 //p')
call2=$(printf '%s' "$seen" | sed -n 's/^call2 //p')

section 'progress is written before each call, not after the run'
assert_contains "call 1 saw a status file"      '"step"'              "$call1"
assert_contains "call 1: calling the API"       '"step":"calling_api"' "$call1"
assert_contains "call 1 is the first call"      '"api_calls":1'        "$call1"
assert_contains "call 1 has used no tools yet"  '"tools_used":[]'      "$call1"
assert_contains "call 1 marked as background"   '"background":true'    "$call1"

section 'the tool call in between was recorded'
assert_contains "call 2 is the second call"     '"api_calls":2'                "$call2"
assert_contains "call 2 names the tool used"    '"tools_used":["wiki_list_pages"]' "$call2"

section 'the thread hands the status to the client'
cm=$(get_as "$JAR" 'api.php?action=chat_messages&space=Main&file=T.chat')
assert_contains "chat_messages carries ai_status" '"ai_status"'          "$cm"
assert_contains "  …with the step"                '"step"'               "$cm"
assert_contains "get_ai_status returns it too"    '"step"' \
    "$(get_as "$JAR" 'api.php?action=get_ai_status&space=Main&file=T.chat&id=2')"

section 'the status is transient and never lands in the .chat file'
assert_not_contains "not persisted" 'ai_status' "$(cat "$WIKI_PAGES/Main/T.chat")"
assert_contains     "placeholder still pending" '"pending"' "$(cat "$WIKI_PAGES/Main/T.chat")"

section 'delivering the answer clears the progress file'
assert_file_exists "status file exists before delivery" "$WIKI_PAGES/Main/T.chat.ai-status.2"
(cd "$WIKI_APP" && php -r '
require "config.php"; require "indexer.php"; require "space_settings.php";
require "ai_core.php"; require "mailer.php"; require "agent_jobs.php";
$job = ["reply_to" => ["chat" => "T.chat", "message_id" => 2], "space" => "Main"];
var_export(agent_job_deliver_to_chat($job, "All done.", null));
' > /dev/null 2>&1)
assert_file_missing "status file removed after delivery" "$WIKI_PAGES/Main/T.chat.ai-status.2"
assert_contains     "answer is in the thread" 'All done.' "$(cat "$WIKI_PAGES/Main/T.chat")"
assert_not_contains "no longer pending"       '"pending"' "$(cat "$WIKI_PAGES/Main/T.chat")"

printf '\n'
exit $(( ASSERT_FAIL > 0 ))
