#!/usr/bin/env bash
# Astucia Wiki — Copyright (C) 2026 Mads Rotwitt
# Free software under the GNU GPL v3 or later. See LICENSE for the full notice,
# or <https://www.gnu.org/licenses/>. Distributed WITHOUT ANY WARRANTY.
#
# Asking for attention from outside the window: the tab title counter and the favicon dot.
#
# A browser suite because there is no other place to look. Nothing is written, no endpoint
# is called that a black-box test could watch — the whole feature is two properties of the
# document, and the rule that decides them is whether the window is focused. A module that
# was never wired into script.js, or one that clobbers the title and cannot put it back,
# passes every HTTP assertion there is.
#
# It runs end to end rather than poking the module directly: the page is opened as a real
# logged-in user who has really been mentioned, so the count on the tab is the same number
# the sidebar badge got, through modules/mentions. Two things had to be arranged for that.
#
#  - **A session cookie in Chrome.** The router is started with a non-zero
#    `session.cookie_lifetime`, so PHP's session cookie is persisted in the browser
#    profile rather than dropped when the browser exits — which lets the login happen in
#    one headless run and the measurement in the next, sharing `--user-data-dir`.
#  - **A window that is not focused.** Headless Chrome has exactly one page and it is
#    always focused, so the probe stubs `document.hasFocus()` and dispatches the `blur`
#    the browser would have. That is simulating the user switching apps, which is the
#    one thing this feature is about and the one thing headless cannot do itself.
#
# Results come back on a `data-probe` attribute rather than through `document.title`, the
# way every other browser suite here reports: the title is the thing under test, so
# writing to it would be the probe overwriting its own subject.
#
# Chrome is not a test dependency — no chrome means skip, not fail.

set -uo pipefail
cd "$(dirname "$0")"
. lib/assert.sh
. lib/fixture.sh

CHROME=""
for c in google-chrome chromium chromium-browser; do
    command -v "$c" >/dev/null 2>&1 && { CHROME="$c"; break; }
done
if [ -z "$CHROME" ]; then
    printf '  %s\n' "$(_dim 'skipped — no chrome/chromium on PATH')"
    exit 0
fi

fixture_start otp || exit 1
trap fixture_stop EXIT

fixture_space Main
# `lastLogin` is what "new since you last looked" is measured from when the My Mentions
# panel has never been opened. Without it wiki_mentions_since() is 0 and the count is
# deliberately 0 too — an unmarked account is not shown every mention the wiki ever had
# — so the badge would be empty and this suite would pass by measuring nothing.
fixture_users "{\"users\":[
  {\"uid\":1,\"sub\":\"s1\",\"name\":\"Admin\",\"role\":\"admin\",\"auth\":\"oidc\"},
  {\"uid\":2,\"sub\":\"s2\",\"name\":\"Ed\",\"role\":\"editor\",\"auth\":\"oidc\",\"lastLogin\":$(( $(date +%s) - 3600 ))}]}"

fixture_page 'Main/Start.md'  '# Start'
# The mention Ed will find waiting for him. Written to disk and indexed, rather than
# saved through the API, so the count comes from wiki_scan_mentions() reading content —
# the path that works with or without a realtime hub.
fixture_page 'Main/Brief.md'  '# Brief

@Ed can you take this one'

curl -s "$WIKI_URL/api.php?action=list_spaces" > /dev/null
curl -s "$WIKI_URL/api.php?action=indexfiles&space=Main" > /dev/null

page_id() {
    python3 -c 'import json,sys
ix = json.load(open(sys.argv[1]))
print(next(k for k, v in ix.items() if v.get("path") == sys.argv[2]))' \
        "$WIKI_PAGES/Main/index.json" "$1"
}

cat > "$WIKI_APP/__router.php" <<'R'
<?php
// GENERATED BY tests/attention_ui.test.sh — never part of a release.
$p = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
$f = __DIR__ . $p;
if ($p !== '/' && is_file($f)) {
    $e = pathinfo($f, PATHINFO_EXTENSION);
    if ($e === 'js')  { header('Content-Type: text/javascript'); readfile($f); return true; }
    if ($e === 'css') { header('Content-Type: text/css');        readfile($f); return true; }
    if ($e === 'ico') { header('Content-Type: image/x-icon');    readfile($f); return true; }
    return false;
}
return false;
R

python3 - "$WIKI_APP/index.php" <<'PY'
import io, sys
p = sys.argv[1]
s = io.open(p, encoding='utf-8', newline='').read()
# No backslashes in here: this lives in a Python heredoc inside a shell script, and a
# parse error would take the whole module down silently.
probe = """<script type="module">
import { setUnread } from './modules/attention/index.js';
const sleep = (ms) => new Promise(r => setTimeout(r, ms));
const report = (v) => document.documentElement.setAttribute('data-probe', v);
const icon = () => document.querySelector('link[rel~="icon"]')?.getAttribute('href') || '';
// A data: URL is the badged one; the page's own icon is recognised by name rather than
// by comparing against whatever is in the DOM when the probe runs — by then the module
// has already badged it for the mention that was waiting, so the live value is not a
// baseline.
const iconKind = () => {
  const h = icon();
  if (h.startsWith('data:image')) return 'badged';
  return h.indexOf('favicon.ico') >= 0 ? 'original' : 'other';
};
// Headless has one page and it is always focused, so the window losing focus has to be
// simulated. Both halves are needed: the module asks document.hasFocus() when it renders,
// and it only renders again because of the event.
let focused = true;
Object.defineProperty(document, 'hasFocus', { value: () => focused, configurable: true });
const blur  = () => { focused = false; window.dispatchEvent(new Event('blur')); };
const focus = () => { focused = true;  window.dispatchEvent(new Event('focus')); };

window.addEventListener('error', e => report('fatal=' + e.message));
window.addEventListener('unhandledrejection',
    e => report('fatal=' + (e.reason && e.reason.message || e.reason)));

setTimeout(async () => {
  try {
    let out = '';
    // Focused, so the title is the untouched one even though something is unread.
    const baseTitle = document.title;
    out += ' base=' + baseTitle + '/icon:' + iconKind();

    // What modules/mentions already put there: a real count, from a real mention.
    const badge = document.getElementById('mentions-badge');
    out += ' badge=' + (badge ? badge.textContent : 'none');
    // Focused, so the title stays clean even though something is unread: the sidebar
    // badge is on screen and saying it twice in the browser chrome is noise.
    out += ' focused=' + (document.title === baseTitle ? 'clean' : document.title);

    // Away from the window. This is the whole feature.
    blur();
    await sleep(100);
    out += ' blurred=' + document.title;
    // The dot does not wait for the window to be unfocused: it is the state of the tab,
    // and the only marker left on a pinned one.
    await sleep(400);
    out += ' dot=' + iconKind();

    // Back to the window: the title is handed back exactly, not approximately.
    focus();
    await sleep(100);
    out += ' refocused=' + (document.title === baseTitle ? 'restored' : document.title);

    // Reading them clears both surfaces. Driven through setUnread rather than by
    // clicking the panel, because what is being measured is the module's own contract:
    // 0 means put everything back.
    setUnread(0);
    blur();
    await sleep(400);
    out += ' cleared=' + (document.title === baseTitle ? 'restored' : document.title)
         + '/icon:' + iconKind();

    // And it comes back. A one-shot badge that cannot be raised twice would pass
    // everything above.
    setUnread(7);
    await sleep(400);
    out += ' again=' + document.title + '/icon:' + iconKind();
    report(out);
  } catch (e) {
    report('fatal=' + (e && e.message || e));
  }
}, 4000);
</script>
</body>"""
assert s.count('</body>') == 1
io.open(p, 'w', encoding='utf-8', newline='').write(s.replace('</body>', probe))
PY

# session.cookie_lifetime: PHP's default of 0 makes the session cookie a per-browser-run
# one, which is dropped between the login invocation and the measuring invocation below.
PORT="${WIKI_URL##*:}"
kill "$WIKI_PID" 2>/dev/null; wait "$WIKI_PID" 2>/dev/null
( cd "$WIKI_APP" && exec php -d "session.save_path=$WIKI_ROOT/sessions" \
    -d "session.cookie_lifetime=3600" \
    -S "127.0.0.1:$PORT" __router.php ) > "$WIKI_ROOT/router.log" 2>&1 &
WIKI_PID=$!
i=0
until curl -sf --max-time 2 "$WIKI_URL/api.php?action=ping" > /dev/null 2>&1; do
    i=$((i + 1)); [ $i -gt 100 ] && { echo "router did not start" >&2; exit 1; }
    sleep 0.1
done

PROFILE="$WIKI_ROOT/chrome-profile"
chrome() {
    "$CHROME" --headless=new --disable-gpu --no-sandbox --window-size=1280,900 \
        --user-data-dir="$PROFILE" --virtual-time-budget=30000 \
        --dump-dom "$1" 2>/dev/null
}

# Log in as Ed, in a run of its own: the cookie lands in the profile and the next run
# picks it up.
chrome "$WIKI_URL/__test_login.php?uid=2&sub=s2&name=Ed&role=editor" > /dev/null
chrome "$WIKI_URL/index.php?pageid=$(page_id 'Start.md')&space=Main" > "$WIKI_ROOT/dom.html"

PROBE=$(grep -o 'data-probe="[^"]*"' "$WIKI_ROOT/dom.html" \
        | python3 -c 'import html,sys; sys.stdout.write(html.unescape(sys.stdin.read()))' || true)
[ -n "$PROBE" ] || _fail "the page never reported (probe did not run)" "see $WIKI_ROOT/dom.html"

assert_not_contains "the probe ran without throwing" 'fatal' "$PROBE"

section 'the session and the mention are really there'
# The positive control for everything else: without a logged-in user who has been
# mentioned, the count is 0 and every assertion below would pass by doing nothing.
assert_contains "the page is the wiki"          'base=Astucia'  "$PROBE"
assert_contains "Ed has an unread mention"      'badge=1'       "$PROBE"
# The module has already acted on that count by the time the probe runs, which is itself
# the end-to-end assertion: nothing in this probe put it there.
assert_contains "  and the favicon already says so" 'base=Astucia Wiki/icon:badged' "$PROBE"

section 'while the window has focus the title is left alone'
assert_contains "no counter in the chrome"      'focused=clean' "$PROBE"

section 'away from the window, the tab says so'
assert_contains "the count is on the title"     'blurred=(1) '  "$PROBE"
assert_contains "  and the favicon carries a dot" 'dot=badged'  "$PROBE"

section 'and it is handed back exactly'
# Not "approximately": a module that rebuilds the title from a constant would drift from
# APP_TITLE the moment somebody configured one.
assert_contains "coming back restores the title" 'refocused=restored' "$PROBE"
assert_contains "reading it clears the title"    'cleared=restored'   "$PROBE"
assert_contains "  and the favicon"              'cleared=restored/icon:original' "$PROBE"

section 'and it can be raised again'
assert_contains "a later mention re-badges"      'again=(7) '   "$PROBE"
assert_contains "  including the favicon"        'again=(7) Astucia Wiki/icon:badged' "$PROBE"

printf '\n'
exit $(( ASSERT_FAIL > 0 ))
