#!/usr/bin/env bash
# Astucia Wiki — Copyright (C) 2026 Mads Rotwitt
# Free software under the GNU GPL v3 or later. See LICENSE for the full notice,
# or <https://www.gnu.org/licenses/>. Distributed WITHOUT ANY WARRANTY.
#
# Copy buttons on rendered code blocks, in a real browser.
#
# This feature has no HTTP surface at all: the server sends the same Markdown it always
# did and every button is built from the rendered DOM. So the one way it can fail — no
# button, a button in the wrong place, or a button that copies marked's HTML-escaped text
# instead of what the author typed — is invisible to every other suite here. Same reason
# tests/frontmatter_ui.test.sh exists, and it shares that file's mechanics: a two-line
# router (php -S sends no Content-Type for .js, which blocks ES modules), instrumentation
# that only clicks real controls, and a report read out of document.title.
#
# Chrome is not a test dependency — no chrome means skip, not fail.

set -uo pipefail
cd "$(dirname "$0")"
. lib/assert.sh
. lib/fixture.sh

CHROME=""
for c in google-chrome chromium chromium-browser; do
    command -v "$c" >/dev/null 2>&1 && { CHROME="$c"; break; }
done
if [ -z "$CHROME" ]; then
    printf '  %s\n' "$(_dim 'skipped — no chrome/chromium on PATH')"
    exit 0
fi

fixture_start off || exit 1
trap fixture_stop EXIT

fixture_space Main

# Three fences and one inline span. The first fence carries the characters marked escapes
# (`&`, `<`, `>`, `"`): reading it back with innerHTML instead of textContent hands the
# clipboard `&amp;lt;` rather than what the author wrote, which is the trap the mermaid
# renderer documents and this pass inherits.
printf '%s' '# Snippets

Run `php -S localhost:8000` to serve it.

```bash
grep -n "a & b" *.md | head -3
curl -s "https://example.com/a/very/long/unbreakable/path/that/has/no/spaces/in/it/at/all/and/therefore/wraps/exactly/at/the/column/edge?x=1&y=2"
echo "<div>done</div>"
```

Then:

```json
{"ok": true}
```

```mermaid
graph TD
  A[Start] --> B[Stop]
```
' > "$WIKI_PAGES/Main/Snippets.md"

fixture_page 'Main/Prose.md' '# Prose

No code at all, just a sentence.'

curl -s "$WIKI_URL/api.php?action=list_spaces" > /dev/null
curl -s "$WIKI_URL/api.php?action=indexfiles&space=Main" > /dev/null

page_id() {
    python3 -c 'import json,sys
ix = json.load(open(sys.argv[1]))
print(next(k for k, v in ix.items() if v.get("path") == sys.argv[2]))' \
        "$WIKI_PAGES/${2:-Main}/index.json" "$1"
}

cat > "$WIKI_APP/__router.php" <<'R'
<?php
// GENERATED BY tests/code_copy_ui.test.sh — never part of a release.
$p = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
$f = __DIR__ . $p;
if ($p !== '/' && is_file($f)) {
    $e = pathinfo($f, PATHINFO_EXTENSION);
    if ($e === 'js')  { header('Content-Type: text/javascript'); readfile($f); return true; }
    if ($e === 'css') { header('Content-Type: text/css');        readfile($f); return true; }
    return false;
}
return false;
R

python3 - "$WIKI_APP/index.php" <<'PY'
import io, sys
p = sys.argv[1]
s = io.open(p, encoding='utf-8', newline='').read()
# ?probe=<what> selects the action; the report goes in document.title, which --dump-dom
# returns without needing a DevTools connection. Note the escaping: this text lives in a
# Python heredoc inside a shell script, so a backslash meant for JavaScript is doubled.
probe = """<script type="module">
const geom = () => {
  const btns  = [...document.querySelectorAll('#viewer-content .code-copy-btn')];
  const wraps = [...document.querySelectorAll('#viewer-content .code-block')];
  const pres  = [...document.querySelectorAll('#viewer-content pre')];
  const b = btns[0], w = wraps[0];
  // Inside its own block and hard against its top-right corner, measured rather than
  // inferred from the stylesheet — source order and box-sizing have both silently beaten
  // a rule in this sheet before.
  let corner = 'none', inside = 'no', clear = -1;
  if (b && w) {
    const br = b.getBoundingClientRect(), wr = w.getBoundingClientRect();
    corner = Math.round(wr.right - br.right) + '/' + Math.round(br.top - wr.top);
    inside = (br.top >= wr.top - 1 && br.right <= wr.right + 1 && br.bottom <= wr.bottom + 1)
             ? 'yes' : 'NO';
    // The gap between the longest wrapped line and the button's left edge: the block
    // reserves room for it, so a first line running the width of the column wraps before
    // the button rather than under it.
    const pre = w.querySelector('pre');
    const r = document.createRange();
    r.selectNodeContents(pre.querySelector('code'));
    clear = Math.round(br.left - r.getBoundingClientRect().right);
  }
  // Opacity is transitioned, and getComputedStyle reports the value mid-animation — so
  // the reveal has to be measured with the transition suppressed, or every reading is the
  // starting one.
  let atRest = '-', onTouch = '-';
  if (b) {
    b.style.transition = 'none';
    atRest = getComputedStyle(b).opacity;
    document.body.classList.add('mobile');
    onTouch = getComputedStyle(b).opacity;
    document.body.classList.remove('mobile');
    b.style.transition = '';
  }
  return ' fences=' + pres.length
    + ' buttons=' + btns.length
    + ' wrappers=' + wraps.length
    + ' insidePre=' + document.querySelectorAll('#viewer-content pre .code-copy-btn').length
    + ' wrapsAPre=' + wraps.filter(w => w.querySelector(':scope > pre')).length
    + ' corner=' + corner
    + ' inside=' + inside
    + ' clear=' + clear
    + ' atRest=' + atRest
    + ' onTouch=' + onTouch
    // A button inside the block's own text would join it — both for `code.textContent`
    // and for a reader dragging across the block, which is what this replaces.
    + ' blockText=' + JSON.stringify(pres.map(p => p.textContent).join(' ').includes('Copy'))
    + ' label=' + JSON.stringify(b ? (b.title || '') : '');
};
window.addEventListener('error', e => { document.title = 'PROBE fatal=' + e.message; });
window.addEventListener('unhandledrejection', e => {
    document.title = 'PROBE fatalRejection=' + (e.reason && e.reason.message || e.reason); });
setTimeout(() => {
  const probe = new URLSearchParams(location.search).get('probe');
  if (probe === 'copy') {
    // The clipboard is stubbed rather than read back: a headless browser grants no
    // clipboard permission, and what this has to prove is *which bytes* the button hands
    // over, not that the platform stored them.
    let captured = null;
    Object.defineProperty(navigator, 'clipboard', {
      configurable: true,
      value: { writeText: (t) => { captured = t; return Promise.resolve(); } },
    });
    const btn = document.querySelector('#viewer-content .code-copy-btn');
    btn.click();
    setTimeout(() => {
      document.title = 'PROBE copied=' + JSON.stringify(captured)
        + ' marked=' + (btn.classList.contains('code-copy-done') ? 'yes' : 'NO')
        + ' feedback=' + JSON.stringify(btn.title || '');
    }, 400);
    return;
  }
  if (probe === 'refresh') {
    // Re-render the page in place, the way the on-disk watcher does. The wrapper is itself
    // a mutation of the viewer, so the pass that adds it lands back in the observer — a
    // block must not collect a second button on every pass.
    // Tagged first, so the report can say the buttons are *new* ones. Without that,
    // "still two buttons" would also be what a refresh that never happened looks like.
    document.querySelectorAll('#viewer-content .code-copy-btn')
      .forEach(b => { b.dataset.stale = '1'; });
    import('./modules/page_view/index.js')
      .then(m => m.refreshPageContent())
      .then(() => new Promise(r => setTimeout(r, 800)))
      .then(() => { document.title = 'PROBE'
        + ' stale=' + document.querySelectorAll('#viewer-content .code-copy-btn[data-stale]').length
        + geom(); });
    return;
  }
  document.title = 'PROBE' + geom();
}, 5000);
</script>
</body>"""
assert s.count('</body>') == 1
io.open(p, 'w', encoding='utf-8', newline='').write(s.replace('</body>', probe))
PY

# Restart the fixture's server behind the router.
PORT="${WIKI_URL##*:}"
kill "$WIKI_PID" 2>/dev/null; wait "$WIKI_PID" 2>/dev/null
( cd "$WIKI_APP" && exec php -d "session.save_path=$WIKI_ROOT/sessions" \
    -S "127.0.0.1:$PORT" __router.php ) > "$WIKI_ROOT/router.log" 2>&1 &
WIKI_PID=$!
i=0
until curl -sf --max-time 2 "$WIKI_URL/api.php?action=ping" > /dev/null 2>&1; do
    i=$((i + 1)); [ $i -gt 100 ] && { echo "router did not start" >&2; exit 1; }
    sleep 0.1
done

# load <page> [probe] → DOM in $DOM, the probe line in $PROBE
load() {
    local q="pageid=$(page_id "$1")&space=Main"
    [ -n "${2:-}" ] && q="$q&probe=$2"
    "$CHROME" --headless=new --disable-gpu --no-sandbox --window-size=1280,900 \
        --virtual-time-budget=25000 \
        --dump-dom "$WIKI_URL/index.php?$q" > "$WIKI_ROOT/dom.html" 2>/dev/null
    DOM=$(cat "$WIKI_ROOT/dom.html")
    # --dump-dom serialises the title, so anything the probe reports has been HTML-escaped
    # on the way out. Decoding it back matters here more than in the other browser suite:
    # the whole point of one assertion is that the clipboard carries `&` and `<` as the
    # author typed them, and a raw title says `&amp;` either way.
    PROBE=$(printf '%s' "$DOM" | grep -o '<title>PROBE[^<]*</title>' \
            | python3 -c 'import html,sys; sys.stdout.write(html.unescape(sys.stdin.read()))' || true)
    [ -n "$PROBE" ] || _fail "the page never reported (probe did not run)" "page $1"
}
field() { printf '%s' "$PROBE" | sed -n "s/.* $1=\([^ <]*\).*/\1/p"; }

section 'every fenced block on a Markdown page gets a button'
load Snippets.md
# Three fences, one of them mermaid: that <pre> is replaced by an SVG moments later, so a
# button on it would be left floating beside a diagram.
assert_eq "one button per code block, mermaid excluded" '2' "$(field buttons)"
assert_eq "  each in its own wrapper"                   '2' "$(field wrappers)"
assert_eq "  and each wrapper holds the block"          '2' "$(field wrapsAPre)"
assert_eq "no button is inside a <pre>"                 '0' "$(field insidePre)"
assert_contains "so the block's own text stays clean" 'blockText=false' "$PROBE"
assert_contains "the button is labelled"              'label="Copy code"' "$PROBE"

section 'and it sits in the top right corner of the block'
assert_contains "inside the block's box" 'inside=yes' "$PROBE"
printf '  %s\n' "$(_dim "measured: inset $(field corner) (right/top), text clearance $(field clear)px")"
assert_eq "  inset from the corner" '8/8' "$(field corner)"
# Room is reserved for the button, so the widest wrapped line stops short of it.
clear=$(field clear)
if [ "${clear:-0}" -ge 0 ] 2>/dev/null; then _pass "  no line runs under it"
else _fail "  no line runs under it" "text overlaps the button by ${clear#-}px"; fi

section 'it stays out of the way until it is wanted'
assert_eq "hidden at rest"                  '0' "$(field atRest)"
assert_eq "shown where there is no hover"   '1' "$(field onTouch)"

section 'a page with no code block grows nothing'
load Prose.md
assert_eq "no wrappers" '0' "$(field wrappers)"
assert_eq "no buttons"  '0' "$(field buttons)"

section 'the button copies what the author typed'
load Snippets.md copy
# marked HTML-escapes a fence body, so reading it back with innerHTML yields `&amp;` and
# `&lt;` — the clipboard has to carry the source bytes.
assert_contains "the ampersand survives"    'a & b'                "$PROBE"
assert_contains "the angle brackets too"    '<div>done</div>'      "$PROBE"
assert_contains "both lines of the block"   'echo'                 "$PROBE"
assert_not_contains "nothing is HTML-escaped" '&amp;'              "$PROBE"
assert_contains "the button confirms it"    'marked=yes'           "$PROBE"
assert_contains "  and says so"             'feedback="Copied"'    "$PROBE"

section 'an in-place re-render does not stack buttons'
load Snippets.md refresh
assert_eq "the blocks really were re-rendered" '0' "$(field stale)"
assert_eq "still one button per block"        '2' "$(field buttons)"
assert_eq "  and one wrapper each"            '2' "$(field wrappers)"
