#!/usr/bin/env bash
# Astucia Wiki — Copyright (C) 2026 Mads Rotwitt
# Free software under the GNU GPL v3 or later. See LICENSE for the full notice,
# or <https://www.gnu.org/licenses/>. Distributed WITHOUT ANY WARRANTY.
#
# The editor's Alt shortcuts, and the modifiers they must keep their hands off.
#
# `Alt+B` inserting bold markers is easy to get right. The failure this exists for is the
# other half: **AltGr reports as Ctrl+Alt on Windows and Linux**, so a handler gated on
# `e.altKey` alone answers a perfectly ordinary keystroke — the one a German, Polish or
# Brazilian layout uses to type a character — by swallowing it with preventDefault() and
# inserting a heading instead. macOS is the mirror image: Cmd+Alt+I opens the browser's
# dev tools, and that was answered with a pair of italic markers.
#
# Nothing black-box can see any of this: the whole behaviour is which keystrokes a
# document-level listener claims, and the evidence is a `defaultPrevented` flag. So this
# drives a real browser, dispatches each combination, and — exactly as the browser does —
# performs the default text insertion only when nothing cancelled the event.
#
# Every denial is paired with a positive control, because a handler that has stopped
# firing at all would pass every "it did not intercept" assertion on its own.
#
# Chrome is not a test dependency — no chrome means skip, not fail.

set -uo pipefail
cd "$(dirname "$0")"
. lib/assert.sh
. lib/fixture.sh

CHROME=""
for c in google-chrome chromium chromium-browser; do
    command -v "$c" >/dev/null 2>&1 && { CHROME="$c"; break; }
done
if [ -z "$CHROME" ]; then
    printf '  %s\n' "$(_dim 'skipped — no chrome/chromium on PATH')"
    exit 0
fi

fixture_start off || exit 1
trap fixture_stop EXIT

fixture_space Main
fixture_page 'Main/Notes.md' '# Notes'

curl -s "$WIKI_URL/api.php?action=list_spaces" > /dev/null
curl -s "$WIKI_URL/api.php?action=indexfiles&space=Main" > /dev/null

page_id() {
    python3 -c 'import json,sys
ix = json.load(open(sys.argv[1]))
print(next(k for k, v in ix.items() if v.get("path") == sys.argv[2]))' \
        "$WIKI_PAGES/${2:-Main}/index.json" "$1"
}

cat > "$WIKI_APP/__router.php" <<'R'
<?php
// GENERATED BY tests/editor_hotkeys_ui.test.sh — never part of a release.
$p = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
$f = __DIR__ . $p;
if ($p !== '/' && is_file($f)) {
    $e = pathinfo($f, PATHINFO_EXTENSION);
    if ($e === 'js')  { header('Content-Type: text/javascript'); readfile($f); return true; }
    if ($e === 'css') { header('Content-Type: text/css');        readfile($f); return true; }
    return false;
}
return false;
R

python3 - "$WIKI_APP/index.php" <<'PY'
import io, sys
p = sys.argv[1]
s = io.open(p, encoding='utf-8', newline='').read()
# The report goes in document.title, which --dump-dom returns without needing a DevTools
# connection. No backslashes in here: this lives in a Python heredoc inside a shell
# script, and a parse error would take the whole module down silently.
probe = """<script type="module">
const sleep = (ms) => new Promise(r => setTimeout(r, ms));

// One keystroke, as the browser performs it: dispatch a cancelable keydown, and insert
// the character only if nothing called preventDefault().
const press = (ta, key, mods, text) => {
  const ev = new KeyboardEvent('keydown', Object.assign(
    { key, bubbles: true, cancelable: true }, mods));
  ta.dispatchEvent(ev);
  if (!ev.defaultPrevented && text !== null) {
    const s = ta.selectionStart, e = ta.selectionEnd;
    ta.setRangeText(text, s, e, 'end');
    ta.dispatchEvent(new Event('input', { bubbles: true }));
  }
  return ev.defaultPrevented;
};

// What the editor holds after one keystroke on an empty document.
const after = (ta, key, mods, text) => {
  ta.value = '';
  ta.focus();
  ta.setSelectionRange(0, 0);
  press(ta, key, mods, text);
  return ta.value;
};

window.addEventListener('error', e => { document.title = 'PROBE fatal=' + e.message; });
window.addEventListener('unhandledrejection', e => {
    document.title = 'PROBE fatalRejection=' + (e.reason && e.reason.message || e.reason); });

setTimeout(async () => {
  try {
    document.getElementById('edit-btn').click();
    await sleep(700);
    const ta = document.getElementById('editor-container');

    const ALTGR = { ctrlKey: true, altKey: true };   // Windows and Linux report AltGr so
    const CMDALT = { metaKey: true, altKey: true };  // macOS: Cmd+Alt opens the dev tools
    const ALT = { altKey: true };

    document.title = 'PROBE'
      // The character the layout puts under that key must reach the document.
      + ' altgr3=' + JSON.stringify(after(ta, '3', ALTGR, '3'))
      + ' altgrB=' + JSON.stringify(after(ta, 'b', ALTGR, 'b'))
      + ' altgrT=' + JSON.stringify(after(ta, 't', ALTGR, 't'))
      + ' cmdAltI=' + JSON.stringify(after(ta, 'i', CMDALT, 'i'))
      // Positive controls: the shortcuts themselves still work on bare Alt.
      + ' alt2=' + JSON.stringify(after(ta, '2', ALT, null))
      + ' altB=' + JSON.stringify(after(ta, 'b', ALT, null))
      + ' altN=' + JSON.stringify(after(ta, 'n', ALT, null))
      // And the typing this all started from is untouched.
      + ' hashes=' + JSON.stringify((() => {
          ta.value = ''; ta.focus(); ta.setSelectionRange(0, 0);
          press(ta, '#', { shiftKey: true }, '#');
          press(ta, '#', { shiftKey: true }, '#');
          press(ta, ' ', {}, ' ');
          return ta.value;
        })())
      // Tab indents rather than moving the focus. Built from char codes because this
      // lives in a Python heredoc inside a shell script and a stray backslash would
      // take the whole module down with a parse error.
      + (() => {
          const TAB = String.fromCharCode(9), LF = String.fromCharCode(10);
          const set = (v, a, b) => { ta.value = v; ta.focus();
                                     ta.setSelectionRange(a, b === undefined ? a : b); };
          const shot = (p) => p + '|' + JSON.stringify(ta.value);
          let out = '';

          // What the tab the key inserts is actually worth on screen. CSS defaults
          // tab-size to 8, a terminal convention that makes one level of list nesting
          // look like three.
          out += ' tabSize=' + JSON.stringify(getComputedStyle(ta).tabSize);

          set('');
          out += ' tabCaret=' + shot(press(ta, 'Tab', {}, null));

          set(TAB + 'a', 2);
          out += ' shiftTab=' + shot(press(ta, 'Tab', { shiftKey: true }, null));

          // Three lines, the middle one empty: a blank line must stay blank rather
          // than collecting trailing whitespace nothing renders.
          set('- a' + LF + LF + '- b', 0, 8);
          out += ' block=' + shot(press(ta, 'Tab', {}, null));
          out += ' blockOut=' + shot(press(ta, 'Tab', { shiftKey: true }, null));

          // Shift+Tab with nothing to give back is still the editor's key.
          set('a', 1);
          out += ' outdentNoop=' + shot(press(ta, 'Tab', { shiftKey: true }, null));

          // The escape hatch: Esc hands the next Tab back to the focus order, and the
          // one after that indents again.
          set('x', 1);
          press(ta, 'Escape', {}, null);
          out += ' escThenTab=' + press(ta, 'Tab', {}, null);
          out += ' tabAfterThat=' + press(ta, 'Tab', {}, null);

          // Esc followed by Shift+Tab still escapes: holding the modifier must not
          // cancel the hatch before the Tab arrives.
          set('x', 1);
          press(ta, 'Escape', {}, null);
          press(ta, 'Shift', { shiftKey: true }, null);
          out += ' escThenShiftTab=' + press(ta, 'Tab', { shiftKey: true }, null);

          // Esc then any ordinary key cancels it again.
          set('x', 1);
          press(ta, 'Escape', {}, null);
          press(ta, 'y', {}, 'y');
          out += ' escThenTyping=' + press(ta, 'Tab', {}, null);

          // Undo has to survive an indent. setRangeText() would have dropped the
          // browser's native undo stack, so this is what says insertText was used.
          set('a', 1);
          press(ta, 'Tab', {}, null);
          const indented = ta.value;
          document.execCommand('undo');
          out += ' undo=' + JSON.stringify(indented) + '>' + JSON.stringify(ta.value);

          // The window manager's combinations are never ours.
          set('x', 1);
          out += ' ctrlTab=' + press(ta, 'Tab', { ctrlKey: true }, null);
          out += ' altTab=' + press(ta, 'Tab', { altKey: true }, null);

          // A textarea that is not the editor keeps Tab as focus movement — a chat
          // composer is one, and this is what stops the claim being a blanket one.
          const plain = document.createElement('textarea');
          document.body.appendChild(plain);
          plain.focus();
          out += ' plainTab=' + press(plain, 'Tab', {}, null) +
                 '|' + JSON.stringify(plain.value);
          return out;
        })();
  } catch (e) {
    document.title = 'PROBE fatal=' + (e && e.message || e);
  }
}, 5000);
</script>
</body>"""
assert s.count('</body>') == 1
io.open(p, 'w', encoding='utf-8', newline='').write(s.replace('</body>', probe))
PY

PORT="${WIKI_URL##*:}"
kill "$WIKI_PID" 2>/dev/null; wait "$WIKI_PID" 2>/dev/null
( cd "$WIKI_APP" && exec php -d "session.save_path=$WIKI_ROOT/sessions" \
    -S "127.0.0.1:$PORT" __router.php ) > "$WIKI_ROOT/router.log" 2>&1 &
WIKI_PID=$!
i=0
until curl -sf --max-time 2 "$WIKI_URL/api.php?action=ping" > /dev/null 2>&1; do
    i=$((i + 1)); [ $i -gt 100 ] && { echo "router did not start" >&2; exit 1; }
    sleep 0.1
done

load() {
    "$CHROME" --headless=new --disable-gpu --no-sandbox --window-size=1280,900 \
        --virtual-time-budget=25000 \
        --dump-dom "$WIKI_URL/index.php?pageid=$(page_id "$1")&space=Main&probe=keys" \
        > "$WIKI_ROOT/dom.html" 2>/dev/null
    PROBE=$(grep -o '<title>PROBE[^<]*</title>' "$WIKI_ROOT/dom.html" \
            | python3 -c 'import html,sys; sys.stdout.write(html.unescape(sys.stdin.read()))' || true)
    [ -n "$PROBE" ] || _fail "the page never reported (probe did not run)" "page $1"
}

load Notes.md
assert_not_contains "the probe ran without throwing" 'fatal' "$PROBE"

section 'AltGr is not Alt — the character reaches the page'
# Ctrl+Alt is what AltGr sends, and these four keys are the ones the editor claims.
assert_contains "AltGr+3 types its character"  'altgr3="3"' "$PROBE"
assert_contains "AltGr+B types its character"  'altgrB="b"' "$PROBE"
assert_contains "AltGr+T types its character"  'altgrT="t"' "$PROBE"

section 'nor is Cmd+Alt, which opens the browser dev tools'
assert_contains "Cmd+Alt+I is left alone" 'cmdAltI="i"' "$PROBE"

section 'while the shortcuts themselves still work'
assert_contains "Alt+2 inserts a heading"     'alt2="## "'      "$PROBE"
assert_contains "Alt+B inserts bold markers"  'altB="****"'     "$PROBE"
assert_contains "Alt+N inserts the filename placeholder" 'altN="{filename}"' "$PROBE"

section 'and ordinary typing is untouched'
assert_contains "Shift+3 twice, then a space" 'hashes="## "' "$PROBE"

section 'Tab indents instead of moving the focus'
# A real tab: one press is one nesting level, and both renderers (marked in the browser,
# Parsedown in the static export) read a leading tab as exactly that.
assert_contains "Tab is claimed, and inserts a tab"  'tabCaret=true|"\t"'  "$PROBE"
assert_contains "Shift+Tab takes it back off"        'shiftTab=true|"a"'    "$PROBE"
# The reason indentLines() goes through execCommand('insertText') rather than the
# setRangeText() every other helper in editor.js uses: a scripted mutation drops the
# browser's native undo stack, and an editor where Ctrl+Z stops working after each
# indent is worse than no Tab key at all. This is what says the native path was taken.
assert_contains "and Ctrl+Z still undoes it"         'undo="a\t">"a"'      "$PROBE"
# --tab-size in styles.css, shared by the editor, the rendered page, a chat bubble and
# the static export, so a code block never changes width between typing it and reading it.
assert_contains "one tab is four columns, not the CSS default eight" 'tabSize="4"' "$PROBE"

section 'a multi-line selection moves as a block'
assert_contains "every line gains one level"  'block=true|"\t- a\n\n\t- b"' "$PROBE"
# Indenting a blank line writes trailing whitespace into the file and renders as nothing.
assert_not_contains "and the blank line stays blank" 'block=true|"\t- a\n\t\n' "$PROBE"
assert_contains "Shift+Tab gives the level back"     'blockOut=true|"- a\n\n- b"' "$PROBE"
assert_contains "Shift+Tab at column zero is a no-op, not a focus jump" \
                'outdentNoop=true|"a"' "$PROBE"

section 'Esc is the way out of the keyboard trap'
# Swallowing Tab leaves a textarea with no keyboard exit, which is what WCAG 2.1.2 is
# about. Esc hands the next Tab back; the one after that is the editor's again.
assert_contains "Esc then Tab moves the focus"      'escThenTab=false'      "$PROBE"
assert_contains "and the next Tab indents again"    'tabAfterThat=true'     "$PROBE"
assert_contains "Esc then Shift+Tab escapes too"    'escThenShiftTab=false' "$PROBE"
assert_contains "typing after Esc cancels the hatch" 'escThenTyping=true'   "$PROBE"

section 'and the claim is narrow'
assert_contains "Ctrl+Tab is left to the browser"  'ctrlTab=false'  "$PROBE"
assert_contains "Alt+Tab is left to the window manager" 'altTab=false' "$PROBE"
assert_contains "a textarea that is not the editor still tabs away" 'plainTab=false|""' "$PROBE"

printf '\n'
exit $(( ASSERT_FAIL > 0 ))
