#!/usr/bin/env bash
# Astucia Wiki — Copyright (C) 2026 Mads Rotwitt
# Free software under the GNU GPL v3 or later. See LICENSE for the full notice,
# or <https://www.gnu.org/licenses/>. Distributed WITHOUT ANY WARRANTY.
#
# Links that leave the wiki open in a new tab; links that do not, do not.
#
# A browser suite because the whole feature is an attribute on a node that only exists
# after marked has run in a browser. The server sends Markdown and never sees the anchor,
# so there is nothing black-box to assert against.
#
# The negative cases are the point. "Add target=_blank to links" is trivial to implement
# and easy to over-apply: a `?pageid=` link, a wikilink, an attachment and an in-page
# anchor are all navigation *within* the document and must stay in this tab, and a
# `mailto:` has no tab to open. Each of those is asserted alongside the positive, or a
# blanket implementation would pass on the strength of the external link alone.
#
# Both surfaces are covered because they are reached differently: a page goes through the
# MutationObserver in modules/page_view, while a chat bubble is not under #viewer-content
# at all and that observer never sees it.
#
# Chrome is not a test dependency — no chrome means skip, not fail.

set -uo pipefail
cd "$(dirname "$0")"
. lib/assert.sh
. lib/fixture.sh

CHROME=""
for c in google-chrome chromium chromium-browser; do
    command -v "$c" >/dev/null 2>&1 && { CHROME="$c"; break; }
done
if [ -z "$CHROME" ]; then
    printf '  %s\n' "$(_dim 'skipped — no chrome/chromium on PATH')"
    exit 0
fi

fixture_start off || exit 1
trap fixture_stop EXIT

fixture_space Main
fixture_page 'Main/Links.md' '# Links

- [outside](https://example.com/docs)
- [outside-insecure](http://example.org/x)
- [another page](?pageid=123)
- [an attachment](getfile.php?path=Main/a.png&space=Main)
- [relative](Notes/Other.md)
- [in-page](#links)
- [write to us](mailto:someone@example.com)
- [already decided](https://example.net/ "t"){#x}

<a href="https://example.com/explicit" target="_self">left alone</a>'

# An AI user, because a human message is escaped rather than rendered — only an AI
# bubble goes through marked, and therefore only an AI bubble can contain a link.
fixture_users '{"users":[
  {"uid":9,"sub":"ai9","name":"Bot","role":"editor","auth":"oidc","is_ai":true,
   "ai_config":{"provider":"openai","model":"gpt-4o"}}]}'
printf '{"topic":"Talk","nextMessageId":2,"messages":[{"id":1,"uid":9,"name":"Bot","text":"See [the docs](https://example.com/guide) and [this page](?pageid=42).","timestamp":"%s"}]}' \
    "$(date '+%Y-%m-%d %H:%M:%S')" > "$WIKI_PAGES/Main/Talk.chat"

curl -s "$WIKI_URL/api.php?action=list_spaces" > /dev/null
curl -s "$WIKI_URL/api.php?action=indexfiles&space=Main" > /dev/null

page_id() {
    python3 -c 'import json,sys
ix = json.load(open(sys.argv[1]))
print(next(k for k, v in ix.items() if v.get("path") == sys.argv[2]))' \
        "$WIKI_PAGES/Main/index.json" "$1"
}

cat > "$WIKI_APP/__router.php" <<'R'
<?php
// GENERATED BY tests/external_links_ui.test.sh — never part of a release.
$p = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
$f = __DIR__ . $p;
if ($p !== '/' && is_file($f)) {
    $e = pathinfo($f, PATHINFO_EXTENSION);
    if ($e === 'js')  { header('Content-Type: text/javascript'); readfile($f); return true; }
    if ($e === 'css') { header('Content-Type: text/css');        readfile($f); return true; }
    if ($e === 'ico') { header('Content-Type: image/x-icon');    readfile($f); return true; }
    return false;
}
return false;
R

python3 - "$WIKI_APP/index.php" <<'PY'
import io, sys
p = sys.argv[1]
s = io.open(p, encoding='utf-8', newline='').read()
# No backslashes in here: this lives in a Python heredoc inside a shell script, and a
# parse error would take the whole module down silently.
probe = """<script type="module">
const sleep = (ms) => new Promise(r => setTimeout(r, ms));
const report = (v) => document.documentElement.setAttribute('data-probe', v);
// One anchor, described: does it open elsewhere, and does it carry the rel that makes
// that safe. Matched on a distinctive part of the href so the report reads as a list of
// decisions rather than of positions.
const link = (root, needle) => {
  const a = Array.from(root.querySelectorAll('a[href]'))
      .find(el => (el.getAttribute('href') || '').indexOf(needle) >= 0);
  if (!a) return 'absent';
  const target = a.getAttribute('target') || 'same';
  const rel = (a.getAttribute('rel') || '');
  return target + (target === '_blank'
      ? (rel.indexOf('noopener') >= 0 && rel.indexOf('noreferrer') >= 0 ? '+safe' : '+bare')
      : '');
};

window.addEventListener('error', e => report('fatal=' + e.message));
window.addEventListener('unhandledrejection',
    e => report('fatal=' + (e.reason && e.reason.message || e.reason)));

setTimeout(async () => {
  try {
    let out = '';
    const mode = new URLSearchParams(location.search).get('mode');

    if (mode === 'page') {
      const v = document.getElementById('viewer-content');
      out += ' rendered=' + (v.querySelectorAll('a[href]').length ? 'yes' : 'no');
      out += ' ext=' + link(v, 'example.com/docs');
      out += ' extplain=' + link(v, 'example.org/x');
      out += ' pageid=' + link(v, 'pageid=123');
      out += ' getfile=' + link(v, 'getfile.php');
      out += ' relative=' + link(v, 'Notes/Other.md');
      out += ' anchor=' + link(v, '#links');
      out += ' mail=' + link(v, 'mailto:');
      out += ' explicit=' + link(v, 'example.com/explicit');
    }

    if (mode === 'chat') {
      const c = document.getElementById('chat-messages-container')
             || document.getElementById('chat-view-container');
      out += ' bubbles=' + (c ? c.querySelectorAll('a[href]').length : 'nocontainer');
      out += ' ext=' + link(c, 'example.com/guide');
      out += ' internal=' + link(c, 'pageid=42');
    }
    report(out);
  } catch (e) {
    report('fatal=' + (e && e.message || e));
  }
}, 4000);
</script>
</body>"""
assert s.count('</body>') == 1
io.open(p, 'w', encoding='utf-8', newline='').write(s.replace('</body>', probe))
PY

PORT="${WIKI_URL##*:}"
kill "$WIKI_PID" 2>/dev/null; wait "$WIKI_PID" 2>/dev/null
( cd "$WIKI_APP" && exec php -d "session.save_path=$WIKI_ROOT/sessions" \
    -S "127.0.0.1:$PORT" __router.php ) > "$WIKI_ROOT/router.log" 2>&1 &
WIKI_PID=$!
i=0
until curl -sf --max-time 2 "$WIKI_URL/api.php?action=ping" > /dev/null 2>&1; do
    i=$((i + 1)); [ $i -gt 100 ] && { echo "router did not start" >&2; exit 1; }
    sleep 0.1
done

visit() {
    "$CHROME" --headless=new --disable-gpu --no-sandbox --window-size=1280,900 \
        --virtual-time-budget=30000 \
        --dump-dom "$WIKI_URL/index.php?pageid=$(page_id "$1")&space=Main&mode=$2" \
        > "$WIKI_ROOT/dom.html" 2>/dev/null
    PROBE=$(grep -o 'data-probe="[^"]*"' "$WIKI_ROOT/dom.html" \
            | python3 -c 'import html,sys; sys.stdout.write(html.unescape(sys.stdin.read()))' || true)
    [ -n "$PROBE" ] || _fail "the page never reported (probe did not run)" "page $1"
    assert_not_contains "the probe ran without throwing" 'fatal' "$PROBE"
}

visit Links.md page

section 'on a page, a link that leaves the wiki opens elsewhere'
assert_contains "the page rendered its links" 'rendered=yes'   "$PROBE"
assert_contains "https to another host"       'ext=_blank+safe' "$PROBE"
# Plain http too: what decides is the origin, not the scheme.
assert_contains "and plain http as well"      'extplain=_blank+safe' "$PROBE"

section 'and everything that stays in the wiki stays in the tab'
# The half that a blanket "add target to links" gets wrong.
assert_contains "a page-id link"       'pageid=same'   "$PROBE"
assert_contains "an attachment"        'getfile=same'  "$PROBE"
assert_contains "a relative path"      'relative=same' "$PROBE"
assert_contains "an in-page anchor"    'anchor=same'   "$PROBE"
assert_contains "a mailto"             'mail=same'     "$PROBE"

section 'an author who said otherwise is obeyed'
assert_contains "an explicit target survives" 'explicit=_self' "$PROBE"

visit Talk.chat chat

section 'and the same in a chat, which the page observer never sees'
assert_contains "the bubble rendered its links" 'bubbles=2'     "$PROBE"
assert_contains "the external one opens elsewhere" 'ext=_blank+safe' "$PROBE"
assert_contains "  and the internal one does not"  'internal=same'   "$PROBE"

printf '\n'
exit $(( ASSERT_FAIL > 0 ))
