#!/usr/bin/env bash
# Astucia Wiki — Copyright (C) 2026 Mads Rotwitt
# Free software under the GNU GPL v3 or later. See LICENSE for the full notice,
# or <https://www.gnu.org/licenses/>. Distributed WITHOUT ANY WARRANTY.
#
# The front-matter UI, in a real browser.
#
# Every other suite here is black-box HTTP, which is the right default — but this feature
# was shipped three times with server-side tests green and the UI broken, and each failure
# was *silent*: a button gated on a page type that no page has, and a value captured at two
# read sites that a plain navigation never calls. Nothing HTTP can see any of that, and
# reading the code did not catch it either. Driving the page does.
#
# Chrome is not a test dependency — no chrome means skip, not fail, so CI without it keeps
# working exactly as before. `php -S` sends no Content-Type for .js, which blocks ES modules
# (see CLAUDE.md), so this runs the fixture behind a two-line router that sets it.
#
# The instrumentation only ever *triggers real user actions* (click Edit, click the badge)
# and reports what the DOM then holds. It asserts nothing itself.

set -uo pipefail
cd "$(dirname "$0")"
. lib/assert.sh
. lib/fixture.sh

CHROME=""
for c in google-chrome chromium chromium-browser; do
    command -v "$c" >/dev/null 2>&1 && { CHROME="$c"; break; }
done
if [ -z "$CHROME" ]; then
    printf '  %s\n' "$(_dim 'skipped — no chrome/chromium on PATH')"
    exit 0
fi

fixture_start off || exit 1
trap fixture_stop EXIT

fixture_space Main
printf '%s' '---
title: Quarterly Report
author: Ada Lovelace
status: draft
tags: [finance, q1]
---
# Quarterly Report

Revenue was up.
' > "$WIKI_PAGES/Main/Report.md"
fixture_page 'Main/Plain.md' '# Plain

No metadata here.'

# A second Space with manual editing on, so both forms of the panel can be driven.
fixture_space Editable
printf '%s' '---
title: Editable Page
status: draft
tags:
  - one
  - two
---
# Editable Page

Body.
' > "$WIKI_PAGES/Editable/Edit.md"

curl -s "$WIKI_URL/api.php?action=list_spaces" > /dev/null
curl -s "$WIKI_URL/api.php?action=indexfiles&space=Main" > /dev/null
curl -s "$WIKI_URL/api.php?action=indexfiles&space=Editable" > /dev/null
curl -s -X POST -d 'space_name=Editable&mode=manual' \
     "$WIKI_URL/api.php?action=admin_set_space_fm_edit" > /dev/null
# Manual editing *and* stamping, which is the combination the two settings exist to allow.
curl -s -X POST -d 'space_name=Editable&mode=on' \
     "$WIKI_URL/api.php?action=admin_set_space_fm_autostamp" > /dev/null
printf '%s' '---
title: Stamped Page
created: 2026-01-05T09:00:00+02:00
createdBy: Ada Lovelace
updated: 2026-01-06T09:00:00+02:00
updatedBy: Ada Lovelace
status: draft
---
# Stamped Page

Body.
' > "$WIKI_PAGES/Editable/Stamped.md"
# A page in that Space with **no** block: adding the first field to one of these was
# silently dropped, because the panel rendered the empty-state message instead of the table
# that the new row is appended to.
fixture_page 'Editable/Empty.md' '# Empty

No block here.'
fixture_page 'Editable/Typed.md' '# Typed

No block here either.'
fixture_page 'Editable/Kbd.md' '# Kbd

Body.'
# A page with no block, in a Space that stamps: saving it is what produced the reported
# bug — the four fields landed in the file but the panel kept showing the pre-save state.
fixture_page 'Editable/Stamped2.md' '# Stamped2

Body.'
fixture_page 'Editable/NeverSaved.md' '---
title: Never Saved
status: draft
---
# Never Saved

Body.'
printf '%s' '---
title: Grouped
created: 2026-01-05T09:00:00+02:00
status: draft
createdBy: Ada Lovelace
tags:
  - one
updated: 2026-01-06T09:00:00+02:00
updatedBy: Grace Hopper
nested:
  a: 1
---
# Grouped

Body.
' > "$WIKI_PAGES/Editable/Grouped.md"
printf '%s' '---
tags:
  - one
  - two
langs: [da, en]
nested:
  a: 1
---
# Lists

Body.
' > "$WIKI_PAGES/Editable/Lists.md"
curl -s "$WIKI_URL/api.php?action=indexfiles&space=Editable" > /dev/null

# page_id <file> [space]
page_id() {
    python3 -c 'import json,sys
ix = json.load(open(sys.argv[1]))
print(next(k for k, v in ix.items() if v.get("path") == sys.argv[2]))' \
        "$WIKI_PAGES/${2:-Main}/index.json" "$1"
}

cat > "$WIKI_APP/__router.php" <<'R'
<?php
// GENERATED BY tests/frontmatter_ui.test.sh — never part of a release.
$p = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
$f = __DIR__ . $p;
if ($p !== '/' && is_file($f)) {
    $e = pathinfo($f, PATHINFO_EXTENSION);
    if ($e === 'js')  { header('Content-Type: text/javascript'); readfile($f); return true; }
    if ($e === 'css') { header('Content-Type: text/css');        readfile($f); return true; }
    return false;
}
return false;
R

python3 - "$WIKI_APP/index.php" <<'PY'
import io, sys
p = sys.argv[1]
s = io.open(p, encoding='utf-8', newline='').read()
# ?probe=<what> selects the action; the report goes in document.title, which --dump-dom
# gives us without needing a DevTools connection.
probe = """<script type="module">
const report = () => {
  const badge = document.getElementById('frontmatter-badge');
  const item  = document.getElementById('metadata-btn');
  const dd    = document.querySelector('#page-actions-group .file-actions-dropdown');
  // Where it sits, not just that it exists: it belongs in the page actions row, before
  // the … dropdown, and at the same height as the icons around it.
  const where = badge && badge.parentElement && badge.parentElement.id === 'page-actions-group'
      ? 'actions' : (badge ? 'elsewhere' : 'absent');
  const before = badge && dd && (badge.compareDocumentPosition(dd) & Node.DOCUMENT_POSITION_FOLLOWING)
      ? 'yes' : 'no';
  const h = badge ? Math.round(badge.getBoundingClientRect().height) : 0;
  // Same glyph as the menu item that opens the same panel — one action, one symbol.
  const glyph = (el) => [...(el ? el.querySelectorAll('svg path') : [])]
      .map(p => p.getAttribute('d')).join('|');
  const hRef = dd ? Math.round(dd.getBoundingClientRect().height) : -1;
  // The panel's row order, when one is open: which fields come first, where the rule is,
  // and which rows are editable (marked *).
  const msg = document.getElementById('confirm-modal-message');
  // The gaps either side of the group rule. Measured from the *text*, with a Range: a
  // cell's own rect includes its padding, so comparing cell boxes always reports zero.
  const textRect = (el) => { const r = document.createRange(); r.selectNodeContents(el);
                             return r.getBoundingClientRect(); };
  const sepRow = msg && msg.querySelector('.fm-sep');
  let above = -1, below = -1;
  if (sepRow && sepRow.previousElementSibling && sepRow.nextElementSibling) {
      const line = sepRow.querySelector('td').getBoundingClientRect().bottom;
      above = Math.round(line - textRect(sepRow.previousElementSibling.querySelector('.fm-key')).bottom);
      below = Math.round(textRect(sepRow.nextElementSibling.querySelector('.fm-key')).top - line);
  }
  const shape = msg ? [...msg.querySelectorAll('tbody tr')].map(tr =>
      tr.classList.contains('fm-sep') ? '---'
        : (tr.querySelector('.fm-key') || {}).textContent.trim()
          + (tr.querySelector('.fm-input') ? '*' : '')).join(' ') : '';
  document.title = 'PROBE'
    + ' order=' + JSON.stringify(shape)
    + ' separators=' + (msg ? msg.querySelectorAll('.fm-sep').length : 0)
    + ' ruleGap=' + above + '/' + below
    + ' autoLabels=' + (msg ? msg.querySelectorAll('.fm-auto').length : 0)
    + ' badge='  + (badge ? (badge.classList.contains('hidden') ? 'hidden' : 'visible') : 'absent')
    + ' in='     + where
    + ' beforeDropdown=' + before
    + ' h='      + h + '/' + hRef
    + ' item='   + (item  ? (item.classList.contains('hidden')  ? 'hidden' : 'visible') : 'absent')
    + ' sameGlyph=' + (glyph(badge) && glyph(badge) === glyph(item) ? 'yes' : 'no')
    + ' tip='    + JSON.stringify(badge ? (badge.title || '') : '');
};
// Any uncaught failure becomes the report, so a probe that never runs says why instead of
// looking like a timing problem.
window.addEventListener('error', e => { document.title = 'PROBE fatal=' + e.message; });
window.addEventListener('unhandledrejection', e => {
    document.title = 'PROBE fatalRejection=' + (e.reason && e.reason.message || e.reason); });
setTimeout(() => {
  const probe = new URLSearchParams(location.search).get('probe');
  if (probe === 'edit') {
    document.getElementById('edit-btn')?.click();
    setTimeout(report, 2000);
  } else if (probe === 'open-badge') {
    document.getElementById('frontmatter-badge')?.click();
    setTimeout(report, 1500);
  } else if (probe === 'open-item') {
    document.getElementById('metadata-btn')?.click();
    setTimeout(report, 1500);
  } else if (probe === 'open-item-editor') {
    // The read-only panel's hint names Space settings, which is an admin-only dialog — so
    // an editor is told who to ask instead. The role is read off the body class, which is
    // what index.php sets it from, so swapping it here exercises the real branch.
    document.body.classList.remove('role-admin');
    document.body.classList.add('role-editor');
    document.getElementById('metadata-btn')?.click();
    setTimeout(report, 1500);
  } else if (probe === 'add-field' || probe === 'type-only') {
    // Add a field to a page that has no front matter at all. `type-only` leaves it in the
    // add row without pressing Add, which is what people actually do before hitting Save.
    document.getElementById('metadata-btn')?.click();
    setTimeout(() => {
      const host = document.getElementById('confirm-modal-message');
      const k = document.getElementById('fm-new-key');
      const v = document.getElementById('fm-new-val');
      if (k && v) { k.value = 'owner'; v.value = 'Ada Lovelace'; }
      if (probe === 'add-field') document.getElementById('fm-add-btn')?.click();
      const box = document.querySelector('#confirm-modal .lightbox-content').getBoundingClientRect();
      document.title = 'PROBE table=' + (host.querySelector('.fm-table tbody') ? 'yes' : 'NO')
        + ' inputs=' + host.querySelectorAll('.fm-input').length
        + ' width=' + Math.round(box.width)
        + ' height=' + Math.round(box.height);
      document.getElementById('confirm-modal-ok').click();
    }, 1500);
    return;
  } else if (probe === 'keyboard') {
    // Three fields entered with the keyboard alone. confirmModal confirms on Enter from
    // anywhere in the document, so without the panel stopping that event, tabbing to Add
    // and pressing Enter saved and closed — making this impossible.
    const enter = (el) => el.dispatchEvent(new KeyboardEvent('keydown',
        { key: 'Enter', bubbles: true, cancelable: true }));
    document.getElementById('metadata-btn')?.click();
    setTimeout(() => {
      const host = document.getElementById('confirm-modal-message');
      const k = document.getElementById('fm-new-key');
      const v = document.getElementById('fm-new-val');
      const btn = document.getElementById('fm-add-btn');
      k.value = 'one';   v.value = '1'; btn.focus(); enter(btn);
      k.value = 'two';   v.value = '2'; v.focus();   enter(v);
      k.value = 'three'; v.value = '3'; k.focus();   enter(k);
      document.title = 'PROBE dialog='
          + (document.getElementById('confirm-modal').classList.contains('hidden') ? 'CLOSED' : 'open')
          + ' rows=' + host.querySelectorAll('.fm-input').length
          + ' refocused=' + (document.activeElement && document.activeElement.id === 'fm-new-key' ? 'yes' : 'NO')
          + ' cleared=' + (k.value === '' ? 'yes' : 'NO');
      document.getElementById('confirm-modal-ok').click();
    }, 1500);
    return;
  } else if (probe === 'multi') {
    document.getElementById('metadata-btn')?.click();
    setTimeout(() => {
      const host = document.getElementById('confirm-modal-message');
      const tags = host.querySelector('.fm-input[data-key="tags"]');
      const langs = host.querySelector('.fm-input[data-key="langs"]');
      document.getElementById('fm-new-key').value = 'authors';
      document.getElementById('fm-new-val').value = 'Ada, Grace';
      document.getElementById('fm-new-multi').checked = true;
      document.getElementById('fm-add-btn').click();
      if (tags) tags.value = 'alpha, beta, gamma';
      if (langs) langs.value = 'sv, no';
      document.title = 'PROBE listEditable=' + (tags ? 'yes' : 'NO')
        + ' listShown=' + JSON.stringify(tags ? tags.defaultValue : '')
        + ' listMarked=' + (tags && tags.dataset.multi ? 'yes' : 'NO')
        + ' nestedEditable=' + (host.querySelector('.fm-input[data-key="nested"]') ? 'YES' : 'no')
        + ' hasMultiBox=' + (document.getElementById('fm-new-multi') ? 'yes' : 'NO');
      document.getElementById('confirm-modal-ok').click();
    }, 1500);
    return;
  } else if (probe === 'save-then-open') {
    // Edit and save the page the way a person would, then open the panel *without
    // navigating* — the cached metadata came from the `get` that rendered the page, and
    // stamping happens after it.
    document.getElementById('edit-btn').click();
    setTimeout(() => {
      const ta = document.getElementById('editor-container');
      ta.value = '# Stamped2\\n\\nEdited in the browser.\\n';
      // Save is disabled until the editor is dirty, so the edit is announced as typing would.
      ta.dispatchEvent(new Event('input', { bubbles: true }));
      document.getElementById('save-btn').click();
      setTimeout(() => {
        const badge = document.getElementById('frontmatter-badge');
        const wasVisible = badge && !badge.classList.contains('hidden');
        document.getElementById('metadata-btn').click();
        setTimeout(() => {
          const host = document.getElementById('confirm-modal-message');
          const keys = [...host.querySelectorAll('tbody .fm-key')].map(td => td.textContent.trim());
          document.title = 'PROBE keys=' + JSON.stringify(keys.join(','))
            + ' editableRows=' + host.querySelectorAll('tbody .fm-input').length
            + ' autoLabels=' + host.querySelectorAll('.fm-auto').length
            + ' separators=' + host.querySelectorAll('.fm-sep').length
            + ' order=' + JSON.stringify([...host.querySelectorAll('tbody tr')].map(tr =>
                  tr.classList.contains('fm-sep') ? '---'
                    : tr.querySelector('.fm-key').textContent.trim()
                      + (tr.querySelector('.fm-input') ? '*' : '')).join(' '))
            + ' removable=' + host.querySelectorAll('.fm-rm').length
            + ' indicator=' + (wasVisible ? 'visible' : 'HIDDEN');
        }, 1200);
      }, 3000);
    }, 1500);
    return;
  } else if (probe === 'layout') {
    document.getElementById('metadata-btn')?.click();
    setTimeout(async () => {
      const host = document.getElementById('confirm-modal-message');
      const rowIn = host.querySelector('tbody .fm-input');
      const newVal = document.getElementById('fm-new-val');
      const btn = document.getElementById('fm-add-btn');
      const cs = getComputedStyle(btn);
      const inner = btn.clientWidth - parseFloat(cs.paddingLeft) - parseFloat(cs.paddingRight);
      // The widest Add label across every locale, read from the locale files rather than
      // hardcoded, so this keeps holding when a translation changes.
      const span = document.createElement('span');
      span.style.cssText = 'position:absolute;visibility:hidden;white-space:nowrap;font:' + cs.font;
      document.body.appendChild(span);
      let widest = 0, worst = '';
      for (const l of ['en','da','sv','es','fr','de','zh','hi','ja']) {
        const m = (await import('./modules/i18n/locales/' + l + '.js')).default;
        span.textContent = m['fm.add'];
        const w = Math.ceil(span.getBoundingClientRect().width);
        if (w > widest) { widest = w; worst = l; }
      }
      const a = rowIn.getBoundingClientRect(), b = newVal.getBoundingClientRect();
      document.title = 'PROBE aligned='
          + (Math.abs(a.left - b.left) <= 1 && Math.abs(a.right - b.right) <= 1 ? 'yes' : 'NO')
          + ' edges=' + Math.round(a.left) + '/' + Math.round(b.left)
          + ':' + Math.round(a.right) + '/' + Math.round(b.right)
          + ' labelFits=' + (widest <= inner ? 'yes' : 'NO')
          + ' widest=' + widest + '(' + worst + ')/' + Math.round(inner);
    }, 1500);
    return;
  } else if (probe === 'space-settings') {
    // The Space settings dialog, whose two selects drive the per-Space policies. Worth
    // driving because a callback it invokes was missing from its own parameter list, which
    // threw a ReferenceError *after* a successful save — invisible to any HTTP test.
    document.getElementById('space-switcher')?.querySelector('.space-switcher-header')?.click();
    setTimeout(() => {
      document.getElementById('space-settings-btn')?.click();
      setTimeout(() => {
        const ed = document.getElementById('space-fm-edit');
        const st = document.getElementById('space-fm-stamp');
        window.__err = null;
        // Both, and the second is the one that matters: these handlers are `async`, so a
        // ReferenceError inside one surfaces as an unhandled *rejection* and never reaches
        // the window's `error` event. Listening only for `error` made this check silently
        // useless — it passed against the very bug it was written for.
        window.addEventListener('error', e => { window.__err = String(e.message); });
        window.addEventListener('unhandledrejection',
            e => { window.__err = String(e.reason && e.reason.message || e.reason); });
        if (st) { st.value = 'on'; st.dispatchEvent(new Event('change')); }
        setTimeout(() => {
          // Geometry as well as behaviour: this dialog has grown a section at a time and
          // at a fixed height its last section and its Close button fell outside the box
          // with nothing to scroll.
          const c = document.querySelector('.space-settings-content');
          const b = document.querySelector('.space-settings-body');
          const btn = document.querySelector('.space-settings-content .lightbox-footer button');
          const r = c && c.getBoundingClientRect();
          const br = btn && btn.getBoundingClientRect();
          const reachable = b
            ? (b.scrollTop = b.scrollHeight,
               Math.round(b.scrollTop + b.clientHeight) >= b.scrollHeight - 2)
            : false;
          document.title = 'PROBE edit=' + (ed ? ed.value : 'absent')
            + ' stamp=' + (st ? st.value : 'absent')
            + ' error=' + (window.__err ? 'YES:' + window.__err : 'none')
            + ' sections=' + (b ? b.querySelectorAll('.space-settings-section').length : 0)
            + ' fits=' + (r && r.bottom <= window.innerHeight && r.top >= 0 ? 'yes' : 'NO')
            + ' closeVisible=' + (br && br.bottom <= window.innerHeight && br.top >= 0 ? 'yes' : 'NO')
            + ' lastReachable=' + (reachable ? 'yes' : 'NO');
        }, 1200);
      }, 1200);
    }, 600);
    return;
  } else if (probe === 'new-space') {
    // The create-Space dialog must ask for the metadata policy alongside the name.
    document.querySelector('#space-switcher .space-dropdown-new')?.click();
    setTimeout(() => {
      const host = document.getElementById('confirm-modal-message');
      const name = document.getElementById('new-space-name');
      const sel  = document.getElementById('new-space-fm');
      const st   = document.getElementById('new-space-stamp');
      document.title = 'PROBE name=' + (name ? 'yes' : 'no')
        + ' select=' + (sel ? 'yes' : 'no')
        + ' default=' + (sel ? sel.value : '-')
        + ' options=' + (sel ? [...sel.options].map(o => o.value).join(',') : '-')
        + ' stampSelect=' + (st ? 'yes' : 'no')
        + ' stampDefault=' + (st ? st.value : '-')
        + ' stampOptions=' + (st ? [...st.options].map(o => o.value).join(',') : '-');
      if (name && sel) { name.value = 'FromDialog'; sel.value = 'manual'; }
      if (st) st.value = 'on';
      document.getElementById('confirm-modal-ok').click();
    }, 1500);
    return;
  } else if (probe === 'edit-field') {
    // Open the panel, change one value, add a field, mark one for removal, save.
    document.getElementById('metadata-btn')?.click();
    setTimeout(() => {
      const host = document.getElementById('confirm-modal-message');
      const inp  = host.querySelector('.fm-input[data-key="status"]');
      if (inp) inp.value = 'published';
      const beforeAdd = host.querySelectorAll('.fm-input').length;
      document.getElementById('fm-new-key').value = 'owner';
      document.getElementById('fm-new-val').value = 'Ada Lovelace';
      document.getElementById('fm-add-btn').click();
      host.querySelector('.fm-rm[data-key="title"]')?.click();
      document.title = 'PROBE editable=' + beforeAdd
        + ' afterAdd=' + host.querySelectorAll('.fm-input').length
        + ' locked=' + host.querySelectorAll('.fm-locked').length
        + ' struck=' + host.querySelectorAll('.fm-removed').length;
      document.getElementById('confirm-modal-ok').click();
    }, 1500);
    return;
  } else {
    report();
  }
}, 5000);
</script>
</body>"""
assert s.count('</body>') == 1
io.open(p, 'w', encoding='utf-8', newline='').write(s.replace('</body>', probe))
PY

# Restart the fixture's server behind the router.
PORT="${WIKI_URL##*:}"
kill "$WIKI_PID" 2>/dev/null; wait "$WIKI_PID" 2>/dev/null
( cd "$WIKI_APP" && exec php -d "session.save_path=$WIKI_ROOT/sessions" \
    -S "127.0.0.1:$PORT" __router.php ) > "$WIKI_ROOT/router.log" 2>&1 &
WIKI_PID=$!
i=0
until curl -sf --max-time 2 "$WIKI_URL/api.php?action=ping" > /dev/null 2>&1; do
    i=$((i + 1)); [ $i -gt 100 ] && { echo "router did not start" >&2; exit 1; }
    sleep 0.1
done

# load <page> [probe] [space] → DOM of that page in $DOM, the probe line in $PROBE
load() {
    local sp="${3:-Main}"
    local q="pageid=$(page_id "$1" "$sp")&space=$sp"
    [ -n "${2:-}" ] && q="$q&probe=$2"
    "$CHROME" --headless=new --disable-gpu --no-sandbox --window-size=1280,900 \
        --virtual-time-budget=25000 \
        --dump-dom "$WIKI_URL/index.php?$q" > "$WIKI_ROOT/dom.html" 2>/dev/null
    DOM=$(cat "$WIKI_ROOT/dom.html")
    PROBE=$(printf '%s' "$DOM" | grep -o '<title>PROBE[^<]*</title>' || true)
    [ -n "$PROBE" ] || _fail "the page never reported (probe did not run)" "page $1"
}
# The rows the panel rendered, as `key=value` lines.
rows() {
    python3 - "$WIKI_ROOT/dom.html" <<'PY'
import re, io, sys
s = io.open(sys.argv[1], encoding='utf-8').read()
for k, v in re.findall(r'<td class="fm-key">([^<]*)</td><td class="fm-val">(.*?)</td>', s):
    print(f'{k}={v}')
PY
}
modal_title() {
    printf '%s' "$DOM" | grep -o 'id="confirm-modal-title"[^>]*>[^<]*' | sed 's/.*>//'
}
# Only the panel's own markup. The probe script injected into the page mentions the class
# names it clicks, so a `not_contains` against the whole document would match that script
# rather than the panel.
modal_body() {
    python3 - "$WIKI_ROOT/dom.html" <<'PY'
import re, io, sys
s = io.open(sys.argv[1], encoding='utf-8').read()
m = re.search(r'id="confirm-modal-message".*?(?=<div class="lightbox-footer")', s, re.S)
print(m.group(0) if m else '')
PY
}

section 'a page that carries front matter says so, without a click'
load Report.md
assert_contains "the indicator is shown"        'badge=visible' "$PROBE"
assert_contains "  in the page actions row"     'in=actions'    "$PROBE"
assert_contains "  left of the … dropdown"      'beforeDropdown=yes' "$PROBE"
assert_contains "  with the field count"        '4 fields'      "$PROBE"
assert_contains "  and the field names"         'title, author, status, tags' "$PROBE"
assert_contains "the menu item is available"    'item=visible'  "$PROBE"
assert_contains "  and both use the same glyph" 'sameGlyph=yes' "$PROBE"
# Same height as the icons it sits among — the whole point of using their classes rather
# than a bespoke chip. Compared against the dropdown beside it, measured in the browser.
h=$(printf '%s' "$PROBE" | sed -n 's/.* h=\([0-9]*\)\/\([0-9-]*\) .*/\1 \2/p')
printf '  %s\n' "$(_dim "measured: badge ${h% *}px, dropdown ${h#* }px")"
# A zero would satisfy the comparison below while meaning "not rendered at all".
assert_eq "  it actually has a height" '32' "$(printf '%s' "$h" | cut -d' ' -f1)"
assert_eq "  and the same height as them" "$(printf '%s' "$h" | cut -d' ' -f2)" \
                                          "$(printf '%s' "$h" | cut -d' ' -f1)"

section 'a page that carries none shows nothing'
load Plain.md
assert_contains "no indicator"                  'badge=hidden'  "$PROBE"
# The menu item stays: it is how you learn the page has no metadata.
assert_contains "the menu item is still there"  'item=visible'  "$PROBE"

section 'the editor is where knowing matters most, so it stays visible there'
# The editor is handed the body with the block removed, so this is the one view that has
# silently dropped it — an author editing an imported page would otherwise have no clue.
load Report.md edit
assert_contains "still shown in edit mode"      'badge=visible' "$PROBE"

section 'both entry points open the same panel'
load Report.md open-badge
assert_eq "clicking the indicator opens it" 'Page metadata' "$(modal_title)"
got=$(rows)
assert_contains "  title"   'title=Quarterly Report' "$got"
assert_contains "  author"  'author=Ada Lovelace'    "$got"
assert_contains "  status"  'status=draft'           "$got"
assert_contains "  a list joins with commas" 'tags=finance, q1' "$got"

load Report.md open-item
assert_eq "the menu item opens it too" 'Page metadata' "$(modal_title)"
assert_contains "  same rows" 'author=Ada Lovelace' "$(rows)"

section 'and a page with none explains itself rather than showing an empty table'
load Plain.md open-item
assert_eq "the panel still opens" 'Page metadata' "$(modal_title)"
assert_eq "with no table"         ''              "$(rows)"
assert_contains "and an explanation" 'no front matter' "$DOM"
# The emptiest panel is the one that most needs to say where editing is turned on: "this
# file has no front matter" on its own answers nothing about how to give it some.
assert_contains "  and where editing is turned on" 'fm-edit-off' "$(modal_body)"
assert_contains "  naming Space settings" 'Space settings' "$(modal_body)"

section 'where the Space allows it, the panel is an editor'
load Edit.md open-item Editable
panel=$(modal_body)
assert_eq "the panel opens" 'Page metadata' "$(modal_title)"
assert_not_contains "and no hint about turning editing on" 'fm-edit-off' "$panel"
assert_contains "the scalar fields are inputs"  'class="form-control fm-input"' "$panel"
assert_contains "  including status"            'data-key="status"'             "$panel"
# A list is editable now, as a comma-separated box marked data-multi.
assert_contains "a list field is an input too"  'data-key="tags" data-multi'    "$panel"
assert_contains "  labelled as comma-separated" 'fm-multi-note'                 "$panel"
assert_contains "there is a way to add a field" 'id="fm-add-btn"'               "$panel"
assert_contains "and a way to remove one"       'class="fm-rm"'                 "$panel"

section 'and where it does not, the same panel is read-only'
load Report.md open-item Main
panel=$(modal_body)
assert_contains     "the values are still shown" 'Ada Lovelace'  "$panel"
assert_not_contains "but there are no inputs"    'fm-input'      "$panel"
assert_not_contains "no add row"                 'fm-add-btn'    "$panel"
assert_not_contains "no remove buttons"          'class="fm-rm"' "$panel"
# Read-only is a Space setting, not a property of the file, so the panel says so and says
# where it is changed — otherwise the only reading available is "this wiki cannot do it".
assert_contains "it says why it is read-only" 'read-only' "$panel"
assert_contains "  and where to change it"    'Turn editing on in Space settings' "$panel"

load Report.md open-item-editor Main
panel=$(modal_body)
assert_contains "an editor is told who can change it" 'An administrator can change that' "$panel"
assert_not_contains "  and is not sent to a dialog they cannot open" 'the gear beside' "$panel"

section 'editing writes through to the file'
load Edit.md edit-field Editable
# title, status and the tags list — a list is editable as well now.
assert_contains "all three fields were editable"   'editable=3' "$PROBE"
assert_contains "  and the added field joined them" 'afterAdd=4' "$PROBE"
assert_contains "  nothing was locked"             'locked=0'  "$PROBE"
assert_contains "  and one row was struck through" 'struck=1'  "$PROBE"
file=$(cat "$WIKI_PAGES/Editable/Edit.md")
assert_contains     "the changed value landed"  'status: published'     "$file"
assert_contains     "the added field landed"    'owner: Ada Lovelace'   "$file"
assert_not_contains "the removed field is gone" 'title:'                "$file"
assert_contains     "the list is untouched"     '  - one'               "$file"
assert_contains     "and so is the body"        'Body.'                 "$file"

section 'a new Space is asked about the policy, with the name'
# The switcher's dropdown has to be open for its "New" row to exist, so the probe clicks
# that row rather than calling anything directly.
load Report.md new-space Main
assert_contains "the dialog asks for a name"     'name=yes'          "$PROBE"
assert_contains "  and for the metadata policy"  'select=yes'        "$PROBE"
assert_contains "  which defaults to off"        'default=off'       "$PROBE"
assert_contains "  offering both modes"          'options=off,manual' "$PROBE"
assert_contains "  and asks about stamping too"  'stampSelect=yes'   "$PROBE"
assert_contains "  also defaulting to off"       'stampDefault=off'  "$PROBE"
assert_contains "  with both modes"              'stampOptions=off,on' "$PROBE"
sleep 1
created=$(curl -s "$WIKI_URL/api.php?action=list_spaces")
assert_contains "the Space was created"          'FromDialog'        "$created"
assert_contains "  with the chosen policy"       '"fm_edit":["Editable","FromDialog"]' "$created"
assert_contains "  and the chosen stamping"      '"fm_autostamp":["Editable","FromDialog"]' "$created"

section 'the fields the wiki maintains are shown, but never as text boxes'
load Stamped.md open-item Editable
panel=$(modal_body)
assert_contains     "the stamped values are shown"   'Ada Lovelace'       "$panel"
assert_not_contains "  with no per-row label"        'fm-auto'            "$panel"
assert_not_contains "  and not editable"             'data-key="updatedBy"' "$panel"
assert_not_contains "  nor removable"                'fm-rm" data-key="updated"' "$panel"
assert_contains     "an ordinary field is still editable" 'data-key="status"' "$panel"
assert_contains     "and the panel says why"         'maintained by the wiki' "$panel"

section 'a field can be added to a page that has no block at all'
# The reported bug: on such a page the panel showed the empty-state text instead of a
# table, so the Add button appended a row into a tbody that did not exist. The field
# vanished, Save found nothing to send, and it returned without a word.
load Empty.md add-field Editable
assert_contains "the table is there to add into" 'table=yes' "$PROBE"
assert_contains "  and the field is in it"       'inputs=1'  "$PROBE"
sleep 1
empty=$(cat "$WIKI_PAGES/Editable/Empty.md")
assert_eq       "the file gained a block" '---' "$(printf '%s' "$empty" | head -1)"
assert_contains "with the new field"      'owner: Ada Lovelace' "$empty"
assert_contains "and the body kept"       'No block here.'      "$empty"

section 'and typing a field without pressing Add still saves it'
load Typed.md type-only Editable
sleep 1
typed=$(cat "$WIKI_PAGES/Editable/Typed.md")
assert_contains "the typed field was saved" 'owner: Ada Lovelace' "$typed"

section 'the panel has room for a table of fields'
# The shared confirm dialog is sized for a sentence of prose (~424px wide); a table of
# fields with inputs in it needs more, and gets it via the .fm-view wrapper.
load Edit.md open-item Editable
assert_contains "the panel is wrapped for sizing" 'class="fm-view"' "$(modal_body)"
load Empty.md add-field Editable
w=$(printf '%s' "$PROBE" | sed -n 's/.* width=\([0-9]*\).*/\1/p')
h=$(printf '%s' "$PROBE" | sed -n 's/.* height=\([0-9]*\).*/\1/p')
# Measured in a 1280x900 window (see load()), where the shared dialog is 424x306 for a
# sentence of prose. Thresholds sit between that and what the panel now gets.
printf '  %s\n' "$(_dim "measured: ${w}x${h}px in a 1280x900 window")"
if [ "${w:-0}" -gt 600 ]; then _pass "it is wider than the default dialog"
else _fail "it is wider than the default dialog" "width was ${w:-?}px"; fi
if [ "${h:-0}" -gt 420 ]; then _pass "and taller"
else _fail "and taller" "height was ${h:-?}px"; fi

section 'many fields can be entered from the keyboard, without the dialog closing'
load Kbd.md keyboard Editable
assert_contains "the dialog stayed open"     'dialog=open'  "$PROBE"
assert_contains "  all three were added"     'rows=3'       "$PROBE"
assert_contains "  focus returned to the key box" 'refocused=yes' "$PROBE"
assert_contains "  which was cleared"        'cleared=yes'  "$PROBE"
sleep 1
kbd=$(cat "$WIKI_PAGES/Editable/Kbd.md")
for f in 'one: 1' 'two: 2' 'three: 3'; do
    assert_contains "  and written: $f" "$f" "$kbd"
done

section 'a multi-value property'
load Lists.md multi Editable
assert_contains "a list is editable"          'listEditable=yes' "$PROBE"
assert_contains "  shown comma-separated"     'listShown="one, two"' "$PROBE"
assert_contains "  and marked as a list"      'listMarked=yes'   "$PROBE"
assert_contains "a nested value is not"       'nestedEditable=no' "$PROBE"
assert_contains "there is a multi-value box"  'hasMultiBox=yes'  "$PROBE"
sleep 1
lists=$(cat "$WIKI_PAGES/Editable/Lists.md")
assert_contains     "the block list kept its style" '  - alpha' "$lists"
assert_not_contains "  and was not flattened"       'tags: ['   "$lists"
assert_contains     "the flow list kept its style"  'langs: [sv, no]' "$lists"
assert_contains     "the new list was added"        'authors: [Ada, Grace]' "$lists"
assert_contains     "and the nested value survived" '  a: 1'    "$lists"

section 'the panel describes what it actually is'
# It said "the wiki does not write this block", which stopped being true the moment
# editing and stamping existed — and it has to say something different per Space. The
# intro is now only about where the values *came from*; whether they can be changed, and
# where that is decided, is the sentence under it.
load Edit.md open-item Editable
assert_contains     "an editable Space says so"  'written into the file itself' "$(modal_body)"
assert_not_contains "  not the read-only line"   'nothing can be added'         "$(modal_body)"
load Report.md open-item Main
assert_contains     "a read-only Space says that" 'nothing can be added or changed here' "$(modal_body)"
assert_not_contains "  without claiming the wiki never writes it" 'does not write' "$(modal_body)"
load Stamped.md open-item Editable
assert_contains     "and a stamped Space names the four" 'maintained by the wiki' "$(modal_body)"

section 'what a save stamps is shown straight away, read-only'
# The reported bug: the fields were written to the file but the panel still showed what it
# had read before the save, because only `lastUpdated` and `size` came back on the response.
load Stamped2.md save-then-open Editable
assert_contains     "the stamped fields are listed"  'created'   "$PROBE"
assert_contains "  including the timestamp"          'updated'   "$PROBE"
assert_contains "  none of them editable"            'editableRows=0' "$PROBE"
assert_contains "  and carry no per-row label"       'autoLabels=0'   "$PROBE"
assert_contains "  and none removable"               'removable=0'    "$PROBE"
# The indicator has to appear too: the page had no block at all until this save.
assert_contains "the indicator appeared"             'indicator=visible' "$PROBE"

section "the wiki's fields come first, then a rule, then the author's"
# A per-row "auto" badge said this once per row; the grouping says it once. The order
# within the first group is the wiki's own (created, createdBy, updated, updatedBy), not
# whatever order the file happens to list them in.
load Grouped.md open-item Editable
assert_contains "the four come first, in the wiki's order" \
    'order="created createdBy updated updatedBy ---' "$PROBE"
assert_contains "  followed by the author's fields"  '--- title* status* tags*' "$PROBE"
assert_contains "exactly one rule between them"      'separators=1'   "$PROBE"
assert_contains "and no per-row label"               'autoLabels=0'   "$PROBE"
# Assert on the note element, not on its wording: the intro line mentions the wiki too,
# so a phrase match cannot tell the two apart.
assert_contains "the group is explained once"        'fm-managed-note' "$(modal_body)"
# The rule needs room on both sides or it reads as a line through one list rather than a
# break between two. A table row cannot carry a margin, so the space below it comes from
# the following row's padding — which is easy to lose and invisible to every other check.
gap=$(printf '%s' "$PROBE" | tr ' ' '\n' | sed -n 's|^ruleGap=||p')
printf '  %s\n' "$(_dim "gap above/below the rule: ${gap}px")"
if [ "${gap%/*}" -ge 8 ] && [ "${gap#*/}" -ge 8 ]; then
    _pass "there is room on both sides of it"
else
    _fail "there is room on both sides of it" "measured ${gap}px (above/below)"
fi
# With nothing for the wiki to maintain there is no rule, and no note: a line above or
# below nothing is a line with no meaning.
# NeverSaved.md is used by nothing else: every other page in this Space has been saved by
# an earlier test, and saving here stamps, so they all have the four fields by now.
load NeverSaved.md open-item Editable
assert_contains     "a page with no stamps has no rule" 'separators=0' "$PROBE"
assert_not_contains "  and no note"                     'fm-managed-note' "$(modal_body)"

section 'the add row lines up with the rows above it'
# It was a flex row beside the table, so its boxes matched the columns only if a percentage
# width and a cell padding were kept in step with the table's — which they were not.
load Lists.md layout Editable
assert_contains "the value boxes share an edge" 'aligned=yes' "$PROBE"
# $PROBE is the whole <title> element, so a reported field is cut out of it by hand.
field() { printf '%s' "$PROBE" | tr ' ' '\n' | sed -n "s|^$1=||p" | sed 's|</title>||'; }
printf '  %s\n' "$(_dim "value box left/right — row vs add row: $(field edges)")"
# The Add button shares the column with the × buttons, and "Add" is short in English only.
assert_contains "the longest Add label fits"    'labelFits=yes' "$PROBE"
printf '  %s\n' "$(_dim "widest label vs available space: $(field widest)")"

section 'the Space settings dialog drives both policies'
load Report.md space-settings Main
assert_contains "the metadata select is there"  'edit='       "$PROBE"
assert_contains "the stamping select is there"  'stamp=on'    "$PROBE"
# The callback fired by that change was once referenced without being declared, which threw
# only in the browser, only after the request had already succeeded.
assert_contains "and changing it raises no error" 'error=none' "$PROBE"
# The box has to hold what it now contains: five sections plus the Close button.
assert_contains "every section is present"    'sections=5'       "$PROBE"
assert_contains "the dialog fits the window"  'fits=yes'         "$PROBE"
assert_contains "the Close button is inside it" 'closeVisible=yes' "$PROBE"
assert_contains "and the last section is reachable" 'lastReachable=yes' "$PROBE"
sleep 1
after=$(curl -s "$WIKI_URL/api.php?action=admin_space_settings")
assert_contains "the change reached the server" '"name":"Main","readonly":false,"fm_edit":"off","fm_autostamp":"on"' "$after"

printf '\n'
exit $(( ASSERT_FAIL > 0 ))
