#!/usr/bin/env bash
# Astucia Wiki — Copyright (C) 2026 Mads Rotwitt
# Free software under the GNU GPL v3 or later. See LICENSE for the full notice,
# or <https://www.gnu.org/licenses/>. Distributed WITHOUT ANY WARRANTY.
#
# Admin → AI → LLM Providers, the AI user form that now names one, the avatar picker, and
# the chat bubble that draws the chosen avatar.
#
# A browser suite because the failure that matters is invisible over HTTP: the tab could
# render nothing, the form could still carry a key box nobody reads, or a pick in the grid
# could never reach the hidden input the save reads — and every endpoint would stay green.
# It clicks the real controls and reads the result off the DOM.
#
# Chrome is not a test dependency — no chrome means skip, not fail.

set -uo pipefail
cd "$(dirname "$0")"
. lib/assert.sh
. lib/fixture.sh

CHROME=""
for c in google-chrome chromium chromium-browser; do
    command -v "$c" >/dev/null 2>&1 && { CHROME="$c"; break; }
done
if [ -z "$CHROME" ]; then
    printf '  %s\n' "$(_dim 'skipped — no chrome/chromium on PATH')"
    exit 0
fi

fixture_start off || exit 1
trap fixture_stop EXIT
fixture_space Main

# Legacy shape: the first request migrates it, so the UI is looking at migrated data —
# which is the state every upgraded install will be in.
fixture_users '{"users":[
 {"uid":-1,"name":"Ann","role":"editor","is_ai":true,
  "ai_config":{"provider":"openai","api_url":"","api_key":"sk-one","model":"gpt-a"}},
 {"uid":-2,"name":"Ben","role":"editor","is_ai":true,
  "ai_config":{"provider":"anthropic","api_url":"","api_key":"sk-two","model":"claude-x"}}]}'
cat > "$WIKI_PAGES/Main/Talk.chat" <<'JSON'
{"messages":[
 {"id":1,"uid":-1,"name":"Ann","text":"Hello from Ann","ts":"2026-10-01T10:00:00+00:00"},
 {"id":2,"uid":-2,"name":"Ben","text":"Hello from Ben","ts":"2026-10-01T10:01:00+00:00"}],
 "nextMessageId":3,"topic":"T"}
JSON
curl -s "$WIKI_URL/api.php?action=list_spaces" > /dev/null
curl -s "$WIKI_URL/api.php?action=indexfiles&space=Main" > /dev/null

cat > "$WIKI_APP/__router.php" <<'R'
<?php
// GENERATED BY tests/llm_providers_ui.test.sh — never part of a release.
$p = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
$f = __DIR__ . $p;
if ($p !== '/' && is_file($f)) {
    $e = pathinfo($f, PATHINFO_EXTENSION);
    if ($e === 'js')  { header('Content-Type: text/javascript'); readfile($f); return true; }
    if ($e === 'css') { header('Content-Type: text/css');        readfile($f); return true; }
    if ($e === 'svg') { header('Content-Type: image/svg+xml');   readfile($f); return true; }
    return false;
}
return false;
R

python3 - "$WIKI_APP/index.php" <<'PY'
import io, sys
p = sys.argv[1]
s = io.open(p, encoding='utf-8', newline='').read()
# Reported through a data-probe attribute and document.title. No backslashes in here:
# this lives in a Python heredoc inside a shell script.
probe = """<script type="module">
const sleep = (ms) => new Promise(r => setTimeout(r, ms));
const $ = (sel) => document.querySelector(sel);
const rows = (id) => Array.from(document.querySelectorAll('#' + id + ' tbody tr'));
const click = (el) => { if (!el) throw new Error('missing control'); el.click(); };
const report = (out) => { document.title = 'PROBE' + out; };

window.addEventListener('error', e => report(' fatal=' + e.message));
window.addEventListener('unhandledrejection', e => report(' fatal=' + (e.reason && e.reason.message || e.reason)));

const admin = async () => {
  let out = '';
  click($('#admin-btn'));                                    await sleep(800);
  click($('.admin-group[data-group="ai"]'));                 await sleep(800);
  click($('.admin-tab[data-tab="llm"]'));                    await sleep(1000);
  const names = rows('admin-llm-list').map(tr => tr.querySelector('.admin-td-name')?.firstChild?.textContent.trim());
  out += ' providers=' + names.length + ' names=' + names.sort().join('+');
  out += ' usedby=' + rows('admin-llm-list').map(tr => tr.children[3].textContent).sort().join('+');

  // The AI user form names a provider instead of carrying the connection itself.
  click($('.admin-tab[data-tab="ai"]'));                     await sleep(1000);
  const ann = rows('admin-ai-list').find(tr => tr.textContent.includes('Ann'));
  out += ' listconn=' + (ann?.children[4]?.textContent || 'none');
  click(ann.querySelector('.btn-secondary'));               await sleep(1200);
  const sel = $('#ai-f-connection');
  out += ' select=' + (sel ? sel.options.length : 'missing') + '/' + (sel && sel.value ? 'set' : 'empty');
  out += ' keybox=' + ($('#ai-f-key') ? 'present' : 'gone') + ' urlbox=' + ($('#ai-f-url') ? 'present' : 'gone');

  // Avatar: open the grid, pick one, and the preview and the hidden input follow.
  click($('#ai-f-avatar-toggle'));                           await sleep(200);
  const grid = $('#ai-f-avatar-grid');
  out += ' grid=' + (grid.classList.contains('hidden') ? 'closed' : 'open') + '/' + grid.querySelectorAll('[data-avatar]').length;
  click(grid.querySelector('[data-avatar="owl"]'));          await sleep(200);
  out += ' picked=' + $('#ai-f-avatar').value + ' preview=' + (($('#ai-f-avatar-btn img')?.getAttribute('src')) || 'none');
  out += ' closed=' + grid.classList.contains('hidden');
  const img = grid.querySelector('[data-avatar="owl"] img');
  out += ' loaded=' + (img && img.complete && img.naturalWidth > 0);
  click($('#ai-f-save-btn'));                                await sleep(1500);

  // "Manage LLM providers" goes to the tab rather than being decoration.
  const ann2 = rows('admin-ai-list').find(tr => tr.textContent.includes('Ann'));
  out += ' listavatar=' + ((ann2?.querySelector('.avatar-circle img')?.getAttribute('src')) || 'none');
  click(ann2.querySelector('.btn-secondary'));              await sleep(1200);
  click($('#ai-f-connection-manage'));                       await sleep(1000);
  out += ' manage=' + ($('#admin-pane-llm').classList.contains('hidden') ? 'stayed' : 'went');

  // A new provider from the tab's own form.
  click($('#admin-llm-add-btn'));                            await sleep(600);
  $('#llm-f-name').value = 'Spare';
  $('#llm-f-provider').value = 'anthropic';
  $('#llm-f-key').value = 'sk-three';
  click($('#llm-f-save-btn'));                               await sleep(1500);
  out += ' after=' + rows('admin-llm-list').length;
  return out;
};

const chat = async () => {
  const av = (name) => {
    const row = Array.from(document.querySelectorAll('.chat-row'))
        .find(r => r.textContent.includes('Hello from ' + name));
    const a = row?.querySelector('.chat-avatar');
    if (!a) return 'missing';
    const img = a.querySelector('img');
    return img ? 'img:' + img.getAttribute('src') : (a.querySelector('svg') ? 'glyph' : 'empty');
  };
  return ' ann=' + av('Ann') + ' ben=' + av('Ben');
};

// The reported bug: set an avatar, look at a chat that is already on screen, and it still
// shows the old one. Two routes in: this browser's own admin edit, and an edit made in some
// other browser — which this page can only learn of from a poll.
const live = async () => {
  let out = ' before=' + (await chat());
  // This browser: edit Ben in the admin dialog, over the open thread.
  click($('#admin-btn'));                                    await sleep(800);
  click($('.admin-group[data-group="ai"]'));                 await sleep(1200);
  const ben = rows('admin-ai-list').find(tr => tr.textContent.includes('Ben'));
  click(ben.querySelector('.btn-secondary'));               await sleep(1200);
  click($('#ai-f-avatar-toggle'));                           await sleep(200);
  click($('#ai-f-avatar-grid [data-avatar="fox"]'));         await sleep(200);
  click($('#ai-f-save-btn'));                                await sleep(1500);
  click($('#admin-lightbox-close-btn'));                     await sleep(500);
  out += ' here=' + (await chat());
  // Another browser: a plain fetch, so none of this page's own code knows it happened.
  const list = await (await fetch('api.php?action=admin_get_ai_users')).json();
  const ann  = list.data.find(u => u.name === 'Ann');
  const fd = new FormData();
  fd.append('uid', String(ann.uid)); fd.append('name', 'Ann'); fd.append('role', 'editor'); fd.append('spaces', 'null');
  fd.append('ai_config', JSON.stringify({ connection_id: ann.ai_config.connection_id, model: 'gpt-a', avatar: 'cat' }));
  await fetch('api.php?action=admin_save_ai_user', { method: 'POST', body: fd });
  await sleep(9000);                                          // one idle chat poll is 5 s
  out += ' elsewhere=' + (await chat());
  return out;
};

setTimeout(async () => {
  try {
    const mode = new URLSearchParams(location.search).get('probe');
    if (mode === 'live') { report(await live()); return; }
    report(mode === 'chat' ? await chat() : await admin());
  } catch (e) {
    report(' fatal=' + (e && e.message || e));
  }
}, 4000);
</script>
</body>"""
assert s.count('</body>') == 1
io.open(p, 'w', encoding='utf-8', newline='').write(s.replace('</body>', probe))
PY

PORT="${WIKI_URL##*:}"
kill "$WIKI_PID" 2>/dev/null; wait "$WIKI_PID" 2>/dev/null
( cd "$WIKI_APP" && exec php -d "session.save_path=$WIKI_ROOT/sessions" \
    -S "127.0.0.1:$PORT" __router.php ) > "$WIKI_ROOT/router.log" 2>&1 &
WIKI_PID=$!
i=0
until curl -sf --max-time 2 "$WIKI_URL/api.php?action=ping" > /dev/null 2>&1; do
    i=$((i + 1)); [ $i -gt 100 ] && { echo "router did not start" >&2; exit 1; }
    sleep 0.1
done

run() {  # run <query>
    "$CHROME" --headless=new --disable-gpu --no-sandbox --window-size=1280,900 \
        --virtual-time-budget=60000 \
        --dump-dom "$WIKI_URL/index.php?$1" > "$WIKI_ROOT/dom.html" 2>/dev/null
    PROBE=$(grep -o '<title>PROBE[^<]*</title>' "$WIKI_ROOT/dom.html" \
            | python3 -c 'import html,sys; sys.stdout.write(html.unescape(sys.stdin.read()))' || true)
    [ -n "$PROBE" ] || _fail "the page never reported (probe did not run)" "$1"
    assert_not_contains "the probe ran without throwing" 'fatal' "$PROBE"
}

section 'the LLM Providers tab lists what the migration made'
run 'probe=admin'
assert_contains "two providers"                   'providers=2'              "$PROBE"
assert_contains "named after their type"          'names=Anthropic+OpenAI'   "$PROBE"
assert_contains "each with who uses it"           'usedby=Ann+Ben'           "$PROBE"

section 'the AI user form names a provider'
assert_contains "the list shows the provider"     'listconn=OpenAI'          "$PROBE"
assert_contains "a provider select, preselected"  'select=2/set'             "$PROBE"
assert_contains "no key box on the AI user"       'keybox=gone'              "$PROBE"
assert_contains "no URL box either"               'urlbox=gone'              "$PROBE"
assert_contains "the manage link goes to the tab" 'manage=went'              "$PROBE"

section 'the avatar picker'
assert_contains "opens with the default plus 100" 'grid=open/101'            "$PROBE"
assert_contains "a pick reaches the saved field"  'picked=owl'               "$PROBE"
assert_contains "and the preview"                 'preview=avatars/owl.svg'  "$PROBE"
assert_contains "and closes the grid"             'closed=true'              "$PROBE"
assert_contains "the icons actually load"         'loaded=true'              "$PROBE"
assert_contains "the list shows it after saving"  'listavatar=avatars/owl.svg' "$PROBE"
assert_eq "saved to the AI user"                  'owl' \
    "$(python3 -c "import json;print([u for u in json.load(open('$WIKI_SYS/users.json'))['users'] if u['name']=='Ann'][0]['ai_config'].get('avatar'))")"

section 'a provider can be added from the tab'
assert_contains "three after saving one"          'after=3'                  "$PROBE"

section 'chat draws the chosen avatar, and only that one'
CHAT_ID=$(python3 -c 'import json,sys
ix = json.load(open(sys.argv[1]))
print(next(k for k, v in ix.items() if v.get("path") == "Talk.chat"))' "$WIKI_PAGES/Main/index.json")
run "pageid=$CHAT_ID&space=Main&probe=chat"
assert_contains "Ann has her owl"                 'ann=img:avatars/owl.svg'  "$PROBE"
assert_contains "Ben keeps the android"           'ben=glyph'                "$PROBE"

section 'a chat already on screen follows an avatar change'
run "pageid=$CHAT_ID&space=Main&probe=live"
assert_contains "starts as it was"                'before= ann=img:avatars/owl.svg ben=glyph' "$PROBE"
assert_contains "an edit in this browser shows at once" 'here= ann=img:avatars/owl.svg ben=img:avatars/fox.svg' "$PROBE"
assert_contains "an edit elsewhere shows on the next poll" 'elsewhere= ann=img:avatars/cat.svg' "$PROBE"

printf '\n'
exit $(( ASSERT_FAIL > 0 ))
