#!/usr/bin/env bash
# Astucia Wiki — Copyright (C) 2026 Mads Rotwitt
# Free software under the GNU GPL v3 or later. See LICENSE for the full notice,
# or <https://www.gnu.org/licenses/>. Distributed WITHOUT ANY WARRANTY.
#
# My Mentions in a lightbox, and the page controls a takeover has to put away.
#
# Two changes, one suite, because they are two halves of the same problem: a view that
# replaces the main area inherits the header of the page it replaced.
#
#  - **The list is a dialog now.** Glancing at who had named you used to cost you the
#    page you were reading. The assertion is not that a dialog appears — it is that the
#    page underneath is still there, by name, while the dialog is up and after it closes.
#  - **A results list puts the page's controls away.** Search still takes over the main
#    area, and its list of controls to hide was three short: the chat settings gear and
#    the knowledge-graph button survived into it, still wired to the page you had left.
#    Driven from a `.chat` page, because the gear is only ever visible on one — a test
#    starting from Markdown would find it hidden and pass without exercising anything.
#
# Neither has an HTTP surface: nothing is written and no endpoint is called that a
# black-box test could watch. What is being measured is which elements are on screen.
#
# The session is established in a headless run of its own and picked up by the next
# through a shared profile; see tests/attention_ui.test.sh, where the same trick and the
# reason for it are written down.
#
# Chrome is not a test dependency — no chrome means skip, not fail.

set -uo pipefail
cd "$(dirname "$0")"
. lib/assert.sh
. lib/fixture.sh

CHROME=""
for c in google-chrome chromium chromium-browser; do
    command -v "$c" >/dev/null 2>&1 && { CHROME="$c"; break; }
done
if [ -z "$CHROME" ]; then
    printf '  %s\n' "$(_dim 'skipped — no chrome/chromium on PATH')"
    exit 0
fi

fixture_start otp || exit 1
trap fixture_stop EXIT

fixture_space Main
fixture_users "{\"users\":[
  {\"uid\":1,\"sub\":\"s1\",\"name\":\"Admin\",\"role\":\"admin\",\"auth\":\"oidc\"},
  {\"uid\":2,\"sub\":\"s2\",\"name\":\"Ed\",\"role\":\"editor\",\"auth\":\"oidc\",\"lastLogin\":$(( $(date +%s) - 3600 ))}]}"

fixture_page 'Main/Report.md' '# Report

Some prose to search for: kingfisher'
fixture_page 'Main/Brief.md' '# Brief

@Ed can you take this one'
printf '{"topic":"Talk","nextMessageId":2,"messages":[{"id":1,"uid":1,"name":"Admin","text":"kingfisher","timestamp":"%s"}]}' \
    "$(date '+%Y-%m-%d %H:%M:%S')" > "$WIKI_PAGES/Main/Talk.chat"

curl -s "$WIKI_URL/api.php?action=list_spaces" > /dev/null
curl -s "$WIKI_URL/api.php?action=indexfiles&space=Main" > /dev/null

page_id() {
    python3 -c 'import json,sys
ix = json.load(open(sys.argv[1]))
print(next(k for k, v in ix.items() if v.get("path") == sys.argv[2]))' \
        "$WIKI_PAGES/Main/index.json" "$1"
}

cat > "$WIKI_APP/__router.php" <<'R'
<?php
// GENERATED BY tests/mentions_ui.test.sh — never part of a release.
$p = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
$f = __DIR__ . $p;
if ($p !== '/' && is_file($f)) {
    $e = pathinfo($f, PATHINFO_EXTENSION);
    if ($e === 'js')  { header('Content-Type: text/javascript'); readfile($f); return true; }
    if ($e === 'css') { header('Content-Type: text/css');        readfile($f); return true; }
    if ($e === 'ico') { header('Content-Type: image/x-icon');    readfile($f); return true; }
    return false;
}
return false;
R

python3 - "$WIKI_APP/index.php" <<'PY'
import io, sys
p = sys.argv[1]
s = io.open(p, encoding='utf-8', newline='').read()
# No backslashes in here: this lives in a Python heredoc inside a shell script, and a
# parse error would take the whole module down silently.
probe = """<script type="module">
const sleep = (ms) => new Promise(r => setTimeout(r, ms));
const shown = (id) => {
  const el = document.getElementById(id);
  if (!el) return 'absent';
  return el.classList.contains('hidden') ? 'hidden' : 'shown';
};
const title  = () => (document.getElementById('current-page-title')?.textContent || '').trim();
const dialog = () => document.getElementById('confirm-modal')?.classList.contains('hidden')
  ? 'shut' : 'open';
const rows   = () => document.querySelectorAll('#confirm-modal-message .sr-card').length;

window.addEventListener('error', e => {
  document.documentElement.setAttribute('data-probe', 'fatal=' + e.message); });
window.addEventListener('unhandledrejection', e => {
  document.documentElement.setAttribute('data-probe',
    'fatal=' + (e.reason && e.reason.message || e.reason)); });

setTimeout(async () => {
  try {
    let out = '';
    const mode = new URLSearchParams(location.search).get('mode');

    if (mode === 'dialog') {
      // On a page, reading it. The dialog must not cost you that.
      out += ' page=' + title() + '/viewer:' + shown('viewer-container');
      document.getElementById('mentions-btn').click();
      await sleep(1200);
      out += ' open=' + dialog() + '/rows:' + rows()
           + '/view:' + (document.querySelector('#confirm-modal-message .mentions-view')
                          ? 'yes' : 'no');
      // The whole point: the page is still underneath, by name.
      out += ' behind=' + title() + '/viewer:' + shown('viewer-container');
      document.getElementById('confirm-modal-ok').click();
      await sleep(400);
      out += ' closed=' + dialog() + '/still=' + title()
           + '/viewer:' + shown('viewer-container');
    }

    if (mode === 'takeover') {
      // A chat page: the settings gear belongs to this thread and is on screen.
      out += ' chat=' + title()
           + '/gear:' + shown('chat-topic-btn')
           + '/graph:' + shown('graph-focus-btn');
      // A search takes over the main area, and has to take the page's controls with it.
      document.getElementById('search-query-input').value = 'kingfisher';
      document.getElementById('search-query-btn').click();
      await sleep(1500);
      out += ' results=' + (document.querySelector('.search-results') ? 'yes' : 'no')
           + '/gear:' + shown('chat-topic-btn')
           + '/graph:' + shown('graph-focus-btn')
           + '/find:' + shown('search-btn')
           + '/git:' + shown('git-history-btn');
    }
    document.documentElement.setAttribute('data-probe', out);
  } catch (e) {
    document.documentElement.setAttribute('data-probe', 'fatal=' + (e && e.message || e));
  }
}, 4000);
</script>
</body>"""
assert s.count('</body>') == 1
io.open(p, 'w', encoding='utf-8', newline='').write(s.replace('</body>', probe))
PY

PORT="${WIKI_URL##*:}"
kill "$WIKI_PID" 2>/dev/null; wait "$WIKI_PID" 2>/dev/null
( cd "$WIKI_APP" && exec php -d "session.save_path=$WIKI_ROOT/sessions" \
    -d "session.cookie_lifetime=3600" \
    -S "127.0.0.1:$PORT" __router.php ) > "$WIKI_ROOT/router.log" 2>&1 &
WIKI_PID=$!
i=0
until curl -sf --max-time 2 "$WIKI_URL/api.php?action=ping" > /dev/null 2>&1; do
    i=$((i + 1)); [ $i -gt 100 ] && { echo "router did not start" >&2; exit 1; }
    sleep 0.1
done

PROFILE="$WIKI_ROOT/chrome-profile"
chrome() {
    "$CHROME" --headless=new --disable-gpu --no-sandbox --window-size=1280,900 \
        --user-data-dir="$PROFILE" --virtual-time-budget=30000 \
        --dump-dom "$1" 2>/dev/null
}
chrome "$WIKI_URL/__test_login.php?uid=2&sub=s2&name=Ed&role=editor" > /dev/null

# visit <space-relative page> <probe mode>
visit() {
    chrome "$WIKI_URL/index.php?pageid=$(page_id "$1")&space=Main&mode=$2" > "$WIKI_ROOT/dom.html"
    PROBE=$(grep -o 'data-probe="[^"]*"' "$WIKI_ROOT/dom.html" \
            | python3 -c 'import html,sys; sys.stdout.write(html.unescape(sys.stdin.read()))' || true)
    [ -n "$PROBE" ] || _fail "the page never reported (probe did not run)" "page $1"
    assert_not_contains "the probe ran without throwing" 'fatal' "$PROBE"
}

visit Report.md dialog

section 'the list opens over the page, not instead of it'
assert_contains "a page is open to begin with"  'page=Report/viewer:shown' "$PROBE"
assert_contains "the dialog opened"             'open=open'                "$PROBE"
assert_contains "  with the mention in it"      'rows:1'                   "$PROBE"
assert_contains "  in its own wrapper"          'view:yes'                 "$PROBE"
# The reason for the change, stated as one assertion: the page you were reading is still
# the page you are on while the list is up.
assert_contains "the page is still underneath"  'behind=Report/viewer:shown' "$PROBE"

section 'and closing it leaves you exactly where you were'
assert_contains "the dialog closed"             'closed=shut'              "$PROBE"
assert_contains "  on the same page"            'still=Report'             "$PROBE"
assert_contains "  still showing it"            'still=Report/viewer:shown' "$PROBE"

visit Talk.chat takeover

section 'a view that does take over puts the page controls away'
# The positive control first: the gear is genuinely on screen before the search, or the
# assertions after it would pass against a button that was never visible.
assert_contains "a chat page has its settings gear" 'gear:shown'  "$PROBE"
assert_contains "  and the graph button"            'graph:shown' "$PROBE"
assert_contains "the search results are up"         'results=yes' "$PROBE"
assert_contains "  the gear went with the page"     'results=yes/gear:hidden' "$PROBE"
assert_contains "  and the graph button"            'graph:hidden' "$PROBE"
assert_contains "  and search-and-replace"          'find:hidden'  "$PROBE"
assert_contains "  and version history"             'git:hidden'   "$PROBE"
# `share-btn` is *absent* here rather than hidden — index.php only renders it when mail
# is configured, which the fixture does not do. It is in the shared list all the same;
# hidePageControls() uses optional chaining for exactly this kind of conditional control.

printf '\n'
exit $(( ASSERT_FAIL > 0 ))
