#!/usr/bin/env bash
# Astucia Wiki — Copyright (C) 2026 Mads Rotwitt
# Free software under the GNU GPL v3 or later. See LICENSE for the full notice,
# or <https://www.gnu.org/licenses/>. Distributed WITHOUT ANY WARRANTY.
#
# The mention type-ahead completes on a keystroke and never on a backspace.
#
# `autoPick()` takes the last remaining match as soon as one is left, which is what makes
# "@A" become "@Alice " in one keystroke. It fired on *every* input event, so the
# completion could not be undone: backspacing over "@Alice " leaves "@Alice", which still
# has exactly one match, so the next event put the name straight back. Every keystroke
# that shortened it restored it, and the mention could not be removed at all — reported
# as "I get halfway back and then it autofills again".
#
# A browser suite because the whole thing is a `keydown`/`input` conversation with a
# textarea; the server is never asked anything and no HTTP assertion can see it. The edits
# are dispatched as real `InputEvent`s carrying the `inputType` a browser would set —
# `insertText` and `deleteContentBackward` — which is the signal the fix reads, so a probe
# that faked them with a plain Event would prove nothing.
#
# Both composers are driven. They are two near-identical copies of the type-ahead (the
# main chat view and the page-chat panel), so a fix applied to one is exactly the shape of
# bug this repo keeps finding.
#
# Chrome is not a test dependency — no chrome means skip, not fail.

set -uo pipefail
cd "$(dirname "$0")"
. lib/assert.sh
. lib/fixture.sh

CHROME=""
for c in google-chrome chromium chromium-browser; do
    command -v "$c" >/dev/null 2>&1 && { CHROME="$c"; break; }
done
if [ -z "$CHROME" ]; then
    printf '  %s\n' "$(_dim 'skipped — no chrome/chromium on PATH')"
    exit 0
fi

fixture_start otp || exit 1
trap fixture_stop EXIT

fixture_space Main
# Exactly one person whose name starts with "A", so "@A" has one match and completes.
# Ed is the one logged in; the initials must not collide or "@A" would have two.
fixture_users '{"users":[
  {"uid":2,"sub":"s2","name":"Ed","role":"editor","auth":"oidc"},
  {"uid":3,"sub":"s3","name":"Alice","role":"editor","auth":"oidc"}]}'

fixture_page 'Main/Report.md' '# Report'
printf '{"topic":"Talk","nextMessageId":1,"messages":[]}' > "$WIKI_PAGES/Main/Talk.chat"
printf '{"topic":"Report","nextMessageId":1,"messages":[]}' > "$WIKI_PAGES/Main/Report.chat"

curl -s "$WIKI_URL/api.php?action=list_spaces" > /dev/null
curl -s "$WIKI_URL/api.php?action=indexfiles&space=Main" > /dev/null

page_id() {
    python3 -c 'import json,sys
ix = json.load(open(sys.argv[1]))
print(next(k for k, v in ix.items() if v.get("path") == sys.argv[2]))' \
        "$WIKI_PAGES/Main/index.json" "$1"
}

cat > "$WIKI_APP/__router.php" <<'R'
<?php
// GENERATED BY tests/mention_autocomplete_ui.test.sh — never part of a release.
$p = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
$f = __DIR__ . $p;
if ($p !== '/' && is_file($f)) {
    $e = pathinfo($f, PATHINFO_EXTENSION);
    if ($e === 'js')  { header('Content-Type: text/javascript'); readfile($f); return true; }
    if ($e === 'css') { header('Content-Type: text/css');        readfile($f); return true; }
    if ($e === 'ico') { header('Content-Type: image/x-icon');    readfile($f); return true; }
    return false;
}
return false;
R

python3 - "$WIKI_APP/index.php" <<'PY'
import io, sys
p = sys.argv[1]
s = io.open(p, encoding='utf-8', newline='').read()
# No backslashes in here: this lives in a Python heredoc inside a shell script, and a
# parse error would take the whole module down silently.
probe = """<script type="module">
const sleep = (ms) => new Promise(r => setTimeout(r, ms));
const report = (v) => document.documentElement.setAttribute('data-probe', v);

// Typing and backspacing as a browser reports them. The `inputType` is the whole point:
// it is what tells the handler an edit was an insertion rather than a deletion, so a
// plain Event('input') here would exercise a path no real keyboard produces.
const type = async (ta, ch) => {
  const p = ta.selectionStart;
  ta.value = ta.value.slice(0, p) + ch + ta.value.slice(p);
  ta.selectionStart = ta.selectionEnd = p + ch.length;
  ta.dispatchEvent(new InputEvent('input', { bubbles: true, inputType: 'insertText', data: ch }));
  await sleep(250);
};
const backspace = async (ta) => {
  const p = ta.selectionStart;
  if (p === 0) return;
  ta.value = ta.value.slice(0, p - 1) + ta.value.slice(p);
  ta.selectionStart = ta.selectionEnd = p - 1;
  ta.dispatchEvent(new InputEvent('input', { bubbles: true, inputType: 'deleteContentBackward' }));
  await sleep(250);
};
const popupShown = (id) => {
  const el = document.getElementById(id);
  return el && !el.classList.contains('hidden') ? 'shown' : 'hidden';
};

window.addEventListener('error', e => report('fatal=' + e.message));
window.addEventListener('unhandledrejection',
    e => report('fatal=' + (e.reason && e.reason.message || e.reason)));

// Drive one composer all the way through, and report what its box held at each step.
const run = async (taId, popId, label) => {
  const ta = document.getElementById(taId);
  if (!ta) return ' ' + label + '=absent';
  ta.focus();
  ta.value = '';
  let out = '';
  // Typing completes: one match left, so the name is taken. The positive control for
  // everything after it — a fix that simply switched completion off would pass every
  // deletion assertion below and fail this one.
  await type(ta, '@');
  await type(ta, 'A');
  out += ' ' + label + '.typed=[' + ta.value + ']';
  // Now take it back, one keystroke at a time. Before the fix the first of these was
  // undone immediately and the value never left "@Alice ".
  await backspace(ta);
  out += ' ' + label + '.b1=[' + ta.value + ']';
  await backspace(ta);
  out += ' ' + label + '.b2=[' + ta.value + ']';
  // The popup is still offered on the way back; the help is wanted, the insertion is not.
  out += ' ' + label + '.pop=' + popupShown(popId);
  for (let i = 0; i < 4; i++) await backspace(ta);
  out += ' ' + label + '.b6=[' + ta.value + ']';
  // And all the way to empty, which is the thing that was impossible.
  for (let i = 0; i < 4; i++) await backspace(ta);
  out += ' ' + label + '.gone=[' + ta.value + ']';
  // Typing again still completes, so the deletion did not leave it switched off.
  await type(ta, '@');
  await type(ta, 'A');
  out += ' ' + label + '.again=[' + ta.value + ']';
  return out;
};

setTimeout(async () => {
  try {
    let out = '';
    const mode = new URLSearchParams(location.search).get('mode');
    if (mode === 'chat') {
      out += await run('chat-input', 'chat-mention-popup', 'chat');
    } else {
      // The panel beside a page: its composer only exists once the panel is open.
      document.getElementById('page-chat-btn')?.click();
      await sleep(1500);
      out += await run('pc-input', 'pc-mention-popup', 'panel');
    }
    report(out);
  } catch (e) {
    report('fatal=' + (e && e.message || e));
  }
}, 4000);
</script>
</body>"""
assert s.count('</body>') == 1
io.open(p, 'w', encoding='utf-8', newline='').write(s.replace('</body>', probe))
PY

PORT="${WIKI_URL##*:}"
kill "$WIKI_PID" 2>/dev/null; wait "$WIKI_PID" 2>/dev/null
( cd "$WIKI_APP" && exec php -d "session.save_path=$WIKI_ROOT/sessions" \
    -d "session.cookie_lifetime=3600" \
    -S "127.0.0.1:$PORT" __router.php ) > "$WIKI_ROOT/router.log" 2>&1 &
WIKI_PID=$!
i=0
until curl -sf --max-time 2 "$WIKI_URL/api.php?action=ping" > /dev/null 2>&1; do
    i=$((i + 1)); [ $i -gt 100 ] && { echo "router did not start" >&2; exit 1; }
    sleep 0.1
done

PROFILE="$WIKI_ROOT/chrome-profile"
chrome() {
    "$CHROME" --headless=new --disable-gpu --no-sandbox --window-size=1280,900 \
        --user-data-dir="$PROFILE" --virtual-time-budget=40000 \
        --dump-dom "$1" 2>/dev/null
}
chrome "$WIKI_URL/__test_login.php?uid=2&sub=s2&name=Ed&role=editor" > /dev/null

visit() {
    chrome "$WIKI_URL/index.php?pageid=$(page_id "$1")&space=Main&mode=$2" > "$WIKI_ROOT/dom.html"
    PROBE=$(grep -o 'data-probe="[^"]*"' "$WIKI_ROOT/dom.html" \
            | python3 -c 'import html,sys; sys.stdout.write(html.unescape(sys.stdin.read()))' || true)
    [ -n "$PROBE" ] || _fail "the page never reported (probe did not run)" "page $1"
    assert_not_contains "the probe ran without throwing" 'fatal' "$PROBE"
}

visit Talk.chat chat

section 'the completion still happens on a keystroke'
assert_contains "one match left, so the name is taken" 'chat.typed=[@Alice ]' "$PROBE"

section 'and a backspace takes it back instead of restoring it'
# The bug, exactly: "@Alice " → "@Alice" → completed straight back to "@Alice ".
assert_contains "the trailing space goes"   'chat.b1=[@Alice]' "$PROBE"
assert_contains "  and then the letters"    'chat.b2=[@Alic]'  "$PROBE"
assert_contains "  all the way down"        'chat.b6=[@]'      "$PROBE"
assert_contains "  and out"                 'chat.gone=[]'     "$PROBE"

section 'the popup still helps while deleting'
# Only the *insertion* is suppressed. Closing the list as well would be a second,
# unrelated loss.
assert_contains "the list is still offered" 'chat.pop=shown'   "$PROBE"

section 'and the feature is not left switched off'
# The other way to "fix" this is to delete autoPick, which passes every assertion above.
assert_contains "typing completes again"    'chat.again=[@Alice ]' "$PROBE"

visit Report.md panel

section 'the page-chat panel has its own copy, and the same rules'
assert_contains "it completes on a keystroke"  'panel.typed=[@Alice ]' "$PROBE"
assert_contains "a backspace takes it back"    'panel.b1=[@Alice]'     "$PROBE"
assert_contains "  all the way out"            'panel.gone=[]'         "$PROBE"
assert_contains "and it still completes after" 'panel.again=[@Alice ]' "$PROBE"

printf '\n'
exit $(( ASSERT_FAIL > 0 ))
