#!/usr/bin/env bash
# Astucia Wiki — Copyright (C) 2026 Mads Rotwitt
# Free software under the GNU GPL v3 or later. See LICENSE for the full notice,
# or <https://www.gnu.org/licenses/>. Distributed WITHOUT ANY WARRANTY.
#
# The Recent and Saved panes name a page the way the rest of the wiki does.
#
# Both rows are drawn from a stored `{ path }` rather than from the open page, so
# modules/nav answered "what kind of file is this" from a list of its own — and that list
# knew `.drawio`, `.list` and `.chat` only. A data page or a saved search therefore
# appeared under the generic page icon with its extension still on the name, three
# centimetres from a file tree showing the correct icon and a bare name for the same file.
#
# It is a browser suite because there is nothing else to look at: the panes are built in
# the DOM from localStorage, no endpoint is involved, and the evidence is which SVG ended
# up in a `<span>`. Each icon is compared against the page header's, which is drawn from
# the shared table for the page actually open — so the assertion is "these two agree"
# rather than a copy of the markup that would need updating whenever an icon is redrawn.
#
# Chrome is not a test dependency — no chrome means skip, not fail.

set -uo pipefail
cd "$(dirname "$0")"
. lib/assert.sh
. lib/fixture.sh

CHROME=""
for c in google-chrome chromium chromium-browser; do
    command -v "$c" >/dev/null 2>&1 && { CHROME="$c"; break; }
done
if [ -z "$CHROME" ]; then
    printf '  %s\n' "$(_dim 'skipped — no chrome/chromium on PATH')"
    exit 0
fi

fixture_start off || exit 1
trap fixture_stop EXIT

fixture_space Main
fixture_page 'Main/Notes.md'    '# Notes'
fixture_page 'Main/Data.json'   '{"rows": []}'
fixture_page 'Main/Query.search' '{"terms": "x"}'
fixture_page 'Main/Plan.list'   '{"columns": [], "rows": []}'

curl -s "$WIKI_URL/api.php?action=list_spaces" > /dev/null
curl -s "$WIKI_URL/api.php?action=indexfiles&space=Main" > /dev/null

page_id() {
    python3 -c 'import json,sys
ix = json.load(open(sys.argv[1]))
print(next(k for k, v in ix.items() if v.get("path") == sys.argv[2]))' \
        "$WIKI_PAGES/Main/index.json" "$1"
}

cat > "$WIKI_APP/__router.php" <<'R'
<?php
// GENERATED BY tests/nav_panes_ui.test.sh — never part of a release.
$p = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
$f = __DIR__ . $p;
if ($p !== '/' && is_file($f)) {
    $e = pathinfo($f, PATHINFO_EXTENSION);
    if ($e === 'js')  { header('Content-Type: text/javascript'); readfile($f); return true; }
    if ($e === 'css') { header('Content-Type: text/css');        readfile($f); return true; }
    return false;
}
return false;
R

python3 - "$WIKI_APP/index.php" <<'PY'
import io, sys
p = sys.argv[1]
s = io.open(p, encoding='utf-8', newline='').read()
# Reported through document.title, which --dump-dom returns without a DevTools
# connection. No backslashes in here: this lives in a Python heredoc inside a shell
# script, and a parse error would take the whole module down silently.
probe = """<script type="module">
const sleep = (ms) => new Promise(r => setTimeout(r, ms));
// The header, drawn by page_view for the page that is actually open: the reference the
// two panes are measured against.
const headIcon = () =>
    document.getElementById('current-page-title')?.querySelector('svg')?.outerHTML || '';
const headName = () =>
    (document.getElementById('current-page-title')?.textContent || '').trim();
// The pane row for this page. Rows carry the path as their tooltip.
const row = (pane, path) => Array.from(
        document.querySelectorAll('#' + pane + '-pane .nav-pane-item'))
    .find(li => li.title === path);
const describe = (pane, path) => {
  const li = row(pane, path);
  if (!li) return 'missing';
  const icon = li.querySelector('.nav-pane-item-icon')?.innerHTML.trim();
  const name = li.querySelector('.nav-pane-item-name')?.textContent || '';
  return name + '/' + (icon === headIcon() ? 'same' : 'differs');
};

window.addEventListener('error', e => { document.title = 'PROBE fatal=' + e.message; });
window.addEventListener('unhandledrejection',
    e => { document.title = 'PROBE fatal=' + (e.reason && e.reason.message || e.reason); });

setTimeout(async () => {
  try {
    const path = new URLSearchParams(location.search).get('rel');
    let out = ' head=' + headName() + '/icon:' + (headIcon() ? 'yes' : 'no');
    // Opening the page is what writes the Recent row.
    out += ' recent=' + describe('recent', path);
    // Starring it is what writes the Saved one.
    document.getElementById('favorite-btn').click();
    await sleep(300);
    out += ' saved=' + describe('saved', path);
    document.title = 'PROBE' + out;
  } catch (e) {
    document.title = 'PROBE fatal=' + (e && e.message || e);
  }
}, 4000);
</script>
</body>"""
assert s.count('</body>') == 1
io.open(p, 'w', encoding='utf-8', newline='').write(s.replace('</body>', probe))
PY

PORT="${WIKI_URL##*:}"
kill "$WIKI_PID" 2>/dev/null; wait "$WIKI_PID" 2>/dev/null
( cd "$WIKI_APP" && exec php -d "session.save_path=$WIKI_ROOT/sessions" \
    -S "127.0.0.1:$PORT" __router.php ) > "$WIKI_ROOT/router.log" 2>&1 &
WIKI_PID=$!
i=0
until curl -sf --max-time 2 "$WIKI_URL/api.php?action=ping" > /dev/null 2>&1; do
    i=$((i + 1)); [ $i -gt 100 ] && { echo "router did not start" >&2; exit 1; }
    sleep 0.1
done

# visit <space-relative page> — opens it, then stars it.
visit() {
    "$CHROME" --headless=new --disable-gpu --no-sandbox --window-size=1280,900 \
        --virtual-time-budget=30000 \
        --dump-dom "$WIKI_URL/index.php?pageid=$(page_id "$1")&space=Main&rel=$1" \
        > "$WIKI_ROOT/dom.html" 2>/dev/null
    PROBE=$(grep -o '<title>PROBE[^<]*</title>' "$WIKI_ROOT/dom.html" \
            | python3 -c 'import html,sys; sys.stdout.write(html.unescape(sys.stdin.read()))' || true)
    [ -n "$PROBE" ] || _fail "the page never reported (probe did not run)" "page $1"
    assert_not_contains "the probe ran without throwing" 'fatal' "$PROBE"
}

# Each page is loaded in its own browser run, so localStorage is not shared between them
# and the row being measured is the only one there. The header is asserted first in each:
# it is the reference the pane rows are compared against, and a broken reference would
# make "they agree" pass for the wrong reason.

section 'a data page'
visit Data.json
assert_contains "the header has it right"     'head=Data/icon:yes' "$PROBE"
assert_contains "Recent names it the same"    'recent=Data/same'   "$PROBE"
assert_contains "Saved names it the same"     'saved=Data/same'    "$PROBE"

section 'a saved search'
visit Query.search
assert_contains "the header has it right"     'head=Query/icon:yes' "$PROBE"
assert_contains "Recent names it the same"    'recent=Query/same'   "$PROBE"
assert_contains "Saved names it the same"     'saved=Query/same'    "$PROBE"

section 'the types that already worked still do'
# The positive controls. A pathIcon() that returned the header's icon whatever it was
# handed would satisfy every assertion above; these two only pass if the table is really
# being consulted, since a list page and a Markdown page must not share an icon.
visit Plan.list
assert_contains "a list page"                 'recent=Plan/same'    "$PROBE"
assert_contains "  and in Saved"              'saved=Plan/same'     "$PROBE"
visit Notes.md
assert_contains "a Markdown page"             'recent=Notes/same'   "$PROBE"
assert_contains "  and in Saved"              'saved=Notes/same'    "$PROBE"

printf '\n'
exit $(( ASSERT_FAIL > 0 ))
