#!/usr/bin/env bash
# Astucia Wiki — Copyright (C) 2026 Mads Rotwitt
# Free software under the GNU GPL v3 or later. See LICENSE for the full notice,
# or <https://www.gnu.org/licenses/>. Distributed WITHOUT ANY WARRANTY.
#
# New → JSON Data. `.json` was a supported page type that only an AI tool or a file copied
# into PAGES_DIR could create. It now goes through `create_file` like a Markdown page, and
# starts as `{"field": "value"}` rather than empty — an empty file is not JSON, so the
# viewer would open it as an error.
#
# The HTTP half holds the starter content; the browser half drives the folder listing's
# "New …" menu, which clones the sidebar's rows — so it checks both menus at once, and that
# the clone actually reaches the sidebar's handler. Chrome missing skips that half.

set -uo pipefail
cd "$(dirname "$0")"
. lib/assert.sh
. lib/fixture.sh

fixture_start off || exit 1
trap fixture_stop EXIT
fixture_space Main
fixture_page 'Main/templates/default.md' '# A Markdown template'
curl -s "$WIKI_URL/api.php?action=list_spaces" > /dev/null
J=$WIKI_ROOT/jar

section 'create_file writes a starter object for a .json path'
r=$(post_as "$J" 'api.php?action=create_file&space=Main' 'path=Data.json')
assert_contains "created"                         '"success":true' "$r"
assert_eq "the file is valid JSON with one field" '{"field": "value"}' \
    "$(python3 -c "import json;print(json.dumps(json.load(open('$WIKI_PAGES/Main/Data.json'))))")"
assert_eq "encoded the way save re-encodes it"    "$(printf '{\n    "field": "value"\n}')" "$(cat "$WIKI_PAGES/Main/Data.json")"
assert_contains "indexed like any page"           'Data.json' "$(cat "$WIKI_PAGES/Main/index.json")"
r=$(get_as "$J" 'api.php?action=get&space=Main&file=Data.json')
assert_contains "and readable"                    'field' "$r"

r=$(post_as "$J" 'api.php?action=create_file&space=Main' 'path=Tpl.json&template=default')
assert_not_contains "a Markdown template is not applied" 'A Markdown template' "$(cat "$WIKI_PAGES/Main/Tpl.json")"
r=$(post_as "$J" 'api.php?action=create_file&space=Main' 'path=Data.json')
assert_contains "an existing name is refused"     'already exists' "$r"
assert_eq "and left alone"                        "$(printf '{\n    "field": "value"\n}')" "$(cat "$WIKI_PAGES/Main/Data.json")"
# Positive control: a Markdown page is still a Markdown page.
post_as "$J" 'api.php?action=create_file&space=Main' 'path=Note.md' > /dev/null
assert_eq "a .md page still starts with its title" '# Note' "$(head -1 "$WIKI_PAGES/Main/Note.md")"

CHROME=""
for c in google-chrome chromium chromium-browser; do
    command -v "$c" >/dev/null 2>&1 && { CHROME="$c"; break; }
done
if [ -z "$CHROME" ]; then
    printf '  %s\n' "$(_dim 'browser half skipped — no chrome/chromium on PATH')"
    printf '\n'; exit $(( ASSERT_FAIL > 0 ))
fi

cat > "$WIKI_APP/__router.php" <<'R'
<?php
// GENERATED BY tests/new_json_page.test.sh — never part of a release.
$p = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
$f = __DIR__ . $p;
if ($p !== '/' && is_file($f)) {
    $e = pathinfo($f, PATHINFO_EXTENSION);
    if ($e === 'js')  { header('Content-Type: text/javascript'); readfile($f); return true; }
    if ($e === 'css') { header('Content-Type: text/css');        readfile($f); return true; }
    return false;
}
return false;
R

python3 - "$WIKI_APP/index.php" <<'PY'
import io, sys
p = sys.argv[1]
s = io.open(p, encoding='utf-8', newline='').read()
probe = """<script type="module">
const sleep = (ms) => new Promise(r => setTimeout(r, ms));
const $ = (s) => document.querySelector(s);
const report = (o) => { document.title = 'PROBE' + o; };
window.addEventListener('error', e => report(' fatal=' + e.message));
window.addEventListener('unhandledrejection', e => report(' fatal=' + (e.reason && e.reason.message || e.reason)));
setTimeout(async () => {
  try {
    let out = '';
    const side = $('#dropdown-new-json');
    out += ' sidebar=' + (side ? (side.querySelector('svg') ? 'icon+' : 'noicon+') + side.textContent.trim() : 'missing');
    // The folder listing's menu is built by cloning the sidebar's rows when it opens.
    $('#ff-new-btn').click();                                   await sleep(300);
    const rows = Array.from(document.querySelectorAll('#ff-new-dropdown a'));
    const row = rows.find(a => a.innerHTML === side.innerHTML);
    out += ' listing=' + (row ? 'present' : 'missing') + ' rows=' + rows.length;
    // Choosing it from there names the page and opens it in the data view.
    row.click();                                                await sleep(400);
    $('#input-modal-input').value = 'Budget';
    $('#input-modal-ok').click();                               await sleep(2500);
    out += ' opened=' + ($('#json-view-container').classList.contains('hidden') ? 'no' : 'yes');
    out += ' shows=' + (($('#json-view-content')?.textContent || '').includes('field') ? 'field' : 'nothing');
    report(out);
  } catch (e) { report(' fatal=' + (e && e.message || e)); }
}, 4000);
</script>
</body>"""
assert s.count('</body>') == 1
io.open(p, 'w', encoding='utf-8', newline='').write(s.replace('</body>', probe))
PY

PORT="${WIKI_URL##*:}"
kill "$WIKI_PID" 2>/dev/null; wait "$WIKI_PID" 2>/dev/null
( cd "$WIKI_APP" && exec php -d "session.save_path=$WIKI_ROOT/sessions" \
    -S "127.0.0.1:$PORT" __router.php ) > "$WIKI_ROOT/router.log" 2>&1 &
WIKI_PID=$!
i=0
until curl -sf --max-time 2 "$WIKI_URL/api.php?action=ping" > /dev/null 2>&1; do
    i=$((i + 1)); [ $i -gt 100 ] && { echo "router did not start" >&2; exit 1; }
    sleep 0.1
done

section 'both "New …" menus offer it'
"$CHROME" --headless=new --disable-gpu --no-sandbox --window-size=1280,900 \
    --virtual-time-budget=30000 --dump-dom "$WIKI_URL/index.php?space=Main" > "$WIKI_ROOT/dom.html" 2>/dev/null
PROBE=$(grep -o '<title>PROBE[^<]*</title>' "$WIKI_ROOT/dom.html" \
        | python3 -c 'import html,sys; sys.stdout.write(html.unescape(sys.stdin.read()))' || true)
[ -n "$PROBE" ] || _fail "the page never reported (probe did not run)"
assert_not_contains "the probe ran without throwing" 'fatal'                 "$PROBE"
assert_contains "the sidebar has it, with its icon"  'sidebar=icon+New JSON Data' "$PROBE"
assert_contains "the folder listing's menu too"      'listing=present'       "$PROBE"
assert_contains "eight rows there"                   'rows=8'                "$PROBE"
assert_contains "choosing it opens the data view"    'opened=yes'            "$PROBE"
assert_contains "showing the starter field"          'shows=field'           "$PROBE"
assert_file_exists "and the file is on disk"         "$WIKI_PAGES/Main/Budget.json"

printf '\n'
exit $(( ASSERT_FAIL > 0 ))
