#!/usr/bin/env bash
# Astucia Wiki — Copyright (C) 2026 Mads Rotwitt
# Free software under the GNU GPL v3 or later. See LICENSE for the full notice,
# or <https://www.gnu.org/licenses/>. Distributed WITHOUT ANY WARRANTY.
#
# Switching a page chat between its two presentations.
#
# The same thread can be a panel beside its page or an ordinary page in the main area,
# and until there were swap buttons each was reachable only from where it started. What
# makes this worth a browser suite rather than an HTTP one: **both buttons are pure
# navigation**. Nothing is written, no endpoint is called that a black-box test could
# watch — the entire behaviour is which container ends up on screen, so a handler that
# was never wired, or wired to an element that no longer exists, passes every other kind
# of check while doing nothing at all.
#
# The round trip is asserted in one run, page → panel → page → panel, because each
# direction leaves the state the other one starts from: a dock button that works only
# the first time would pass two separate one-way tests.
#
# It also covers **creating** a thread, which is where the two meet: a page chat is an
# indexed page like any other and has to reach the sidebar at once. It did not — every
# other creator in the wiki calls refreshFileTree() and this one never did — so a new
# thread was invisible until the tree's own poll came round, and `treeEntry()` reads the
# *rendered* tree for a page's id, so until then the expand button opened the thread
# with no id at all. Both are asserted, because the visible half is the one that gets
# reported and the id is the half that quietly breaks `?pageid=` links to it.
#
# Chrome is not a test dependency — no chrome means skip, not fail.

set -uo pipefail
cd "$(dirname "$0")"
. lib/assert.sh
. lib/fixture.sh

CHROME=""
for c in google-chrome chromium chromium-browser; do
    command -v "$c" >/dev/null 2>&1 && { CHROME="$c"; break; }
done
if [ -z "$CHROME" ]; then
    printf '  %s\n' "$(_dim 'skipped — no chrome/chromium on PATH')"
    exit 0
fi

fixture_start off || exit 1
trap fixture_stop EXIT

fixture_space Main
fixture_page 'Main/Report.md' '# Report'
# The thread that belongs to that page, and a standalone one that belongs to nothing.
printf '{"topic":"Report","nextMessageId":2,"messages":[{"id":1,"uid":1,"name":"Ann","text":"beside the page","timestamp":"2026-01-01 10:00:00"}]}' \
    > "$WIKI_PAGES/Main/Report.chat"
printf '{"topic":"Team","nextMessageId":2,"messages":[{"id":1,"uid":1,"name":"Ann","text":"free standing","timestamp":"2026-01-01 10:00:00"}]}' \
    > "$WIKI_PAGES/Main/Team.chat"
# A page with no thread beside it, so opening its panel has to create one.
fixture_page 'Main/Fresh.md' '# Fresh'

curl -s "$WIKI_URL/api.php?action=list_spaces" > /dev/null
curl -s "$WIKI_URL/api.php?action=indexfiles&space=Main" > /dev/null

page_id() {
    python3 -c 'import json,sys
ix = json.load(open(sys.argv[1]))
print(next(k for k, v in ix.items() if v.get("path") == sys.argv[2]))' \
        "$WIKI_PAGES/Main/index.json" "$1"
}

cat > "$WIKI_APP/__router.php" <<'R'
<?php
// GENERATED BY tests/page_chat_swap_ui.test.sh — never part of a release.
$p = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
$f = __DIR__ . $p;
if ($p !== '/' && is_file($f)) {
    $e = pathinfo($f, PATHINFO_EXTENSION);
    if ($e === 'js')  { header('Content-Type: text/javascript'); readfile($f); return true; }
    if ($e === 'css') { header('Content-Type: text/css');        readfile($f); return true; }
    return false;
}
return false;
R

python3 - "$WIKI_APP/index.php" <<'PY'
import io, sys
p = sys.argv[1]
s = io.open(p, encoding='utf-8', newline='').read()
# Reported through document.title, which --dump-dom returns without a DevTools
# connection. No backslashes in here: this lives in a Python heredoc inside a shell
# script, and a parse error would take the whole module down silently.
probe = """<script type="module">
const sleep = (ms) => new Promise(r => setTimeout(r, ms));
const hidden = (id) => {
  const el = document.getElementById(id);
  return el ? (el.classList.contains('hidden') ? 'hidden' : 'shown') : 'absent';
};
const panel = () => document.getElementById('page-chat-panel')?.classList.contains('open')
  ? 'open' : 'closed';
const title = () => (document.getElementById('current-page-title')?.textContent || '').trim();
// Report.md and Report.chat both display as "Report", so the title cannot say which of
// the two is on screen. The container can.
const view = () => document.getElementById('chat-view-container')?.classList.contains('hidden')
  ? 'page' : 'thread';
const click = async (id, ms) => { document.getElementById(id)?.click(); await sleep(ms || 900); };

window.addEventListener('error', e => { document.title = 'PROBE fatal=' + e.message; });
window.addEventListener('unhandledrejection',
    e => { document.title = 'PROBE fatal=' + (e.reason && e.reason.message || e.reason); });

setTimeout(async () => {
  try {
    let out = '';
    const trip = [];
    const stamp = () => trip.push(view() + '-' + panel());
    stamp();
    // On the page: only the open-chat button, and nothing to swap yet.
    out += ' start=' + title() + '/' + view() + '/' + panel()
         + '/chat:' + hidden('page-chat-btn') + '/dock:' + hidden('chat-dock-btn');

    // Page -> panel, the way it already worked.
    await click('page-chat-btn');
    stamp();
    out += ' opened=' + panel() + '/expand:' + (document.getElementById('pc-expand-btn') ? 'yes' : 'no');

    // Panel -> page. The thread becomes the main area, and the swap back appears.
    await click('pc-expand-btn', 1400);
    stamp();
    out += ' expanded=' + title() + '/' + view() + '/' + panel() + '/dock:' + hidden('chat-dock-btn');

    // Page -> panel again, from the main-area view. This is the direction asked for:
    // it has to land on the *page* with the panel open, not merely close something.
    await click('chat-dock-btn', 1600);
    stamp();
    out += ' docked=' + title() + '/' + view() + '/' + panel() + '/dock:' + hidden('chat-dock-btn');

    // Creating a thread from a page that has none. Only reached in the `create` run;
    // the round trip above uses a page whose thread already exists.
    if (new URLSearchParams(location.search).get('probe') === 'create') {
      // Space-relative, like every data-path in the tree — `Fresh.chat`, not
      // `Main/Fresh.chat`. The same trap tabs_ui.test.sh documents for tab paths.
      const treeHas = (p) => document.querySelector('[data-path="' + p + '"]') ? 'yes' : 'no';
      out = ' before=' + treeHas('Fresh.chat');
      await click('page-chat-btn', 600);
      out += ' asked=' + hidden('page-chat-confirm-lightbox');
      await click('pcl-confirm-btn', 2000);
      out += ' panel=' + panel() + ' tree=' + treeHas('Fresh.chat');
      // The consequence of the tree being stale: treeEntry() had no id to give, so the
      // thread opened as a page without one.
      await click('pc-expand-btn', 1600);
      const idEl = document.getElementById('page-id-display');
      const idTxt = (idEl?.textContent || '').trim();
      out += ' opened=' + view() + '/id:' +
             (idEl?.classList.contains('hidden') ? 'hidden'
              : (/^ID: \\d+$/.test(idTxt) ? 'real' : idTxt || 'empty'));
      document.title = 'PROBE' + out;
      return;
    }

    // The journey as one string. The per-step fields above read well in a failure,
    // but each is satisfiable by standing still: with the expand button dead you never
    // leave the page, so "on the page with the panel open" is *already* true when the
    // last step is measured and passes for the wrong reason. A trip that has to change
    // at every stage cannot be satisfied by doing nothing.
    document.title = 'PROBE' + out + ' trip=' + trip.join('>');
  } catch (e) {
    document.title = 'PROBE fatal=' + (e && e.message || e);
  }
}, 4000);
</script>
</body>"""
assert s.count('</body>') == 1
io.open(p, 'w', encoding='utf-8', newline='').write(s.replace('</body>', probe))
PY

PORT="${WIKI_URL##*:}"
kill "$WIKI_PID" 2>/dev/null; wait "$WIKI_PID" 2>/dev/null
( cd "$WIKI_APP" && exec php -d "session.save_path=$WIKI_ROOT/sessions" \
    -S "127.0.0.1:$PORT" __router.php ) > "$WIKI_ROOT/router.log" 2>&1 &
WIKI_PID=$!
i=0
until curl -sf --max-time 2 "$WIKI_URL/api.php?action=ping" > /dev/null 2>&1; do
    i=$((i + 1)); [ $i -gt 100 ] && { echo "router did not start" >&2; exit 1; }
    sleep 0.1
done

load() {
    "$CHROME" --headless=new --disable-gpu --no-sandbox --window-size=1280,900 \
        --virtual-time-budget=30000 \
        --dump-dom "$WIKI_URL/index.php?pageid=$(page_id "$1")&space=Main&probe=${2:-swap}" \
        > "$WIKI_ROOT/dom.html" 2>/dev/null
    PROBE=$(grep -o '<title>PROBE[^<]*</title>' "$WIKI_ROOT/dom.html" \
            | python3 -c 'import html,sys; sys.stdout.write(html.unescape(sys.stdin.read()))' || true)
    [ -n "$PROBE" ] || _fail "the page never reported (probe did not run)" "page $1"
}

load Report.md
assert_not_contains "the probe ran without throwing" 'fatal' "$PROBE"

section 'on a page, only the way in is offered'
assert_contains "the page is open with no panel"   'start=Report/page/closed' "$PROBE"
assert_contains "  the open-chat button is there"  'chat:shown'               "$PROBE"
assert_contains "  and nothing to swap back to"    'start=Report/page/closed/chat:shown/dock:hidden' "$PROBE"

section 'page → panel, then the panel offers the way out'
assert_contains "the panel opened"                 'opened=open'          "$PROBE"
assert_contains "  carrying an open-as-a-page button" 'expand:yes'        "$PROBE"

section 'panel → page: the thread fills the main area'
# The panel closes and the thread is the page you are on — which is also what gives the
# sidebar back, since the panel covers it while open.
assert_contains "the thread is the open page"      'expanded=Report/thread/closed' "$PROBE"
assert_contains "  and the swap back is offered"   'dock:shown'           "$PROBE"

section 'page → panel again, which is the direction that was missing'
# Back on the *page*, panel open — not merely the chat closed. A handler that only
# closed the view would pass a weaker assertion than this one.
assert_contains "it lands on the page, panel open" 'docked=Report/page/open' "$PROBE"
assert_contains "  and the swap button is gone with it" 'dock:hidden'     "$PROBE"
# And the whole journey, which no single standstill satisfies.
assert_contains "the round trip really moved at each step" \
                'trip=page-closed>page-open>thread-closed>page-open' "$PROBE"

section 'a thread that belongs to no page cannot be docked'
# The button's absence is the only thing distinguishing a page chat from a free-standing
# one, so it is asserted rather than assumed.
load Team.chat
assert_not_contains "the probe ran without throwing" 'fatal' "$PROBE"
assert_contains "the standalone thread is open"      'start=Team/thread/closed' "$PROBE"
assert_contains "  with no button to dock it"        'dock:hidden'        "$PROBE"

section 'a thread created from a page reaches the sidebar at once'
load Fresh.md create
assert_not_contains "the probe ran without throwing" 'fatal' "$PROBE"
# The positive control: the page really had no thread, so what the tree gains below is
# the one this run created.
assert_contains "the page starts without one"   'before=no'       "$PROBE"
assert_contains "  and is asked before creating" 'asked=shown'    "$PROBE"
assert_contains "the panel opened"              'panel=open'      "$PROBE"
assert_contains "the tree has it immediately"   'tree=yes'        "$PROBE"
# Not cosmetic: the id comes from the rendered tree, so a stale sidebar means the thread
# opens as a page with nothing in its ID badge.
assert_contains "and it opens as a page"        'opened=thread'   "$PROBE"
assert_contains "  carrying its real page id"   'id:real'         "$PROBE"

printf '\n'
exit $(( ASSERT_FAIL > 0 ))
