#!/usr/bin/env bash
# Astucia Wiki — Copyright (C) 2026 Mads Rotwitt
# Free software under the GNU GPL v3 or later. See LICENSE for the full notice,
# or <https://www.gnu.org/licenses/>. Distributed WITHOUT ANY WARRANTY.
#
# Pasting an image into the editor, in a real browser.
#
# tests/paste_image.test.sh covers the naming contract over HTTP. The half it cannot see
# is the whole client feature: a `paste` listener that has to fire on the right textarea,
# recognise a clipboard bitmap, upload it, and write the link the *server* chose. That
# last one is the interesting failure — a client that composes "image.png" itself looks
# correct until the second paste, when the file on disk is image2.png and the page links
# to somebody else's image. No HTTP assertion can see it.
#
# Mechanics are tests/code_copy_ui.test.sh's: a two-line router (php -S sends no
# Content-Type for .js, which blocks ES modules), a probe injected into index.php that
# drives real controls, and a report read out of document.title.
#
# Chrome is not a test dependency — no chrome means skip, not fail.

set -uo pipefail
cd "$(dirname "$0")"
. lib/assert.sh
. lib/fixture.sh

CHROME=""
for c in google-chrome chromium chromium-browser; do
    command -v "$c" >/dev/null 2>&1 && { CHROME="$c"; break; }
done
if [ -z "$CHROME" ]; then
    printf '  %s\n' "$(_dim 'skipped — no chrome/chromium on PATH')"
    exit 0
fi

fixture_start off || exit 1
trap fixture_stop EXIT

fixture_space Main
fixture_page 'Main/Notes.md' '# Notes'

curl -s "$WIKI_URL/api.php?action=list_spaces" > /dev/null
curl -s "$WIKI_URL/api.php?action=indexfiles&space=Main" > /dev/null

UP=$WIKI_PAGES/Main/Notes.md.uploads

page_id() {
    python3 -c 'import json,sys
ix = json.load(open(sys.argv[1]))
print(next(k for k, v in ix.items() if v.get("path") == sys.argv[2]))' \
        "$WIKI_PAGES/${2:-Main}/index.json" "$1"
}

cat > "$WIKI_APP/__router.php" <<'R'
<?php
// GENERATED BY tests/paste_image_ui.test.sh — never part of a release.
$p = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
$f = __DIR__ . $p;
if ($p !== '/' && is_file($f)) {
    $e = pathinfo($f, PATHINFO_EXTENSION);
    if ($e === 'js')  { header('Content-Type: text/javascript'); readfile($f); return true; }
    if ($e === 'css') { header('Content-Type: text/css');        readfile($f); return true; }
    return false;
}
return false;
R

python3 - "$WIKI_APP/index.php" <<'PY'
import io, sys
p = sys.argv[1]
s = io.open(p, encoding='utf-8', newline='').read()
# ?probe=<what> selects the action; the report goes in document.title, which --dump-dom
# returns without needing a DevTools connection. No backslashes anywhere in here: this
# text lives in a Python heredoc inside a shell script, so one meant for JavaScript would
# have to be doubled, and a parse error takes the whole module down silently.
probe = """<script type="module">
const sleep = (ms) => new Promise(r => setTimeout(r, ms));

// A clipboard carrying a bitmap, as the browser hands one over for a screenshot: a file
// part with an image MIME type and a name nobody chose.
const imageClipboard = (bytes) => {
  const dt = new DataTransfer();
  dt.items.add(new File([bytes], 'image.png', { type: 'image/png' }));
  return dt;
};
const textClipboard = (text) => {
  const dt = new DataTransfer();
  dt.setData('text/plain', text);
  return dt;
};
const paste = (el, dt) => {
  const ev = new ClipboardEvent('paste', { clipboardData: dt, bubbles: true, cancelable: true });
  el.dispatchEvent(ev);
  return ev.defaultPrevented;
};

const enterEditMode = async () => {
  document.getElementById('edit-btn').click();
  await sleep(600);
  const ta = document.getElementById('editor-container');
  ta.focus();
  ta.setSelectionRange(ta.value.length, ta.value.length);
  return ta;
};

window.addEventListener('error', e => { document.title = 'PROBE fatal=' + e.message; });
window.addEventListener('unhandledrejection', e => {
    document.title = 'PROBE fatalRejection=' + (e.reason && e.reason.message || e.reason); });

setTimeout(async () => {
  const probe = new URLSearchParams(location.search).get('probe');
  try {
    if (probe === 'paste') {
      const ta = await enterEditMode();
      const editing = !!(window.__state ? window.__state.isEditing : true);

      // Twice, because the second is where a client that makes the name up itself parts
      // company with the file that is actually on disk.
      const mark1 = ta.value.length;
      const p1 = paste(ta, imageClipboard('FIRST-PASTE'));
      await sleep(2500);
      const first = ta.value.slice(mark1);

      const mark2 = ta.value.length;
      const p2 = paste(ta, imageClipboard('SECOND-PASTE'));
      await sleep(2500);
      const second = ta.value.slice(mark2);

      document.title = 'PROBE'
        + ' editing=' + editing
        + ' prevented=' + p1 + '/' + p2
        + ' first=' + JSON.stringify(first)
        + ' second=' + JSON.stringify(second)
        + ' dirty=' + !document.getElementById('save-btn').disabled
        // setEditingMode() hides the attachments strip; refreshing the list after a paste
        // must not pop it back into view under the author.
        + ' attachHidden=' + document.getElementById('attachments-section').classList.contains('hidden');
      return;
    }

    if (probe === 'ignore') {
      const ta = await enterEditMode();

      // Ordinary text: the browser pastes it and this module never sees a file.
      const beforeText = ta.value;
      const pText = paste(ta, textClipboard('just words'));

      // An image pasted somewhere that is not the editor. A chat composer or a dialog's
      // input is somebody else's paste, and uploading into the open page from one would
      // be a surprise.
      const foreign = document.createElement('textarea');
      document.body.appendChild(foreign);
      foreign.focus();
      const pForeign = paste(foreign, imageClipboard('WRONG-TARGET'));

      await sleep(2500);
      document.title = 'PROBE'
        + ' textPrevented=' + pText
        + ' textUntouched=' + (ta.value === beforeText)
        + ' foreignPrevented=' + pForeign;
      return;
    }

    document.title = 'PROBE noProbeRequested=true';
  } catch (e) {
    document.title = 'PROBE fatal=' + (e && e.message || e);
  }
}, 5000);
</script>
</body>"""
assert s.count('</body>') == 1
io.open(p, 'w', encoding='utf-8', newline='').write(s.replace('</body>', probe))
PY

# Restart the fixture's server behind the router.
PORT="${WIKI_URL##*:}"
kill "$WIKI_PID" 2>/dev/null; wait "$WIKI_PID" 2>/dev/null
( cd "$WIKI_APP" && exec php -d "session.save_path=$WIKI_ROOT/sessions" \
    -S "127.0.0.1:$PORT" __router.php ) > "$WIKI_ROOT/router.log" 2>&1 &
WIKI_PID=$!
i=0
until curl -sf --max-time 2 "$WIKI_URL/api.php?action=ping" > /dev/null 2>&1; do
    i=$((i + 1)); [ $i -gt 100 ] && { echo "router did not start" >&2; exit 1; }
    sleep 0.1
done

# load <page> [probe] → the probe line in $PROBE
load() {
    local q="pageid=$(page_id "$1")&space=Main"
    [ -n "${2:-}" ] && q="$q&probe=$2"
    "$CHROME" --headless=new --disable-gpu --no-sandbox --window-size=1280,900 \
        --virtual-time-budget=30000 \
        --dump-dom "$WIKI_URL/index.php?$q" > "$WIKI_ROOT/dom.html" 2>/dev/null
    # --dump-dom serialises the title, so the report comes back HTML-escaped — and the
    # thing being asserted on is a URL full of & separators.
    PROBE=$(grep -o '<title>PROBE[^<]*</title>' "$WIKI_ROOT/dom.html" \
            | python3 -c 'import html,sys; sys.stdout.write(html.unescape(sys.stdin.read()))' || true)
    [ -n "$PROBE" ] || _fail "the page never reported (probe did not run)" "page $1"
}
field() { printf '%s' "$PROBE" | sed -n "s/.* $1=\([^ <]*\).*/\1/p"; }

section 'a pasted bitmap is uploaded and linked'
load Notes.md paste
assert_not_contains "the probe ran without throwing" 'fatal' "$PROBE"
assert_contains "the native paste is suppressed" 'prevented=true/true' "$PROBE"
assert_contains "the first paste links image.png" \
    'first="![image.png](getfile.php?path=Notes.md.uploads%2Fimage.png&space=Main)"' "$PROBE"
assert_file_exists "and the file is on disk" "$UP/image.png"
assert_eq "with the pasted bytes" 'FIRST-PASTE' "$(cat "$UP/image.png" 2>/dev/null)"

section 'the second paste links the name the server actually used'
assert_contains "image2.png, not a repeat of image.png" \
    'second="![image2.png](getfile.php?path=Notes.md.uploads%2Fimage2.png&space=Main)"' "$PROBE"
assert_file_exists "which exists" "$UP/image2.png"
assert_eq "holding the second image"   'SECOND-PASTE' "$(cat "$UP/image2.png" 2>/dev/null)"
assert_eq "the first is still intact"  'FIRST-PASTE'  "$(cat "$UP/image.png" 2>/dev/null)"

section 'and the editor is left in the state an edit leaves it'
assert_contains "the page is marked unsaved" 'dirty=true' "$PROBE"
assert_contains "the attachments strip stays hidden" 'attachHidden=true' "$PROBE"

section 'anything that is not an image in the editor is left to the browser'
load Notes.md ignore
assert_not_contains "the probe ran without throwing" 'fatal' "$PROBE"
assert_contains "a text paste is not intercepted"    'textPrevented=false' "$PROBE"
assert_contains "  and the browser still pastes it"  'textUntouched=true'  "$PROBE"
assert_contains "an image outside the editor is ignored" 'foreignPrevented=false' "$PROBE"
# Neither of those may have uploaded anything: the page still has exactly the two images
# the first probe pasted.
count=$(ls -1 "$UP" 2>/dev/null | wc -l | tr -d ' ')
assert_eq "no further attachment was written" '2' "$count"

printf '\n'
exit $(( ASSERT_FAIL > 0 ))
