#!/usr/bin/env bash
# Astucia Wiki — Copyright (C) 2026 Mads Rotwitt
# Free software under the GNU GPL v3 or later. See LICENSE for the full notice,
# or <https://www.gnu.org/licenses/>. Distributed WITHOUT ANY WARRANTY.
#
# A person chooses their own avatar in My Preferences, and the dialog grew to hold it.
#
# Two things only a browser can see. The dialog's geometry: it gained a 100-icon picker on
# top of settings that already filled it, and the failure is the Save button sliding out of
# the box or off the screen — the bug the Space settings dialog had, invisible to HTTP. And
# that saving repaints the user's own chat bubbles in place, with the thread left open.
#
# The preferences dialog only exists with authentication on, so this logs a real browser
# in the way attention_ui.test.sh does: a session cookie that survives between two
# headless runs sharing a profile. Chrome missing means skip, not fail.

set -uo pipefail
cd "$(dirname "$0")"
. lib/assert.sh
. lib/fixture.sh

CHROME=""
for c in google-chrome chromium chromium-browser; do
    command -v "$c" >/dev/null 2>&1 && { CHROME="$c"; break; }
done
if [ -z "$CHROME" ]; then
    printf '  %s\n' "$(_dim 'skipped — no chrome/chromium on PATH')"
    exit 0
fi

fixture_start otp || exit 1
trap fixture_stop EXIT
fixture_space Main
fixture_users '{"users":[
  {"uid":1,"sub":"s1","name":"Admin","role":"admin","auth":"oidc"},
  {"uid":2,"sub":"s2","name":"Ed","role":"editor","auth":"oidc","email":"ed@example.com"}]}'
cat > "$WIKI_PAGES/Main/Talk.chat" <<'JSON'
{"messages":[{"id":1,"uid":2,"name":"Ed","text":"Hello from Ed","ts":"2026-10-01T10:00:00+00:00"}],
 "nextMessageId":2,"topic":"T"}
JSON
curl -s "$WIKI_URL/api.php?action=list_spaces" > /dev/null
curl -s "$WIKI_URL/api.php?action=indexfiles&space=Main" > /dev/null
CHAT_ID=$(python3 -c 'import json,sys
ix = json.load(open(sys.argv[1]))
print(next(k for k, v in ix.items() if v.get("path") == "Talk.chat"))' "$WIKI_PAGES/Main/index.json")

cat > "$WIKI_APP/__router.php" <<'R'
<?php
// GENERATED BY tests/preferences_avatar_ui.test.sh — never part of a release.
$p = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
$f = __DIR__ . $p;
if ($p !== '/' && is_file($f)) {
    $e = pathinfo($f, PATHINFO_EXTENSION);
    if ($e === 'js')  { header('Content-Type: text/javascript'); readfile($f); return true; }
    if ($e === 'css') { header('Content-Type: text/css');        readfile($f); return true; }
    if ($e === 'svg') { header('Content-Type: image/svg+xml');   readfile($f); return true; }
    return false;
}
return false;
R

python3 - "$WIKI_APP/index.php" <<'PY'
import io, sys
p = sys.argv[1]
s = io.open(p, encoding='utf-8', newline='').read()
probe = """<script type="module">
const sleep = (ms) => new Promise(r => setTimeout(r, ms));
const $ = (s) => document.querySelector(s);
const report = (v) => document.documentElement.setAttribute('data-probe', v);
window.addEventListener('error', e => report('fatal=' + e.message));
window.addEventListener('unhandledrejection', e => report('fatal=' + (e.reason && e.reason.message || e.reason)));
const mine = () => {
  const a = Array.from(document.querySelectorAll('.chat-row'))
      .find(r => r.textContent.includes('Hello from Ed'))?.querySelector('.chat-avatar');
  if (!a) return 'missing';
  const img = a.querySelector('img');
  return img ? 'img:' + img.getAttribute('src') : 'text:' + a.textContent.trim();
};
// Inside: every edge of the inner box within the outer one, to the pixel.
const inside = (inner, outer) => inner.top >= outer.top - 1 && inner.bottom <= outer.bottom + 1
    && inner.left >= outer.left - 1 && inner.right <= outer.right + 1;
const viewport = () => ({ top: 0, left: 0, bottom: window.innerHeight, right: window.innerWidth });
setTimeout(async () => {
  try {
    let out = 'before=' + mine();
    $('#preferences-btn').click();                              await sleep(1500);
    const box  = $('#preferences-lightbox .prefs-content');
    const save = $('#preferences-save-btn');
    out += ' width=' + Math.round(box.getBoundingClientRect().width);
    out += ' boxin=' + inside(box.getBoundingClientRect(), viewport());
    out += ' savein=' + inside(save.getBoundingClientRect(), box.getBoundingClientRect());
    // Opening the grid is what adds the height; Save must still be in the box after it.
    $('#pref-avatar-toggle').click();                           await sleep(300);
    const grid = $('#pref-avatar-grid');
    out += ' grid=' + (grid.classList.contains('hidden') ? 'closed' : 'open') + '/' + grid.querySelectorAll('[data-avatar]').length;
    out += ' none=' + (grid.querySelector('[data-avatar=""]')?.textContent.trim() || 'empty');
    out += ' openboxin=' + inside(box.getBoundingClientRect(), viewport());
    out += ' opensavein=' + inside(save.getBoundingClientRect(), box.getBoundingClientRect());
    const body = $('.prefs-body');
    out += ' scrolls=' + (body.scrollHeight > body.clientHeight ? 'yes' : 'no');
    grid.querySelector('[data-avatar="owl"]').click();          await sleep(200);
    out += ' picked=' + $('#pref-avatar').value;
    save.click();                                               await sleep(2500);
    out += ' closed=' + $('#preferences-lightbox').classList.contains('hidden');
    out += ' after=' + mine();
    report(out);
  } catch (e) { report('fatal=' + (e && e.message || e)); }
}, 4000);
</script>
</body>"""
assert s.count('</body>') == 1
io.open(p, 'w', encoding='utf-8', newline='').write(s.replace('</body>', probe))
PY

PORT="${WIKI_URL##*:}"
kill "$WIKI_PID" 2>/dev/null; wait "$WIKI_PID" 2>/dev/null
( cd "$WIKI_APP" && exec php -d "session.save_path=$WIKI_ROOT/sessions" \
    -d "session.cookie_lifetime=3600" \
    -S "127.0.0.1:$PORT" __router.php ) > "$WIKI_ROOT/router.log" 2>&1 &
WIKI_PID=$!
i=0
until curl -sf --max-time 2 "$WIKI_URL/api.php?action=ping" > /dev/null 2>&1; do
    i=$((i + 1)); [ $i -gt 100 ] && { echo "router did not start" >&2; exit 1; }
    sleep 0.1
done

PROFILE="$WIKI_ROOT/chrome-profile"
chrome() {  # chrome <height> <url>
    "$CHROME" --headless=new --disable-gpu --no-sandbox --window-size=1280,"$1" \
        --user-data-dir="$PROFILE" --virtual-time-budget=30000 \
        --dump-dom "$2" 2>/dev/null
}
probe() {   # probe <height>
    chrome "$1" "$WIKI_URL/index.php?pageid=$CHAT_ID&space=Main" > "$WIKI_ROOT/dom.html"
    PROBE=$(grep -o 'data-probe="[^"]*"' "$WIKI_ROOT/dom.html" \
            | python3 -c 'import html,sys; sys.stdout.write(html.unescape(sys.stdin.read()))' || true)
    [ -n "$PROBE" ] || _fail "the page never reported (probe did not run)" "height $1"
    assert_not_contains "the probe ran without throwing" 'fatal' "$PROBE"
}
reset_avatar() {
    python3 -c "import json;p='$WIKI_SYS/users.json';d=json.load(open(p));[u.pop('avatar',None) for u in d['users']];json.dump(d,open(p,'w'))"
}

chrome 900 "$WIKI_URL/__test_login.php?uid=2&sub=s2&name=Ed&role=editor" > /dev/null

section 'the dialog holds everything, Save included'
probe 900
assert_contains "it is 600 wide, not 440"          'width=600'       "$PROBE"
assert_contains "it is inside the window"          'boxin=true'      "$PROBE"
assert_contains "Save is inside it"                'savein=true'     "$PROBE"
assert_contains "the picker opens with 100 + none" 'grid=open/101'   "$PROBE"
assert_contains "'none' is your initial"           'none=E'          "$PROBE"
assert_contains "still inside with it open"        'openboxin=true'  "$PROBE"
assert_contains "and Save still reachable"         'opensavein=true' "$PROBE"

section 'choosing one repaints your own bubbles'
assert_contains "the bubble starts as your initial" 'before=text:E'  "$PROBE"
assert_contains "the pick reaches the field"       'picked=owl'      "$PROBE"
assert_contains "saving closes the dialog"         'closed=true'     "$PROBE"
assert_contains "and the open thread shows it"     'after=img:avatars/owl.svg' "$PROBE"
assert_eq "stored on the user record"              'owl' \
    "$(python3 -c "import json;print([u for u in json.load(open('$WIKI_SYS/users.json'))['users'] if u['uid']==2][0].get('avatar'))")"

section 'a short window: the body scrolls and Save stays put'
# The viewport cap is what keeps Save on screen when the content is taller than the window;
# a fixed height would push it off the bottom, which is how the Space settings bug began.
reset_avatar
probe 600
assert_contains "the dialog fits the window"       'openboxin=true'  "$PROBE"
assert_contains "Save is still inside it"          'opensavein=true' "$PROBE"
assert_contains "because the body scrolls instead" 'scrolls=yes'     "$PROBE"

printf '\n'
exit $(( ASSERT_FAIL > 0 ))
