#!/usr/bin/env bash
# Astucia Wiki — Copyright (C) 2026 Mads Rotwitt
# Free software under the GNU GPL v3 or later. See LICENSE for the full notice,
# or <https://www.gnu.org/licenses/>. Distributed WITHOUT ANY WARRANTY.
#
# The page header after a rename.
#
# A rename deliberately does not reload the page — it only retitles — so the header is
# written a second time, by modules/file_ops rather than by loadPage. That second copy
# had drifted: it wrote `textContent` with the **whole path**, which erased the type icon
# (textContent replaces the element's children, svg included) and put `Folder/Sub/Page`
# where the file's own name belongs, duplicating what the breadcrumb already says.
#
# Nothing black-box can see any of it. The `move` action succeeded, the file is where it
# should be, the index is right and every HTTP assertion passes; the damage is two
# properties of one element in a browser that never navigated. So the page is renamed by
# driving the real controls — the … menu's Rename, the prompt dialog, its OK button — and
# the header is measured before and after.
#
# The icon is compared against the one loadPage rendered rather than merely being counted,
# because "an svg is present" is satisfied by the wrong icon, and the rename path picks
# its own.
#
# It also renames a `.json` and a `.search` page, because the same handler kept three
# lists of file extensions — one to strip for display, one to put back, one for the
# prompt's icon — and those two types were in none of them: the box offered
# `Data.json`, and a name typed over it was written back with no extension at all. That
# one *is* visible on disk, so it is asserted there as well as in the header.
#
# Chrome is not a test dependency — no chrome means skip, not fail.

set -uo pipefail
cd "$(dirname "$0")"
. lib/assert.sh
. lib/fixture.sh

CHROME=""
for c in google-chrome chromium chromium-browser; do
    command -v "$c" >/dev/null 2>&1 && { CHROME="$c"; break; }
done
if [ -z "$CHROME" ]; then
    printf '  %s\n' "$(_dim 'skipped — no chrome/chromium on PATH')"
    exit 0
fi

fixture_start off || exit 1
trap fixture_stop EXIT

fixture_space Main
# In a subfolder, which is the whole point: at the space root the basename and the path
# are the same string, so the bug is invisible there.
fixture_page 'Main/Notes/Deep/Draft.md' '# Draft'
# Nothing links to it, so the wikilink-retarget prompt never opens and cannot swallow the
# clicks that follow.
fixture_page 'Main/Other.md' '# Other'
# The two types the handler had never heard of. Both in the same folder, for the same
# reason Draft.md is: a basename that differs from its path.
fixture_page 'Main/Notes/Deep/Data.json' '{"rows": []}'
fixture_page 'Main/Notes/Deep/Query.search' '{"terms": "deep"}'

curl -s "$WIKI_URL/api.php?action=list_spaces" > /dev/null
curl -s "$WIKI_URL/api.php?action=indexfiles&space=Main" > /dev/null

page_id() {
    python3 -c 'import json,sys
ix = json.load(open(sys.argv[1]))
print(next(k for k, v in ix.items() if v.get("path") == sys.argv[2]))' \
        "$WIKI_PAGES/Main/index.json" "$1"
}

cat > "$WIKI_APP/__router.php" <<'R'
<?php
// GENERATED BY tests/rename_header_ui.test.sh — never part of a release.
$p = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
$f = __DIR__ . $p;
if ($p !== '/' && is_file($f)) {
    $e = pathinfo($f, PATHINFO_EXTENSION);
    if ($e === 'js')  { header('Content-Type: text/javascript'); readfile($f); return true; }
    if ($e === 'css') { header('Content-Type: text/css');        readfile($f); return true; }
    return false;
}
return false;
R

python3 - "$WIKI_APP/index.php" <<'PY'
import io, sys
p = sys.argv[1]
s = io.open(p, encoding='utf-8', newline='').read()
# Reported through document.title, which --dump-dom returns without a DevTools
# connection. No backslashes in here: this lives in a Python heredoc inside a shell
# script, and a parse error would take the whole module down silently.
probe = """<script type="module">
const sleep = (ms) => new Promise(r => setTimeout(r, ms));
const head  = () => document.getElementById('current-page-title');
const text  = () => (head()?.textContent || '').trim();
const svg   = () => head()?.querySelector('svg')?.outerHTML || '';
const crumb = () => (document.getElementById('page-breadcrumb')?.textContent || '')
                      .replace(/\\s+/g, ' ').trim();

window.addEventListener('error', e => { document.title = 'PROBE fatal=' + e.message; });
window.addEventListener('unhandledrejection',
    e => { document.title = 'PROBE fatal=' + (e.reason && e.reason.message || e.reason); });

setTimeout(async () => {
  try {
    let out = '';
    // As loadPage rendered it: the file's own name, and the markdown icon beside it.
    const iconBefore = svg();
    out += ' before=' + text() + '/icon:' + (iconBefore ? 'yes' : 'no')
         + '/crumb:' + crumb();

    // Rename through the real controls, exactly as a reader would.
    document.getElementById('rename-btn').click();
    await sleep(400);
    const dialog = document.getElementById('input-modal');
    out += ' dialog=' + (dialog && !dialog.classList.contains('hidden') ? 'open' : 'shut');
    // The prompt is seeded with the file's own name, never the path.
    out += ' seeded=' + (document.getElementById('input-modal-input')?.value || '');
    // And it is illustrated with this page's own type icon. Read while the dialog is
    // open, because it is the only moment it exists — and compared against the header's,
    // since the handler chose it from a map of its own that had a dead key in it.
    out += ' prompticon:' +
        (document.getElementById('input-modal-icon')?.innerHTML.trim() === iconBefore
            ? 'same' : 'differs');
    document.getElementById('input-modal-input').value =
        new URLSearchParams(location.search).get('rename');
    document.getElementById('input-modal-ok').click();
    await sleep(2500);

    // The header afterwards. A title carrying a slash is the bug: the folders above the
    // page are the breadcrumb's, and it is still showing them.
    out += ' after=' + text() + '/icon:' + (svg() ? 'yes' : 'no')
         + '/slash:' + (text().indexOf('/') >= 0 ? 'yes' : 'no')
         + '/same:' + (svg() && svg() === iconBefore ? 'yes' : 'no')
         + '/crumb:' + crumb();

    // Copy composes a filename from the same question rename does, and answered it from
    // a literal of its own. The box offers a name; the extension is added for you.
    document.getElementById('copy-btn').click();
    await sleep(400);
    out += ' copybox=' + (document.getElementById('copy-new-name')?.value || '');
    document.getElementById('copy-new-name').value =
        new URLSearchParams(location.search).get('copy') || 'Unused';
    document.getElementById('copy-confirm-btn').click();
    await sleep(2000);

    document.title = 'PROBE' + out;
  } catch (e) {
    document.title = 'PROBE fatal=' + (e && e.message || e);
  }
}, 4000);
</script>
</body>"""
assert s.count('</body>') == 1
io.open(p, 'w', encoding='utf-8', newline='').write(s.replace('</body>', probe))
PY

PORT="${WIKI_URL##*:}"
kill "$WIKI_PID" 2>/dev/null; wait "$WIKI_PID" 2>/dev/null
( cd "$WIKI_APP" && exec php -d "session.save_path=$WIKI_ROOT/sessions" \
    -S "127.0.0.1:$PORT" __router.php ) > "$WIKI_ROOT/router.log" 2>&1 &
WIKI_PID=$!
i=0
until curl -sf --max-time 2 "$WIKI_URL/api.php?action=ping" > /dev/null 2>&1; do
    i=$((i + 1)); [ $i -gt 100 ] && { echo "router did not start" >&2; exit 1; }
    sleep 0.1
done

# rename <space-relative page> <new name> <copy name>
#   Opens the page, renames it, then copies the result into the space root. Both in one
#   run because they are the same question — which extension does this file carry — and
#   because a browser launch costs more than the second half of a probe.
rename() {
    "$CHROME" --headless=new --disable-gpu --no-sandbox --window-size=1280,900 \
        --virtual-time-budget=30000 \
        --dump-dom "$WIKI_URL/index.php?pageid=$(page_id "$1")&space=Main&rename=$2&copy=$3" \
        > "$WIKI_ROOT/dom.html" 2>/dev/null
    PROBE=$(grep -o '<title>PROBE[^<]*</title>' "$WIKI_ROOT/dom.html" \
            | python3 -c 'import html,sys; sys.stdout.write(html.unescape(sys.stdin.read()))' || true)
    [ -n "$PROBE" ] || _fail "the page never reported (probe did not run)" "page $1"
    assert_not_contains "the probe ran without throwing" 'fatal' "$PROBE"
}

rename 'Notes/Deep/Draft.md' Plan PlanCopy

section 'before the rename, as loadPage draws it'
assert_contains "the header is the file's own name" 'before=Draft/'  "$PROBE"
assert_contains "  with its type icon"              'before=Draft/icon:yes' "$PROBE"
assert_contains "  and the folders are the breadcrumb's" 'crumb:Main / Root / Notes / Deep' "$PROBE"

section 'the rename really happened'
# The positive control for everything below: without it the header would read "Draft"
# and every assertion about the new name would be measuring a page that never moved.
assert_contains "the prompt opened"                 'dialog=open'     "$PROBE"
assert_contains "  seeded with the name, not the path" 'seeded=Draft prompticon:' "$PROBE"
assert_contains "  and with this page's own icon"      'prompticon:same' "$PROBE"
assert_file_exists "the file moved" "$WIKI_PAGES/Main/Notes/Deep/Plan.md"

section 'after the rename, the header says the same kind of thing'
assert_contains "it is the new name alone"          'after=Plan/'     "$PROBE"
assert_contains "  not the path"                    'slash:no'        "$PROBE"
assert_contains "  the type icon survived"          'after=Plan/icon:yes' "$PROBE"
# Counting the svg is not enough — the rename path chooses an icon of its own, and the
# wrong one is still one.
assert_contains "  and it is the same icon as before" 'same:yes'      "$PROBE"
assert_contains "  the breadcrumb is unchanged"     'after=Plan/icon:yes/slash:no/same:yes/crumb:Main / Root / Notes / Deep' "$PROBE"
assert_contains "the copy box offers the name without the extension" 'copybox=Plan ' "$PROBE"
assert_file_exists "  and the copy carries it" "$WIKI_PAGES/Main/PlanCopy.md"

section 'a data page keeps its extension'
# The extension decides how the wiki renders and indexes a file, so a rename may not
# change it. Before the handler knew about `.json` the box offered "Data.json" and a name
# typed over it landed on disk with nothing after it.
rename 'Notes/Deep/Data.json' Figures FiguresCopy
assert_contains "the box offered the name without it"  'seeded=Data prompticon:'  "$PROBE"
assert_contains "  illustrated with the data-page icon" 'prompticon:same' "$PROBE"
assert_file_exists "the extension came back" "$WIKI_PAGES/Main/Notes/Deep/Figures.json"
assert_file_missing "  and not as a bare name" "$WIKI_PAGES/Main/Notes/Deep/Figures"
assert_contains "the header is the new name alone"     'after=Figures/'  "$PROBE"
assert_contains "  with the data-page icon, unchanged" 'same:yes'        "$PROBE"
assert_contains "the copy box offers the name without the extension" 'copybox=Figures ' "$PROBE"
# The old fallback for an extension the pattern did not list was `.md`, so this landed as
# a Markdown file holding JSON.
assert_file_exists "  and the copy is still a data page" "$WIKI_PAGES/Main/FiguresCopy.json"
assert_file_missing "  not a Markdown one" "$WIKI_PAGES/Main/FiguresCopy.md"

section 'and so does a saved search'
rename 'Notes/Deep/Query.search' Recent RecentCopy
assert_contains "the box offered the name without it"  'seeded=Query prompticon:' "$PROBE"
assert_contains "  illustrated with the saved-search icon" 'prompticon:same' "$PROBE"
assert_file_exists "the extension came back" "$WIKI_PAGES/Main/Notes/Deep/Recent.search"
assert_file_missing "  and not as a bare name" "$WIKI_PAGES/Main/Notes/Deep/Recent"
assert_contains "the header is the new name alone"     'after=Recent/'   "$PROBE"
assert_contains "  with the saved-search icon, unchanged" 'same:yes'     "$PROBE"
assert_contains "the copy box offers the name without the extension" 'copybox=Recent ' "$PROBE"
assert_file_exists "  and the copy is still a saved search" "$WIKI_PAGES/Main/RecentCopy.search"
assert_file_missing "  not a Markdown one" "$WIKI_PAGES/Main/RecentCopy.md"

printf '\n'
exit $(( ASSERT_FAIL > 0 ))
