#!/usr/bin/env bash
# Astucia Wiki — Copyright (C) 2026 Mads Rotwitt
# Free software under the GNU GPL v3 or later. See LICENSE for the full notice,
# or <https://www.gnu.org/licenses/>. Distributed WITHOUT ANY WARRANTY.
#
# The tab bar's ⌄ menu, in a real browser.
#
# `modules/tabs` is measurement-driven — which tabs fit is decided from `offsetWidth` and
# the strip's budget — so nothing about it is visible to an HTTP test, and the two states
# that matter here differ only in whether a button is in the row. Same mechanics as the
# other two browser suites (tests/frontmatter_ui.test.sh, tests/code_copy_ui.test.sh): a
# two-line router so `php -S` serves ES modules, instrumentation that only clicks real
# controls, and a report read out of document.title.
#
# Chrome is not a test dependency — no chrome means skip, not fail.

set -uo pipefail
cd "$(dirname "$0")"
. lib/assert.sh
. lib/fixture.sh

CHROME=""
for c in google-chrome chromium chromium-browser; do
    command -v "$c" >/dev/null 2>&1 && { CHROME="$c"; break; }
done
if [ -z "$CHROME" ]; then
    printf '  %s\n' "$(_dim 'skipped — no chrome/chromium on PATH')"
    exit 0
fi

fixture_start off || exit 1
trap fixture_stop EXIT

fixture_space Main
# Two short names that fit side by side, and eight long ones that cannot: the whole
# feature is about the difference between "nothing is hidden" and "some tabs are".
fixture_page 'Main/A.md' '# A'
fixture_page 'Main/B.md' '# B'
for n in 1 2 3 4 5 6 7 8; do
    fixture_page "Main/A Rather Long Page Name $n.md" "# Long $n"
done

curl -s "$WIKI_URL/api.php?action=list_spaces" > /dev/null
curl -s "$WIKI_URL/api.php?action=indexfiles&space=Main" > /dev/null

page_id() {
    python3 -c 'import json,sys
ix = json.load(open(sys.argv[1]))
print(next(k for k, v in ix.items() if v.get("path") == sys.argv[2]))' \
        "$WIKI_PAGES/${2:-Main}/index.json" "$1"
}

cat > "$WIKI_APP/__router.php" <<'R'
<?php
// GENERATED BY tests/tabs_ui.test.sh — never part of a release.
$p = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
$f = __DIR__ . $p;
if ($p !== '/' && is_file($f)) {
    $e = pathinfo($f, PATHINFO_EXTENSION);
    if ($e === 'js')  { header('Content-Type: text/javascript'); readfile($f); return true; }
    if ($e === 'css') { header('Content-Type: text/css');        readfile($f); return true; }
    return false;
}
return false;
R

python3 - "$WIKI_APP/index.php" <<'PY'
import io, sys
p = sys.argv[1]
s = io.open(p, encoding='utf-8', newline='').read()
# ?probe=<n> opens n pages as permanent tabs through the ordinary loadPage path, then
# clicks the ⌄ button and reports what the menu holds. The report goes in document.title,
# which --dump-dom returns without a DevTools connection.
probe = """<script type="module">
const PAGES = ['A.md', 'B.md',
  'A Rather Long Page Name 1.md', 'A Rather Long Page Name 2.md',
  'A Rather Long Page Name 3.md', 'A Rather Long Page Name 4.md',
  'A Rather Long Page Name 5.md', 'A Rather Long Page Name 6.md',
  'A Rather Long Page Name 7.md', 'A Rather Long Page Name 8.md'];

const report = (extra) => {
  const bar   = document.getElementById('wiki-tabs');
  const more  = bar && bar.querySelector('.wiki-tabs-more');
  const menu  = document.querySelector('.wiki-tab-menu-overflow');
  const rows  = menu ? [...menu.querySelectorAll('button')] : [];
  const last  = rows[rows.length - 1];
  // Whether the rule has something on both sides of it, which is the only case it is
  // drawn in — and whether the action is genuinely the last row, not merely present.
  const kids  = menu ? [...menu.children] : [];
  document.title = 'PROBE tabs=' + (bar ? bar.querySelectorAll('.wiki-tab').length : 0)
    + ' hidden=' + (bar ? bar.querySelectorAll('.wiki-tab.overflowed').length : 0)
    + ' more=' + (more ? (more.classList.contains('hidden') ? 'hidden' : 'shown') : 'absent')
    + ' count=' + JSON.stringify(more ? more.querySelector('.wiki-tabs-more-count').textContent : '-')
    + ' tip=' + JSON.stringify(more ? (more.title || '') : '')
    + ' menu=' + (menu ? 'open' : 'ABSENT')
    + ' listed=' + (menu ? menu.querySelectorAll('.wiki-tab-menu-list button').length : -1)
    + ' rules=' + (menu ? menu.querySelectorAll('.wiki-tab-menu-sep').length : -1)
    + ' lastIsAction=' + (last && last.classList.contains('wiki-tab-menu-action') ? 'yes' : 'NO')
    + ' lastRow=' + JSON.stringify(last ? last.textContent.trim() : '')
    + ' order=' + JSON.stringify(kids.map(k => k.className.replace('wiki-tab-menu-', '')).join(' '))
    // Not asserted on — it is what names *which* tabs when a count assertion fails.
    + ' paths=' + JSON.stringify(bar ? [...bar.querySelectorAll('.wiki-tab')].map(e => e.title).join('|') : '')
    + (extra || '');
};

window.addEventListener('error', e => { document.title = 'PROBE fatal=' + e.message; });
window.addEventListener('unhandledrejection', e => {
    document.title = 'PROBE fatalRejection=' + (e.reason && e.reason.message || e.reason); });

setTimeout(async () => {
  const q = new URLSearchParams(location.search);
  const n = parseInt(q.get('probe') || '0', 10);
  if (!n) { report(); return; }
  // Real tabs, opened the way every create path opens one.
  const { loadPage } = await import('./modules/page_view/index.js');
  for (const rel of PAGES.slice(0, n)) {
    await loadPage(rel, null, [], { intent: 'permanent' });
  }
  await new Promise(r => setTimeout(r, 600));
  document.querySelector('#wiki-tabs .wiki-tabs-more')?.click();
  await new Promise(r => setTimeout(r, 400));
  if (q.get('act') !== 'close') { report(); return; }
  // Click the action itself, then report what is left of the bar.
  const active = document.querySelector('#wiki-tabs .wiki-tab.active')?.title || '';
  document.querySelector('.wiki-tab-menu-action')?.click();
  await new Promise(r => setTimeout(r, 2500));
  const kept = [...document.querySelectorAll('#wiki-tabs .wiki-tab')].map(el => el.title);
  report(' wasActive=' + JSON.stringify(active) + ' kept=' + JSON.stringify(kept.join('|')));
}, 5000);
</script>
</body>"""
assert s.count('</body>') == 1
io.open(p, 'w', encoding='utf-8', newline='').write(s.replace('</body>', probe))
PY

# Restart the fixture's server behind the router.
PORT="${WIKI_URL##*:}"
kill "$WIKI_PID" 2>/dev/null; wait "$WIKI_PID" 2>/dev/null
( cd "$WIKI_APP" && exec php -d "session.save_path=$WIKI_ROOT/sessions" \
    -S "127.0.0.1:$PORT" __router.php ) > "$WIKI_ROOT/router.log" 2>&1 &
WIKI_PID=$!
i=0
until curl -sf --max-time 2 "$WIKI_URL/api.php?action=ping" > /dev/null 2>&1; do
    i=$((i + 1)); [ $i -gt 100 ] && { echo "router did not start" >&2; exit 1; }
    sleep 0.1
done

# load <tabs-to-open> [act] → the probe line in $PROBE
load() {
    local q="pageid=$(page_id 'A.md')&space=Main&probe=$1"
    [ -n "${2:-}" ] && q="$q&act=$2"
    "$CHROME" --headless=new --disable-gpu --no-sandbox --window-size=1280,900 \
        --virtual-time-budget=30000 \
        --dump-dom "$WIKI_URL/index.php?$q" > "$WIKI_ROOT/dom.html" 2>/dev/null
    DOM=$(cat "$WIKI_ROOT/dom.html")
    PROBE=$(printf '%s' "$DOM" | grep -o '<title>PROBE[^<]*</title>' \
            | python3 -c 'import html,sys; sys.stdout.write(html.unescape(sys.stdin.read()))' || true)
    [ -n "$PROBE" ] || _fail "the page never reported (probe did not run)" "tabs=$1"
}
field() { printf '%s' "$PROBE" | sed -n "s/.* $1=\([^ <]*\).*/\1/p"; }

section 'one tab has nothing to offer, so there is no button'
load 1
assert_eq "one tab"        '1'      "$(field tabs)"
assert_eq "no ⌄ button"    'hidden' "$(field more)"

section 'two tabs that both fit: the button is there anyway'
load 2
assert_eq "two tabs"               '2'     "$(field tabs)"
assert_eq "  none of them hidden"  '0'     "$(field hidden)"
assert_eq "the ⌄ button is shown"  'shown' "$(field more)"
assert_contains "  with no count on it" 'count=""' "$PROBE"
assert_contains "  and a tooltip that does not claim hidden tabs" 'tip="Tab menu"' "$PROBE"
assert_eq "the menu opens"                    'open' "$(field menu)"
assert_eq "  listing no tabs"                 '0'    "$(field listed)"
assert_eq "  and drawing no rule above one row" '0'  "$(field rules)"
assert_contains "the action is the only row" 'lastRow="Close all but current"' "$PROBE"

section 'enough tabs to overflow: hidden tabs, then a rule, then the action'
load 10
assert_eq "ten tabs"              '10'    "$(field tabs)"
assert_eq "the ⌄ button is shown" 'shown' "$(field more)"
hidden=$(field hidden)
printf '  %s\n' "$(_dim "measured: $hidden of 10 tabs hidden at 1280px")"
if [ "${hidden:-0}" -ge 1 ] 2>/dev/null; then _pass "some tabs are hidden"
else _fail "some tabs are hidden" "nothing overflowed, so this case was not exercised"; fi
assert_eq "the count is the hidden tabs"  "$hidden" "$(field count | tr -d '\"')"
assert_eq "the menu lists exactly those"  "$hidden" "$(field listed)"
assert_eq "one rule"                      '1'       "$(field rules)"
assert_contains "the list scrolls, the action does not" 'order="list sep action"' "$PROBE"
assert_eq "the action is last"            'yes'     "$(field lastIsAction)"
assert_contains "  and says so"  'lastRow="Close all but current"' "$PROBE"

section 'and it closes everything except the tab you are on'
load 10 close
assert_eq "one tab left"          '1'      "$(field tabs)"
assert_eq "the button goes away"  'hidden' "$(field more)"
was=$(printf '%s' "$PROBE" | sed -n 's/.* wasActive="\([^"]*\)".*/\1/p')
kept=$(printf '%s' "$PROBE" | sed -n 's/.* kept="\([^"]*\)".*/\1/p')
assert_eq "and it is the one that was active" "$was" "$kept"
