#!/usr/bin/env bash
# Astucia Wiki — Copyright (C) 2026 Mads Rotwitt
# Free software under the GNU GPL v3 or later. See LICENSE for the full notice,
# or <https://www.gnu.org/licenses/>. Distributed WITHOUT ANY WARRANTY.
#
# Admin → Content → Workflows in a browser: the overview, the on/off switch, the editor,
# the Test preview and the run history.
#
# tests/workflows.test.sh proves what a definition *does*; this proves the panel can
# produce one. The failures it is for are invisible over HTTP — an action whose fields
# are rendered but never read back, a switch that flips on screen and not on the server,
# a type change that throws away what was typed.
#
# Chrome is not a test dependency — no chrome means skip, not fail.

set -uo pipefail
cd "$(dirname "$0")"
. lib/assert.sh
. lib/fixture.sh

CHROME=""
for c in google-chrome chromium chromium-browser; do
    command -v "$c" >/dev/null 2>&1 && { CHROME="$c"; break; }
done
if [ -z "$CHROME" ]; then
    printf '  %s\n' "$(_dim 'skipped — no chrome/chromium on PATH')"
    exit 0
fi

fixture_start off || exit 1
trap fixture_stop EXIT
fixture_space Main
fixture_page 'Main/Docs/a.md' 'Alpha'
fixture_page 'Main/Team.chat' '{"messages":[],"nextMessageId":1,"topic":"T"}'
curl -s "$WIKI_URL/api.php?action=list_spaces" > /dev/null
curl -s "$WIKI_URL/api.php?action=indexfiles&space=Main" > /dev/null

cat > "$WIKI_APP/__router.php" <<'R'
<?php
// GENERATED BY tests/workflows_ui.test.sh — never part of a release.
$p = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
$f = __DIR__ . $p;
if ($p !== '/' && is_file($f)) {
    $e = pathinfo($f, PATHINFO_EXTENSION);
    if ($e === 'js')  { header('Content-Type: text/javascript'); readfile($f); return true; }
    if ($e === 'css') { header('Content-Type: text/css');        readfile($f); return true; }
    if ($e === 'svg') { header('Content-Type: image/svg+xml');   readfile($f); return true; }
    return false;
}
return false;
R

python3 - "$WIKI_APP/index.php" <<'PY'
import io, sys
p = sys.argv[1]
s = io.open(p, encoding='utf-8', newline='').read()
# Reported through document.title. No backslashes in here: this lives in a Python heredoc
# inside a shell script.
probe = """<script type="module">
const sleep = (ms) => new Promise(r => setTimeout(r, ms));
const $ = (sel) => document.querySelector(sel);
const $$ = (sel) => Array.from(document.querySelectorAll(sel));
const click = (el) => { if (!el) throw new Error('missing control'); el.click(); };
const set = (sel, v) => { const el = $(sel); if (!el) throw new Error('missing ' + sel); el.value = v; el.dispatchEvent(new Event('change')); };
const report = (out) => { document.title = 'PROBE' + out; };
const server = async () => (await (await fetch('api.php?action=admin_get_workflows')).json()).workflows;

window.addEventListener('error', e => report(' fatal=' + e.message));
window.addEventListener('unhandledrejection', e => report(' fatal=' + (e.reason && e.reason.message || e.reason)));

const run = async () => {
  let out = '';
  click($('#admin-btn'));                                     await sleep(800);
  click($('.admin-group[data-group="content"]'));             await sleep(500);
  const tab = $('.admin-tab[data-tab="workflows"]');
  out += ' tab=' + (tab && !tab.classList.contains('hidden') ? 'shown' : 'missing');
  out += ' icon=' + (tab && tab.querySelector('svg') ? 'yes' : 'no');
  click(tab);                                                 await sleep(1000);
  out += ' empty=' + ($('#admin-workflows-list .admin-empty') ? 'yes' : 'no');
  out += ' addbtn=' + ($('#admin-workflows-add-btn').closest('.hidden') ? 'hidden' : 'shown');

  // Build one: saved on page updates under Docs, two actions.
  click($('#admin-workflows-add-btn'));                       await sleep(400);
  $('#wf-f-name').value = 'Review';
  set('#wf-f-trigger', 'tag_added');                          await sleep(100);
  out += ' tagbox=' + ($('#wf-f-tag') ? 'yes' : 'no');
  $('#wf-f-tag').value = 'review';
  // The folder comes from the picker, not the keyboard.
  const clearOf = (id) => $('.wf-path-clear[data-for="' + id + '"]');
  out += ' xbefore=' + (clearOf('wf-f-folder').classList.contains('hidden') ? 'hidden' : 'shown');
  click($('.wf-path-browse[data-for="wf-f-folder"]'));        await sleep(800);
  out += ' picker=' + ($('#pp-lightbox').classList.contains('hidden') ? 'closed' : 'open');
  out += ' spacelocked=' + ($('#pp-space-group').classList.contains('hidden') ? 'yes' : 'no');
  out += ' foldermode=' + ($$('#pp-file-list .pp-file').length === 0 ? 'nofiles' : 'files');
  click($('#pp-file-list .pp-folder[data-name="Docs"]'));     await sleep(200);
  click($('#pp-choose-folder'));                              await sleep(200);
  out += ' folder=' + $('#wf-f-folder').value;
  out += ' xafter=' + (clearOf('wf-f-folder').classList.contains('hidden') ? 'hidden' : 'shown');
  click(clearOf('wf-f-folder'));                              await sleep(100);
  out += ' cleared=[' + $('#wf-f-folder').value + ']/' + (clearOf('wf-f-folder').classList.contains('hidden') ? 'hidden' : 'shown');
  click($('.wf-path-browse[data-for="wf-f-folder"]'));        await sleep(800);
  click($('#pp-file-list .pp-folder[data-name="Docs"]'));     await sleep(200);
  click($('#pp-choose-folder'));                              await sleep(200);
  // The first action defaults to email; switch it to a tag action.
  set('.wf-action-card[data-i="0"] .wf-action-type', 'tag'); await sleep(100);
  $('#wf-a0-add').value = 'seen, queued';
  out += ' runnew=' + ($('#wf-run-btn') ? 'yes' : 'no');
  click($('#wf-add-action'));                                 await sleep(100);
  // Adding an action must not throw away what was typed in the first.
  out += ' kept=' + $('#wf-a0-add').value;
  set('.wf-action-card[data-i="1"] .wf-action-type', 'chat'); await sleep(100);
  click($('.wf-path-browse[data-for="wf-a1-chat"]'));        await sleep(800);
  // Only chats are offered for a chat field — not Docs/a.md's folder contents, not pages.
  out += ' chatfiles=' + $$('#pp-file-list .pp-file').map(f => f.dataset.path).join('+');
  click($('#pp-file-list .pp-file[data-path="Team.chat"]'));  await sleep(200);
  out += ' chat=' + $('#wf-a1-chat').value;
  $('#wf-a1-text').value = '{{page}} needs review';

  // Test before saving: the unsaved form is what is previewed.
  click($('.wf-path-browse[data-for="wf-t-path"]'));         await sleep(800);
  click($('#pp-file-list .pp-folder[data-name="Docs"]'));     await sleep(200);
  click($('#pp-file-list .pp-file[data-path="Docs/a.md"]'));  await sleep(200);
  out += ' testpath=' + $('#wf-t-path').value;
  click($('#wf-test-btn'));                                   await sleep(1200);
  const prev = $('#wf-test-out').textContent;
  out += ' preview=' + (prev.includes('a needs review') ? 'rendered' : 'missing');
  out += ' previewtags=' + (prev.includes('+#seen') ? 'yes' : 'no');

  click($('#wf-f-save'));                                     await sleep(1500);
  const rows = $$('#admin-workflows-list tbody tr');
  out += ' rows=' + rows.length;
  let wf = (await server())[0] || {};
  out += ' stored=' + (wf.trigger && wf.trigger.type) + '/' + (wf.trigger && wf.trigger.tag) + '/' + (wf.filters && wf.filters.folder);
  out += ' actions=' + (wf.actions || []).map(a => a.type).join('+');
  out += ' tags=' + ((wf.actions || [])[0] || {}).add;
  out += ' on=' + wf.enabled;

  // The switch in the overview reaches the server.
  click($('#admin-workflows-list .wf-toggle'));               await sleep(1500);
  wf = (await server())[0] || {};
  out += ' toggled=' + wf.enabled;
  out += ' dimmed=' + ($('#admin-workflows-list tbody tr.wf-row-off') ? 'yes' : 'no');

  // Edit opens with what was saved.
  click($('#admin-workflows-list .wf-edit'));                 await sleep(400);
  out += ' editname=' + $('#wf-f-name').value + ' edittrigger=' + $('#wf-f-trigger').value;
  out += ' editcards=' + $$('.wf-action-card').length;
  // Run now, for real, behind a confirmation.
  $('#wf-t-path').value = 'Docs/a.md';
  click($('#wf-run-btn'));                                    await sleep(400);
  out += ' confirm=' + ($('#confirm-modal').classList.contains('hidden') ? 'none' : 'asked');
  click($('#confirm-modal-ok'));                              await sleep(2000);
  out += ' ran=' + ($('#wf-test-out').textContent.includes('Ran for real') ? 'yes' : 'no');
  const thread = await (await fetch('api.php?action=chat_messages&space=Main&file=Team.chat')).text();
  out += ' posted=' + (thread.includes('needs review') ? 'yes' : 'no');
  click($('#wf-f-cancel'));                                   await sleep(300);

  // History opens, and comes back.
  click($('#admin-workflows-list .wf-history'));              await sleep(800);
  out += ' history=' + ($('#admin-workflows-list .admin-empty') ? 'empty' : 'rows');
  click($('#admin-workflows-list .wf-back'));                 await sleep(300);
  out += ' back=' + $$('#admin-workflows-list tbody tr').length;
  return out;
};

setTimeout(async () => {
  try { report(await run()); } catch (e) { report(' fatal=' + (e && e.message || e)); }
}, 4000);
</script>
</body>"""
assert s.count('</body>') == 1
io.open(p, 'w', encoding='utf-8', newline='').write(s.replace('</body>', probe))
PY

PORT="${WIKI_URL##*:}"
kill "$WIKI_PID" 2>/dev/null; wait "$WIKI_PID" 2>/dev/null
( cd "$WIKI_APP" && exec php -d "session.save_path=$WIKI_ROOT/sessions" \
    -S "127.0.0.1:$PORT" __router.php ) > "$WIKI_ROOT/router.log" 2>&1 &
WIKI_PID=$!
i=0
until curl -sf --max-time 2 "$WIKI_URL/api.php?action=ping" > /dev/null 2>&1; do
    i=$((i + 1)); [ $i -gt 100 ] && { echo "router did not start" >&2; exit 1; }
    sleep 0.1
done

"$CHROME" --headless=new --disable-gpu --no-sandbox --window-size=1280,900 \
    --virtual-time-budget=60000 \
    --dump-dom "$WIKI_URL/index.php" > "$WIKI_ROOT/dom.html" 2>/dev/null
PROBE=$(grep -o '<title>PROBE[^<]*</title>' "$WIKI_ROOT/dom.html" \
        | python3 -c 'import html,sys; sys.stdout.write(html.unescape(sys.stdin.read()))' || true)
[ -n "$PROBE" ] || _fail "the page never reported (probe did not run)" ""
assert_not_contains "the probe ran without throwing" 'fatal' "$PROBE"

section 'the tab'
assert_contains "under Content"                   'tab=shown'            "$PROBE"
assert_contains "with its icon"                   'icon=yes'             "$PROBE"
assert_contains "empty to begin with"             'empty=yes'            "$PROBE"
assert_contains "with a New button"               'addbtn=shown'         "$PROBE"

section 'path pickers'
assert_contains "no × while a field is empty"     'xbefore=hidden'       "$PROBE"
assert_contains "Browse opens the picker"         'picker=open'          "$PROBE"
assert_contains "in the workflow's own space"     'spacelocked=yes'      "$PROBE"
assert_contains "a folder picker offers no pages" 'foldermode=nofiles'   "$PROBE"
assert_contains "choosing a folder fills it in"   'folder=Docs'          "$PROBE"
assert_contains "and shows the ×"                 'xafter=shown'         "$PROBE"
assert_contains "the × clears it and goes away"   'cleared=[]/hidden'    "$PROBE"
assert_contains "a chat field offers only chats"  'chatfiles=Team.chat ' "$PROBE"
assert_contains "choosing a chat fills it in"     'chat=Team.chat'       "$PROBE"
assert_contains "the test page is browsable too"  'testpath=Docs/a.md'   "$PROBE"

section 'the editor'
assert_contains "a tag trigger asks for the tag"  'tagbox=yes'           "$PROBE"
assert_contains "adding an action keeps the first" 'kept=seen, queued'   "$PROBE"
assert_contains "Test previews the unsaved form"  'preview=rendered'     "$PROBE"
assert_contains "  …every action of it"           'previewtags=yes'      "$PROBE"
assert_contains "saving lists it"                 'rows=1'               "$PROBE"
assert_contains "the trigger reached the server"  'stored=tag_added/review/Docs' "$PROBE"
assert_contains "both actions, in order"          'actions=tag+chat'     "$PROBE"
assert_contains "the tags were split"             'tags=seen,queued'     "$PROBE"
assert_contains "new workflows start on"          'on=true'              "$PROBE"

section 'the overview'
assert_contains "the switch reaches the server"   'toggled=false'        "$PROBE"
assert_contains "and the row shows it is off"     'dimmed=yes'           "$PROBE"
assert_contains "edit opens what was saved"       'editname=Review edittrigger=tag_added' "$PROBE"
assert_contains "  …with both actions"            'editcards=2'          "$PROBE"
assert_contains "Run now is not offered unsaved"  'runnew=no'            "$PROBE"
assert_contains "it asks first"                   'confirm=asked'        "$PROBE"
assert_contains "and shows the real result"       'ran=yes'              "$PROBE"
assert_contains "  …which really happened"        'posted=yes'           "$PROBE"
assert_contains "history lists that run"          'history=rows'         "$PROBE"
assert_contains "and back returns to the list"    'back=1'               "$PROBE"

printf '\n'
exit $(( ASSERT_FAIL > 0 ))
