# Astucia Wiki — Copyright (C) 2026 Mads Rotwitt
# Free software under the GNU GPL v3 or later. See LICENSE for the full notice,
# or <https://www.gnu.org/licenses/>. Distributed WITHOUT ANY WARRANTY.
#
# A throwaway wiki, for tests to exercise the real code against.
#
# This is the pattern CLAUDE.md already prescribes for verifying a change — a copy of the
# repository with a config.php built from the template and paths pointed at a temp
# directory — turned into something reusable so that checks accumulate instead of being
# hand-rolled each time.
#
#   fixture_start [auth_mode]     copy the repo, write config, start php -S
#   fixture_space  <name>         create a Space
#   fixture_page   <rel> <text>   write a content file (path is relative to PAGES_DIR)
#   fixture_users  <json>         write WIKI_SYSTEM_DATA/users.json
#   fixture_login  <jar> <query>  establish a session; see __test_login.php below
#   fixture_stop                  kill the server, remove everything
#
# After fixture_start these are exported:
#   WIKI_URL    base URL of the running wiki
#   WIKI_ROOT   the temp directory
#   WIKI_PAGES  PAGES_DIR
#   WIKI_SYS    WIKI_SYSTEM_DATA
#   WIKI_APP    the copy of the application

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

# A port nobody else is on, so parallel runs and CI do not collide.
_free_port() {
    python3 -c 'import socket; s=socket.socket(); s.bind(("127.0.0.1",0)); print(s.getsockname()[1]); s.close()'
}

fixture_start() {
    local auth="${1:-off}"
    WIKI_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/astucia-test.XXXXXX")"
    WIKI_APP="$WIKI_ROOT/app"
    WIKI_PAGES="$WIKI_ROOT/pages"
    WIKI_SYS="$WIKI_ROOT/system"
    mkdir -p "$WIKI_PAGES" "$WIKI_SYS" "$WIKI_ROOT/logs"

    # Copy the working tree, not a git export: the point is to test what is on disk now.
    # .git is skipped because it is large and irrelevant.
    mkdir -p "$WIKI_APP"
    tar -C "$REPO_ROOT" --exclude=.git --exclude=tests -cf - . | tar -C "$WIKI_APP" -xf -

    # config.php from the checked-in template, so a constant added to the template without
    # a matching test default shows up here rather than in production.
    sed -e "s#^define('PAGES_DIR'.*#define('PAGES_DIR', '$WIKI_PAGES/');#" \
        -e "s#^define('WIKI_SYSTEM_DATA'.*#define('WIKI_SYSTEM_DATA', '$WIKI_SYS/');#" \
        -e "s#^define('LOG_DIR'.*#define('LOG_DIR', '$WIKI_ROOT/logs/');#" \
        -e "s#^define('AUTHENTICATION',.*#define('AUTHENTICATION', '$auth');#" \
        "$REPO_ROOT/config.php.txt" > "$WIKI_APP/config.php"

    # A session shim, generated here and never committed, so there is no possibility of it
    # existing in a real deployment. It builds exactly the session shape auth.php does:
    # an OIDC session carries `sub`, an OTP session does not.
    cat > "$WIKI_APP/__test_login.php" <<'SHIM'
<?php
// GENERATED BY tests/lib/fixture.sh — never part of a release.
session_start();
$auth = $_GET['auth'] ?? 'oidc';
$u = [
    'uid'    => (int)($_GET['uid'] ?? 1),
    'name'   => $_GET['name'] ?? 'Test User',
    'email'  => $_GET['email'] ?? 'test@example.com',
    'role'   => $_GET['role'] ?? 'admin',
    'auth'   => $auth,
    'spaces' => isset($_GET['spaces']) && $_GET['spaces'] !== ''
                ? array_values(array_filter(explode(',', $_GET['spaces']))) : null,
];
if ($auth === 'oidc') $u['sub'] = $_GET['sub'] ?? ('sub-' . $u['uid']);
$_SESSION['user'] = $u;
echo 'ok';
SHIM

    local port; port="$(_free_port)"
    WIKI_URL="http://127.0.0.1:$port"
    ( cd "$WIKI_APP" && exec php -S "127.0.0.1:$port" ) > "$WIKI_ROOT/server.log" 2>&1 &
    WIKI_PID=$!

    # Poll for readiness rather than sleeping a guessed interval.
    local i=0
    until curl -sf --max-time 2 "$WIKI_URL/api.php?action=ping" > /dev/null 2>&1; do
        i=$((i + 1))
        if [ $i -gt 100 ]; then
            echo "fixture: server did not start; log follows" >&2
            cat "$WIKI_ROOT/server.log" >&2
            return 1
        fi
        sleep 0.1
    done
    export WIKI_URL WIKI_ROOT WIKI_PAGES WIKI_SYS WIKI_APP WIKI_PID
}

fixture_stop() {
    [ -n "${WIKI_PID:-}" ] && kill "$WIKI_PID" 2>/dev/null
    wait "$WIKI_PID" 2>/dev/null
    [ -n "${WIKI_ROOT:-}" ] && [ -d "$WIKI_ROOT" ] && rm -rf "$WIKI_ROOT"
    return 0
}

fixture_space() { mkdir -p "$WIKI_PAGES/$1"; }

fixture_page() {
    mkdir -p "$(dirname "$WIKI_PAGES/$1")"
    printf '%s\n' "$2" > "$WIKI_PAGES/$1"
}

fixture_users() { printf '%s\n' "$1" > "$WIKI_SYS/users.json"; }

# fixture_login <cookie-jar> <query-string>
#   fixture_login "$JAR" "uid=2&name=Bob&role=editor&spaces=Alpha"
fixture_login() {
    rm -f "$1"
    curl -s -b "$1" -c "$1" --max-time 10 "$WIKI_URL/__test_login.php?$2" > /dev/null
}

# GET as a logged-in browser. wget_as <jar> <path-and-query>
get_as()  { curl -s  -b "$1" -c "$1" --max-time 15 "$WIKI_URL/$2"; }
# POST with form data. post_as <jar> <path-and-query> <data>
post_as() { curl -s  -b "$1" -c "$1" --max-time 15 -X POST -d "$3" "$WIKI_URL/$2"; }
# GET returning only the HTTP status.
status_as() { curl -s -o /dev/null -w '%{http_code}' -b "$1" -c "$1" --max-time 15 "$WIKI_URL/$2"; }
# GET with a service token instead of a session.
get_token() { curl -s --max-time 15 -H "Authorization: Bearer $1" "$WIKI_URL/$2"; }
